# Generated by Django 6.0 on 2025-12-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_vehicle_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='confidence',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='destination',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit margin %', max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='sla_hours',
            field=models.IntegerField(default=48, help_text='Service Level Agreement in hours'),
        ),
    ]
