# Generated by Django 5.2.9 on 2026-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_date_format_user_job_title_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default=dict),
        ),
    ]
