# Generated by Django 6.0.2 on 2026-02-23 11:40

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_avatar_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested advance amount (before fees) in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee amount in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount disbursed (amount - fee) in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('REQUESTED', 'Requested'), ('SCORING', 'Scoring'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('DISBURSED', 'Disbursed'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='ELIGIBLE', help_text='Current status of the advance request', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, help_text='When the advance was requested', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the advance was approved', null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, help_text='When funds were disbursed', null=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='When the advance was settled (invoice paid)', null=True)),
                ('denial_reason', models.TextField(blank=True, help_text='Reason for denial if status is DENIED', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this advance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('DENY', 'Deny'), ('DISBURSE', 'Disburse'), ('SETTLE', 'Settle'), ('CANCEL', 'Cancel'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('OTHER', 'Other')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('resource_type', models.CharField(db_index=True, help_text='Type of resource affected (model name)', max_length=100)),
                ('resource_id', models.CharField(db_index=True, help_text='ID of the affected resource', max_length=100)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, help_text='Total facility limit in ZAR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding advances in ZAR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='Current facility status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(help_text='Total risk score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tier', models.CharField(choices=[('EXCELLENT', 'Excellent (85-100)'), ('GOOD', 'Good (70-84)'), ('FAIR', 'Fair (55-69)'), ('ELEVATED', 'Elevated (40-54)'), ('INELIGIBLE', 'Ineligible (<40)')], db_index=True, help_text='Risk tier based on total score', max_length=20)),
                ('fee_percent', models.DecimalField(decimal_places=2, help_text='Fee percentage (0-10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Calculated fee amount in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('factor_payment_history', models.IntegerField(default=0, help_text='Payment history score (0-35 points, 35% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('factor_invoice_age', models.IntegerField(default=0, help_text='Invoice age score (0-20 points, 20% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('factor_pod_quality', models.IntegerField(default=0, help_text='POD quality score (0-15 points, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('factor_credit_score', models.IntegerField(default=0, help_text='Credit score factor (0-15 points, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('factor_relationship_length', models.IntegerField(default=0, help_text='Relationship length score (0-10 points, 10% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('factor_facility_ratio', models.IntegerField(default=0, help_text='Facility ratio score (0-5 points, 5% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('factors_breakdown', models.JSONField(default=dict, help_text='Detailed explanation for each factor score')),
                ('is_eligible', models.BooleanField(db_index=True, default=True, help_text='Whether invoice is eligible for early payment')),
                ('ineligibility_reason', models.TextField(blank=True, help_text='Reason for ineligibility if not eligible', null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='When this score was calculated')),
                ('expires_at', models.DateTimeField(help_text='When this score expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Starting location of the trip', max_length=500)),
                ('destination', models.CharField(help_text='Destination location of the trip', max_length=500)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled in kilometers', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, help_text='Estimated distance in kilometers', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.DateTimeField(blank=True, help_text='Actual trip start time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Actual trip end time', null=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, help_text='Estimated trip duration in hours', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('pod_uploaded', models.BooleanField(default=False, help_text='Whether POD has been uploaded')),
                ('pod_file', models.FileField(blank=True, help_text='Uploaded POD file (signature image or document)', null=True, upload_to='pod_files/%Y/%m/%d/')),
                ('pod_type', models.CharField(choices=[('E_SIGNATURE', 'E-Signature'), ('PHOTO', 'Photo'), ('MANUAL', 'Manual'), ('PENDING', 'Pending')], default='PENDING', help_text='Type of POD submitted', max_length=20)),
                ('pod_verified', models.BooleanField(default=False, help_text='Whether POD has been verified by admin')),
                ('pod_quality_score', models.IntegerField(default=0, help_text='POD quality score (0-15) used in risk calculation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('actual_fuel_litres', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fuel consumed in litres', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_toll_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual toll costs in ZAR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the trip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(blank=True, help_text='Customer credit score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_score_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('DNB', 'Dun & Bradstreet'), ('TRUCKWYS', 'TruckWys Internal')], default='MANUAL', help_text='Source of credit score data', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_score_updated_at',
            field=models.DateTimeField(blank=True, help_text='When credit score was last updated', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether customer account is active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_default',
            field=models.CharField(choices=[('NET30', 'Net 30 Days'), ('NET60', 'Net 60 Days'), ('NET90', 'Net 90 Days')], default='NET30', help_text='Default payment terms for this customer', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this expense has been approved'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this expense was approved', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Scanned receipt or invoice', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='early_pay_eligible',
            field=models.BooleanField(default=False, help_text='Whether this invoice is eligible for early payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='early_pay_offered',
            field=models.BooleanField(default=False, help_text='Whether early payment has been offered for this invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was fully paid', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('NET30', 'Net 30 Days'), ('NET60', 'Net 60 Days'), ('NET90', 'Net 90 Days')], default='NET30', help_text='Payment terms for this invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated invoice PDF', null=True, upload_to='invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was sent to the customer', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount (15% in South Africa)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was first viewed by customer', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLLS', 'Tolls'), ('MAINTENANCE', 'Maintenance'), ('DRIVER', 'Driver Expenses'), ('INSURANCE', 'Insurance'), ('OVERHEAD', 'Overhead'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('EARLY_PAY', 'Early Payment Advance'), ('CREDIT_CARD', 'Credit Card'), ('ACH', 'ACH')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_name_25d5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_is_acti_0e47e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='customers_created_beab7c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_invoice_9dd568_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='payments_payment_f51455_idx'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice to advance', on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.ForeignKey(help_text='Company that owns this facility', on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='core.company'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='facility',
            field=models.ForeignKey(help_text='Facility used for this advance', on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to='core.facility'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='company',
            field=models.ForeignKey(help_text='Company requesting the score', on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='core.company'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='customer',
            field=models.ForeignKey(help_text='Customer being assessed', on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='core.customer'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='risk_score',
            field=models.ForeignKey(blank=True, help_text='Risk assessment for this advance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to='core.riskscore'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(help_text='Driver assigned to this trip', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='load',
            field=models.ForeignKey(help_text='The load/order this trip is delivering', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.load'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(help_text='Vehicle assigned to this trip', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Trip this expense is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.trip'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Trip this invoice is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.trip'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_categor_a6f264_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['approved'], name='expenses_approve_74438a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-expense_date'], name='expenses_expense_090a91_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_created_3daf52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['company', 'status'], name='facilities_company_31c1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['-created_at'], name='facilities_created_0f6fce_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['invoice', '-calculated_at'], name='risk_scores_invoice_1c295f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['customer', '-calculated_at'], name='risk_scores_custome_f3182b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['tier'], name='risk_scores_tier_4807a3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['is_eligible'], name='risk_scores_is_elig_3621e3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['expires_at'], name='risk_scores_expires_d9d37c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['status'], name='advance_req_status_c11515_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['invoice'], name='advance_req_invoice_e3c76b_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['facility'], name='advance_req_facilit_26c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['-created_at'], name='advance_req_created_c04f68_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['disbursed_at'], name='advance_req_disburs_0799bb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_status_b30e85_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_time'], name='trips_start_t_005982_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-created_at'], name='trips_created_2bb114_idx'),
        ),
    ]
