# Generated by Django 6.0.2 on 2026-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_advancerequest_auditlog_facility_riskscore_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fuel_price_per_litre',
            field=models.DecimalField(decimal_places=2, default=23.5, help_text='Current fuel price per litre in ZAR (default: R23.50)', max_digits=6),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Approval status of this expense', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Invoice line items with descriptions, quantities, and amounts'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_per_km',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='Fuel consumption in litres per km (default: 0.35 L/km for trucks)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this expense has been approved (deprecated, use status)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLLS', 'Tolls'), ('MAINTENANCE', 'Maintenance'), ('DRIVER_COST', 'Driver Cost'), ('INSURANCE', 'Insurance'), ('OVERHEAD', 'Overhead'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('EARLY_PAY', 'Early Payment Advance'), ('EFT', 'Electronic Funds Transfer'), ('CREDIT_CARD', 'Credit Card'), ('ACH', 'ACH')], db_index=True, max_length=50),
        ),
    ]
