# Generated by Django 6.0.2 on 2026-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_fuel_price_per_litre_expense_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='xero_access_token',
            field=models.TextField(blank=True, help_text='Xero OAuth access token (encrypted in production)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='xero_connected_at',
            field=models.DateTimeField(blank=True, help_text='When Xero was connected', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='xero_refresh_token',
            field=models.TextField(blank=True, help_text='Xero OAuth refresh token (encrypted in production)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='xero_tenant_id',
            field=models.CharField(blank=True, help_text='Xero tenant/organization ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='xero_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current Xero access token expires', null=True),
        ),
    ]
