# Generated by Django 6.0.2 on 2026-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_xero_access_token_company_xero_connected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='driver_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='toll_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
