# Generated by Django 6.0.2 on 2026-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_quote_toll_driver_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pod_document',
            field=models.FileField(blank=True, null=True, upload_to='pod/'),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
