# Generated by Django 6.0.2 on 2026-02-27 20:08

import core.models.webhook
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_load_pod_document_alter_load_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(default=core.models.webhook.generate_webhook_secret, max_length=64)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('active', models.BooleanField(default=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
