# Generated by Django 6.0.2 on 2026-02-27 20:33

import core.models.integration_api_key
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this key (e.g., 'ABC Fleet System')", max_length=100)),
                ('key', models.CharField(db_index=True, default=core.models.integration_api_key.generate_api_key, max_length=64, unique=True)),
                ('key_type', models.CharField(choices=[('LENDER', 'Lender'), ('FLEET_TMS', 'Fleet TMS'), ('PARTNER', 'Partner')], default='FLEET_TMS', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(help_text='User/company that owns this key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'active'], name='integration_key_3dc066_idx'), models.Index(fields=['key_type', 'active'], name='integration_key_typ_a29601_idx')],
            },
        ),
    ]
