# Generated by Django 6.0.2 on 2026-03-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='core.quote'),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('LOADING', 'Loading'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
