# Generated by Django 6.0.2 on 2026-03-02 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_load_quote_alter_load_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='factor_client_financial',
            field=models.IntegerField(default=0, help_text='Pillar 2: Client Financial Health raw score (0-100, 20% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_client_identity',
            field=models.IntegerField(default=0, help_text='Pillar 1: Client Identity & Profile raw score (0-100, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_debtor_credit',
            field=models.IntegerField(default=0, help_text='Pillar 3: Debtor Creditworthiness raw score (0-100, 20% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_invoice_chars',
            field=models.IntegerField(default=0, help_text='Pillar 4: Invoice Characteristics raw score (0-100, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_macro_market',
            field=models.IntegerField(default=0, help_text='Pillar 7: Macro & Market Factors raw score (0-100, 10% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_operational',
            field=models.IntegerField(default=0, help_text='Pillar 6: Operational & Trip Factors raw score (0-100, 10% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='factor_pod_docs',
            field=models.IntegerField(default=0, help_text='Pillar 5: POD & Documentation raw score (0-100, 10% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_credit_score',
            field=models.IntegerField(default=0, help_text='DEPRECATED: Credit score factor (0-15 points, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_facility_ratio',
            field=models.IntegerField(default=0, help_text='DEPRECATED: Facility ratio score (0-5 points, 5% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_invoice_age',
            field=models.IntegerField(default=0, help_text='DEPRECATED: Invoice age score (0-20 points, 20% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_payment_history',
            field=models.IntegerField(default=0, help_text='DEPRECATED: Payment history score (0-35 points, 35% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_pod_quality',
            field=models.IntegerField(default=0, help_text='DEPRECATED: POD quality score (0-15 points, 15% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='factor_relationship_length',
            field=models.IntegerField(default=0, help_text='DEPRECATED: Relationship length score (0-10 points, 10% weight)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='tier',
            field=models.CharField(choices=[('PRIME', 'Prime (85-100)'), ('STANDARD', 'Standard (70-84)'), ('ELEVATED', 'Elevated (55-69)'), ('HIGH', 'High (40-54)'), ('INELIGIBLE', 'Ineligible (<40)'), ('EXCELLENT', 'Excellent (85-100) - DEPRECATED'), ('GOOD', 'Good (70-84) - DEPRECATED'), ('FAIR', 'Fair (55-69) - DEPRECATED')], db_index=True, help_text='Risk tier based on total score', max_length=20),
        ),
    ]
