# Generated by Django 6.0.2 on 2026-03-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_7_pillar_risk_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_turnover',
            field=models.DecimalField(decimal_places=2, default=5000000.0, help_text='ZAR annual turnover', max_digits=12),
        ),
        migrations.AddField(
            model_name='company',
            name='b_bbee_level',
            field=models.IntegerField(blank=True, default=4, help_text='B-BBEE level (1-8)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('owner_operator', 'Owner Operator'), ('fleet_operator', 'Fleet Operator'), ('broker', 'Broker')], default='owner_operator', help_text='Type of business operation', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='cipc_age_years',
            field=models.IntegerField(default=5, help_text='Years since CIPC registration'),
        ),
        migrations.AddField(
            model_name='company',
            name='fleet_size',
            field=models.IntegerField(default=10, help_text='Number of vehicles in fleet'),
        ),
        migrations.AddField(
            model_name='company',
            name='insurance_status',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('basic', 'Basic'), ('none', 'None')], default='comprehensive', help_text='Insurance coverage level', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='province_count',
            field=models.IntegerField(default=1, help_text='Number of provinces operated in'),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_sector',
            field=models.CharField(choices=[('general_freight', 'General Freight'), ('refrigerated', 'Refrigerated'), ('hazmat', 'Hazmat'), ('abnormal', 'Abnormal'), ('container', 'Container')], default='general_freight', help_text='Freight sub-sector specialization', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='turnover_trend',
            field=models.CharField(choices=[('growing', 'Growing'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', help_text='Annual turnover trend', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='avg_days_to_pay',
            field=models.IntegerField(default=30, help_text='Historical average days to pay invoices'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dispute_rate',
            field=models.DecimalField(decimal_places=2, default=0.02, help_text='Dispute rate ratio (0 to 1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_consistency',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Payment consistency ratio (0 to 1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_invoices_late',
            field=models.IntegerField(default=2, help_text='Total number of late payments'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_invoices_paid',
            field=models.IntegerField(default=10, help_text='Total number of invoices paid by this customer'),
        ),
        migrations.AddField(
            model_name='driver',
            name='accident_history',
            field=models.IntegerField(default=0, help_text='Number of accidents in history'),
        ),
        migrations.AddField(
            model_name='driver',
            name='experience_years',
            field=models.IntegerField(default=3, help_text='Years of driving experience'),
        ),
        migrations.AddField(
            model_name='driver',
            name='violation_count',
            field=models.IntegerField(default=0, help_text='Number of traffic violations'),
        ),
    ]
