# Generated by Django 6.0.2 on 2026-03-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_company_annual_turnover_company_b_bbee_level_and_more'),
    ]

    operations = [
    ]
