# Generated by Django 6.0.2 on 2026-03-02 22:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_vehicletype_company_alter_vehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='fee_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), help_text='Fee percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
