# Generated by Django 6.0.2 on 2026-03-02 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_advance_fee_percent_3dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_payment_date', models.DateField(help_text='Expected payment date (usually invoice due date)')),
                ('actual_payment_date', models.DateField(blank=True, help_text='Actual date payment was received', null=True)),
                ('days_late', models.IntegerField(default=0, help_text='Number of days late (0 if on-time or early)', validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount paid in ZAR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('defaulted', models.BooleanField(db_index=True, default=False, help_text='Whether payment defaulted (>90 days late or collection required)')),
                ('partial_payment', models.BooleanField(default=False, help_text='Whether payment was partial')),
                ('dispute_raised', models.BooleanField(default=False, help_text='Whether customer raised a dispute')),
                ('collection_required', models.BooleanField(default=False, help_text='Whether collection process was required')),
                ('feature_snapshot', models.JSONField(default=dict, help_text='Feature values at time of scoring (for training)')),
                ('risk_score_at_time', models.IntegerField(blank=True, help_text='Risk score calculated at time of advance', null=True)),
                ('risk_tier_at_time', models.CharField(default='UNKNOWN', help_text='Risk tier at time of scoring', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advance', models.ForeignKey(blank=True, help_text='Advance request if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_outcomes', to='core.advancerequest')),
                ('invoice', models.OneToOneField(help_text='Invoice this outcome is for', on_delete=django.db.models.deletion.PROTECT, related_name='payment_outcome', to='core.invoice')),
            ],
            options={
                'db_table': 'payment_outcomes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['defaulted'], name='payment_out_default_f14ad3_idx'), models.Index(fields=['days_late'], name='payment_out_days_la_6c45ab_idx'), models.Index(fields=['expected_payment_date'], name='payment_out_expecte_4d8b91_idx'), models.Index(fields=['actual_payment_date'], name='payment_out_actual__067188_idx'), models.Index(fields=['-created_at'], name='payment_out_created_fe6cdc_idx')],
            },
        ),
    ]
