# Generated by Django 6.0.2 on 2026-03-02 23:07

import core.models.webhook_subscription
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_payment_outcome_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(help_text='Partner company name', max_length=200)),
                ('webhook_url', models.URLField(help_text='URL to deliver webhook events', max_length=500)),
                ('events', models.JSONField(default=list, help_text="List of event types to subscribe to (e.g., ['invoice.created', 'load.delivered'])")),
                ('api_key', models.CharField(db_index=True, default=core.models.webhook_subscription.generate_api_key, help_text='API key for authenticating partner API requests', max_length=64, unique=True)),
                ('secret', models.CharField(default=core.models.webhook_subscription.generate_webhook_secret, help_text='Secret key used for HMAC signature verification', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, help_text='Last successful webhook delivery timestamp', null=True)),
                ('failure_count', models.IntegerField(default=0, help_text='Number of consecutive delivery failures')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', 'is_active'], name='webhook_sub_api_key_0c328c_idx'), models.Index(fields=['is_active'], name='webhook_sub_is_acti_76d62e_idx')],
            },
        ),
    ]
