# Generated by Django 6.0.2 on 2026-03-13 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique invite token', unique=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name (fallback if company FK is null)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('company', models.ForeignKey(blank=True, help_text='Company the user is being invited to join', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.company')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invites_token_1dea89_idx'), models.Index(fields=['email'], name='invites_email_bc31b6_idx')],
            },
        ),
    ]
