# Generated by Django 6.0.2 on 2026-03-18 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Effective date of these fuel prices')),
                ('diesel_inland', models.DecimalField(decimal_places=2, help_text='Diesel price per liter in ZAR for inland regions', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('diesel_coastal', models.DecimalField(decimal_places=2, help_text='Diesel price per liter in ZAR for coastal regions', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('petrol_95', models.DecimalField(decimal_places=2, help_text='Petrol 95 Octane price per liter in ZAR', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('petrol_93', models.DecimalField(decimal_places=2, help_text='Petrol 93 Octane price per liter in ZAR', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(default='FIASA', help_text='Source of the price data (e.g., FIASA, manual entry, scraped)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Price',
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='core_fuelpr_date_5fad84_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('truck_type', models.CharField(max_length=50)),
                ('load_type', models.CharField(max_length=50)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('toll_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tyre_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadhead_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_return_load', models.BooleanField(default=False)),
                ('client_segment', models.CharField(max_length=50)),
                ('quoted_margin_pct', models.FloatField()),
                ('actual_margin_pct', models.FloatField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route_category', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Training Record',
                'verbose_name_plural': 'Quote Training Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accepted'], name='core_quotet_accepte_9624ae_idx'), models.Index(fields=['client_segment'], name='core_quotet_client__33f887_idx'), models.Index(fields=['truck_type'], name='core_quotet_truck_t_c0cc2e_idx'), models.Index(fields=['-created_at'], name='core_quotet_created_d08164_idx')],
            },
        ),
        migrations.CreateModel(
            name='TollPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the toll plaza', max_length=200)),
                ('route', models.CharField(db_index=True, help_text='Route identifier (e.g., N1, N2, N3, N4)', max_length=50)),
                ('province', models.CharField(help_text='South African province where the toll plaza is located', max_length=100)),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SE', 'Southeast'), ('SW', 'Southwest')], help_text='Primary direction of travel', max_length=2)),
                ('location_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km from route start point', max_digits=8, null=True)),
                ('class2_cost', models.DecimalField(decimal_places=2, help_text='Cost in ZAR for Class 2 (light motor vehicles)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('class3_cost', models.DecimalField(decimal_places=2, help_text='Cost in ZAR for Class 3 (medium vehicles)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('class4_cost', models.DecimalField(decimal_places=2, help_text='Cost in ZAR for Class 4 (heavy 2-axle)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('class5_cost', models.DecimalField(decimal_places=2, help_text='Cost in ZAR for Class 5 (heavy 3+ axle, semis)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Toll Plaza',
                'verbose_name_plural': 'Toll Plazas',
                'ordering': ['route', 'location_km'],
                'indexes': [models.Index(fields=['route'], name='core_tollpl_route_f80d41_idx'), models.Index(fields=['route', 'location_km'], name='core_tollpl_route_16eaa1_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(choices=[('semi_34t', 'Semi-trailer 34 ton'), ('rigid_8t', 'Rigid 8 ton'), ('flatbed', 'Flatbed truck'), ('tipper', 'Tipper truck'), ('reefer', 'Refrigerated truck'), ('tanker', 'Tanker truck')], db_index=True, help_text='Type of truck for this cost profile', max_length=50)),
                ('fuel_cpk', models.DecimalField(decimal_places=2, help_text='Fuel cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tyre_cpk', models.DecimalField(decimal_places=2, help_text='Tyre wear cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_cpk', models.DecimalField(decimal_places=2, help_text='Maintenance cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('driver_cost_per_day', models.DecimalField(decimal_places=2, help_text='Driver cost per day in ZAR (includes salary, accommodation, meals)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_rfa_baseline', models.BooleanField(db_index=True, default=False, help_text='True if this is an RFA baseline, False if company override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company that owns this profile (null for RFA baselines)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_cost_profiles', to='core.company')),
            ],
            options={
                'verbose_name': 'Vehicle Cost Profile',
                'verbose_name_plural': 'Vehicle Cost Profiles',
                'ordering': ['truck_type', '-is_rfa_baseline'],
                'indexes': [models.Index(fields=['truck_type', 'is_rfa_baseline'], name='core_vehicl_truck_t_9d5757_idx'), models.Index(fields=['truck_type', 'company'], name='core_vehicl_truck_t_41de0d_idx')],
                'constraints': [models.UniqueConstraint(fields=('truck_type', 'company'), name='unique_truck_type_per_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('is_rfa_baseline', True)), fields=('truck_type',), name='unique_rfa_baseline_per_truck_type')],
            },
        ),
    ]
