# Generated by Django 6.0.3 on 2026-03-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_webhooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('DISPATCHER', 'Dispatcher'), ('VIEWER', 'Viewer'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=20),
        ),
    ]
