# Generated by Django 6.0.3 on 2026-03-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_webhooksubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payfast_token',
            field=models.CharField(blank=True, help_text='PayFast subscription token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, help_text='Our m_payment_id sent to PayFast', max_length=200)),
                ('payfast_payment_id', models.CharField(blank=True, help_text='PayFast pf_payment_id returned in ITN', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('plan', models.CharField(blank=True, help_text='Plan key at time of transaction', max_length=20)),
                ('payment_status', models.CharField(blank=True, help_text='Raw payment_status from PayFast ITN', max_length=50)),
                ('raw_itn_data', models.JSONField(blank=True, default=dict, help_text='Full ITN payload for audit trail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to='core.company')),
            ],
            options={
                'db_table': 'billing_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
