# Generated by Django 6.0.3 on 2026-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_company_payfast_token_company_subscription_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
