# Generated by Django 6.0.2 on 2026-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_company_payfast_token_company_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_calls_reset_date',
            field=models.DateField(blank=True, help_text='Date when API call counter was last reset', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='api_calls_this_month',
            field=models.IntegerField(default=0, help_text='Number of API calls made this month (resets monthly)'),
        ),
    ]
