# Generated by Django 6.0.2 on 2026-03-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_invitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentoutcome',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Invoice this outcome is for (null for synthetic training data)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_outcome', to='core.invoice'),
        ),
    ]
