# Generated by Django 6.0.2 on 2026-03-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tollplaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DISPATCHER', 'Dispatcher'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner')], default='ADMIN', max_length=20),
        ),
    ]
