# Generated by Django 6.0.2 on 2026-03-19 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_seed_rfa_vci_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('truck_type', models.CharField(max_length=50)),
                ('load_type', models.CharField(max_length=50)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('toll_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tyre_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadhead_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_return_load', models.BooleanField(default=False)),
                ('client_segment', models.CharField(max_length=50)),
                ('quoted_margin_pct', models.FloatField()),
                ('actual_margin_pct', models.FloatField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route_category', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Training Record',
                'verbose_name_plural': 'Quote Training Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fuelprice',
            options={'ordering': ['-date'], 'verbose_name': 'Fuel Price', 'verbose_name_plural': 'Fuel Prices'},
        ),
        migrations.AlterModelOptions(
            name='tollplaza',
            options={'ordering': ['route', 'location_km'], 'verbose_name': 'Toll Plaza', 'verbose_name_plural': 'Toll Plazas'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecostprofile',
            options={'ordering': ['-effective_date', 'truck_type'], 'verbose_name': 'Vehicle Cost Profile', 'verbose_name_plural': 'Vehicle Cost Profiles'},
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(db_index=True, help_text='Effective date of these fuel prices'),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='diesel_coastal',
            field=models.DecimalField(decimal_places=2, help_text='Diesel price per liter in ZAR for coastal regions', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='diesel_inland',
            field=models.DecimalField(decimal_places=2, help_text='Diesel price per liter in ZAR for inland regions', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_93',
            field=models.DecimalField(decimal_places=2, help_text='Petrol 93 Octane price per liter in ZAR', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_95',
            field=models.DecimalField(decimal_places=2, help_text='Petrol 95 Octane price per liter in ZAR', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='source',
            field=models.CharField(default='FIASA', help_text='Source of the price data (e.g., FIASA, manual entry, scraped)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='direction',
            field=models.CharField(help_text='Direction of travel on route', max_length=100),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='location_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='name',
            field=models.CharField(help_text='Name of the toll plaza', max_length=100),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='route',
            field=models.CharField(db_index=True, help_text='Route (e.g. N1, N3)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='tariff_class_2',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='tariff_class_3',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='tariff_class_4',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='tariff_class_5',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='tariff_year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DISPATCHER', 'Dispatcher'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclecostprofile',
            name='driver_cost_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Driver cost per day in ZAR (includes salary, accommodation, meals)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclecostprofile',
            name='fuel_cpk',
            field=models.DecimalField(decimal_places=4, help_text='Fuel cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclecostprofile',
            name='maintenance_cpk',
            field=models.DecimalField(decimal_places=4, help_text='Maintenance cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclecostprofile',
            name='tyre_cpk',
            field=models.DecimalField(decimal_places=4, help_text='Tyre wear cost per kilometer in ZAR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['-date'], name='fuel_prices_date_c92cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tollplaza',
            index=models.Index(fields=['route'], name='toll_plazas_route_64fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='tollplaza',
            index=models.Index(fields=['route', 'location_km'], name='toll_plazas_route_3d18fc_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetrainingrecord',
            index=models.Index(fields=['accepted'], name='core_quotet_accepte_9624ae_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetrainingrecord',
            index=models.Index(fields=['client_segment'], name='core_quotet_client__33f887_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetrainingrecord',
            index=models.Index(fields=['truck_type'], name='core_quotet_truck_t_c0cc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetrainingrecord',
            index=models.Index(fields=['-created_at'], name='core_quotet_created_d08164_idx'),
        ),
    ]
