# Generated by Django 6.0.2 on 2026-03-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_quote_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('IT', 'In-Transit'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
