# Generated by Django 6.0.2 on 2026-03-19 18:55
#
# NO-OP: this migration originally re-added the Quote.token column (AddField +
# populate + unique AlterField), but 0036_add_quote_token already does exactly
# that earlier in the dependency chain. Applying both against a fresh database
# fails with: column "token" of relation "quotes" already exists. The operations
# are removed so this is a harmless no-op; the file is kept so the migration
# graph and any dependents stay intact.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_quote_status'),
    ]

    operations = []
