# Generated by Django 6.0.2 on 2026-03-19 18:55

from django.db import migrations, models
import secrets


def generate_tokens(apps, schema_editor):
    Quote = apps.get_model('core', 'Quote')
    for quote in Quote.objects.all():
        if not quote.token:
            quote.token = secrets.token_urlsafe(32)
            quote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(generate_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quote',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
