# Generated by Django 6.0.2 on 2026-03-20 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20260319_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelprice',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when price was fetched'),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='True if price is older than 7 days'),
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quote was accepted', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_price_at_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fuel price snapshot at quote creation time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Quote outcome for ML training', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quote was rejected', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='win_probability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Predicted win probability (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(help_text='Date of the fuel price', unique=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_93',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 93 ULP inland retail price (ZAR/litre)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_95',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 95 ULP inland retail price (ZAR/litre)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='source',
            field=models.CharField(default='SAPIA', help_text='Data source identifier (FIASA, globalpetrolprices.com, etc)', max_length=100),
        ),
        migrations.CreateModel(
            name='QuoteOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Quote outcome: accepted or rejected', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price', max_digits=12, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Realized margin percentage', max_digits=5, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Route distance in km', max_digits=10, null=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='Vehicle type for the quote', max_length=50)),
                ('origin', models.CharField(blank=True, help_text='Origin location code', max_length=50)),
                ('destination', models.CharField(blank=True, help_text='Destination location code', max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo weight in kg', max_digits=10, null=True)),
                ('client_tier', models.CharField(blank=True, help_text='Client tier: new, regular, vip', max_length=20)),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=4, help_text='Fuel price at quote creation', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.quote')),
            ],
            options={
                'db_table': 'quote_outcomes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quote'], name='quote_outco_quote_i_83dc94_idx'), models.Index(fields=['outcome'], name='quote_outco_outcome_554318_idx'), models.Index(fields=['created_at'], name='quote_outco_created_16015d_idx')],
            },
        ),
    ]
