# Generated by Django 6.0.6 on 2026-06-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_user_role'),
        ('core', '0039_fuelprice_fetched_at_fuelprice_is_stale_and_more'),
    ]

    operations = [
    ]
