# Generated by Django 6.0.6 on 2026-06-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_driver_company_alter_company_subscription_plan_and_more'),
        ('core', '0041_seed_default_vehicle_types'),
    ]

    operations = [
    ]
