# Generated by Django 6.0.6 on 2026-06-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge_20260616_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapikey',
            name='monthly_quota',
            field=models.PositiveIntegerField(default=0, help_text='Calls allowed per calendar month (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='quota_period',
            field=models.CharField(blank=True, default='', help_text='YYYY-MM window quota_used tracks', max_length=7),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='quota_used',
            field=models.PositiveIntegerField(default=0, help_text='Calls used in the current quota window'),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Total metered API calls on this key'),
        ),
    ]
