# Generated by Django 6.0.6 on 2026-06-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_integrationapikey_monthly_quota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=12)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='copilot_mes_user_id_224ea0_idx')],
            },
        ),
    ]
