# Generated by Django 6.0.6 on 2026-06-17 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_copilotmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='copilotmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.copilotconversation'),
        ),
        migrations.AddIndex(
            model_name='copilotmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='copilot_mes_convers_985402_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotconversation',
            index=models.Index(fields=['user', '-updated_at'], name='copilot_con_user_id_486b1f_idx'),
        ),
    ]
