# Generated by Django 6.0.6 on 2026-06-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_copilotconversation_copilotmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='xero_last_invoice_sync',
            field=models.DateTimeField(blank=True, help_text='Last time invoices were pushed to Xero', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='xero_last_payment_sync',
            field=models.DateTimeField(blank=True, help_text='Last time payments were pulled from Xero', null=True),
        ),
    ]
