# Generated by Django 6.0.6 on 2026-06-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_company_xero_last_invoice_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, help_text='When the last payment reminder was sent (collections/dunning)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.IntegerField(default=0, help_text='How many payment reminders have been sent for this invoice'),
        ),
    ]
