# Generated by Django 5.2.15 on 2026-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_invoice_last_reminder_at_invoice_reminder_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryTransitRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=3, unique=True)),
                ("country_name", models.CharField(max_length=100)),
                (
                    "weighbridge_fee_zar",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-trip weighbridge fee in ZAR",
                        max_digits=8,
                    ),
                ),
                (
                    "toll_rate_per_km",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Average toll cost per km in ZAR",
                        max_digits=6,
                    ),
                ),
                (
                    "sa_border_distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Approximate km from Johannesburg to SA border post for this country",
                        max_digits=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "country_transit_rates",
                "ordering": ["country_code"],
            },
        ),
        migrations.CreateModel(
            name="BorderCrossingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_country",
                    models.CharField(
                        help_text="ISO-2/3 country code e.g. SA", max_length=3
                    ),
                ),
                ("to_country", models.CharField(max_length=3)),
                (
                    "fee_zar",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="One-way border crossing fee in ZAR",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g. includes COMESA transit docs",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "border_crossing_fees",
                "ordering": ["from_country", "to_country"],
                "unique_together": {("from_country", "to_country")},
            },
        ),
    ]
