# Generated by Django 6.0.6 on 2026-06-22 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_invoice_last_reminder_at_invoice_reminder_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Natural-language document that was embedded')),
                ('embedding', models.TextField(help_text='JSON-encoded list[float] embedding vector')),
                ('source_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_embeddings', to='core.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_embedding', to='core.invoice')),
            ],
            options={
                'db_table': 'rag_invoice_embeddings',
                'indexes': [models.Index(fields=['company'], name='rag_invoice_company_373b54_idx')],
            },
        ),
    ]
