# Generated by Django 5.2.15 on 2026-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_bordercrossingfee_countrytransitrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="allow_cross_border",
            field=models.BooleanField(
                default=True,
                help_text="Whether cross-border routes are enabled for this company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_base_rate_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Default base rate per km used when creating a new quote (ZAR)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_quote_validity_days",
            field=models.IntegerField(
                default=7, help_text="Default number of days a quote remains valid"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_sla_hours",
            field=models.IntegerField(
                default=48, help_text="Default SLA delivery time in hours"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="weight_surcharge_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Weight surcharge percentage applied to base cost when threshold is exceeded",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="weight_surcharge_threshold_kg",
            field=models.IntegerField(
                default=5000,
                help_text="Cargo weight above which a surcharge is applied (kg)",
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="fuel_consumption_l_per_100km",
            field=models.DecimalField(
                decimal_places=2,
                default=36.0,
                help_text="Diesel consumption in litres per 100km (e.g. 32 for Flatbed)",
                max_digits=5,
            ),
        ),
    ]
