# Generated by Django 5.2.15 on 2026-06-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_vehicle_type_fuel_company_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_toll_rate_per_km",
            field=models.DecimalField(
                decimal_places=3,
                default=0.5,
                help_text="Fallback toll cost in ZAR/km used when TomTom returns no toll data (default: R0.50/km)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="margin_at_risk_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Margin % below which a quote is flagged AT RISK (default: 5%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="margin_caution_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                help_text="Margin % below which a quote is flagged CAUTION (default: 12%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="margin_target_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Target margin % used in price-increase suggestions (default: 10%)",
                max_digits=5,
            ),
        ),
    ]
