# Generated by Django 5.2.15 on 2026-06-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_company_guard_thresholds_toll_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="core.driver",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="core.vehicle",
            ),
        ),
    ]
