# Generated by Django 5.2.15 on 2026-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_quote_vehicle_driver_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="avg_revenue_per_trip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="driver",
            name="efficiency_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driver",
            name="margin_per_trip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="driver",
            name="on_time_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="driver",
            name="revenue_generated",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="driver",
            name="safety_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driver",
            name="total_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="driver",
            name="trips_this_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="load",
            name="actual_delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when load was marked DELIVERED",
                null=True,
            ),
        ),
    ]
