# Generated by Django 5.2.15 on 2026-06-24 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_driver_computed_scores_load_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityevent",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_events",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="activityevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
