# Generated by Django 5.2.15 on 2026-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_quote_coords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="delivery_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="delivery_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="pickup_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="pickup_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
    ]
