# Generated by Django 5.2.15 on 2026-06-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_quote_coords_max_digits"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationapikey",
            name="allowed_ips",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated list of allowed caller IPs. Empty = all IPs permitted.",
            ),
        ),
        migrations.AddField(
            model_name="integrationapikey",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="If set, POST the scoring result to this URL after every successful score.",
            ),
        ),
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scored_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("risk_tier", models.CharField(blank=True, default="", max_length=20)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("eligible", models.BooleanField(blank=True, null=True)),
                ("caller_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="core.integrationapikey",
                    ),
                ),
            ],
            options={
                "db_table": "api_call_logs",
                "ordering": ["-scored_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "scored_at"],
                        name="api_call_lo_api_key_7b0aa7_idx",
                    )
                ],
            },
        ),
    ]
