# Generated by Django 5.2.15 on 2026-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_invoice_view_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="return_base_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_cargo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_location",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="quote",
            name="return_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="trip_type",
            field=models.CharField(
                choices=[("ONE_WAY", "One Way"), ("ROUND_TRIP", "Round Trip")],
                default="ONE_WAY",
                max_length=20,
            ),
        ),
    ]
