# Generated by Django 6.0.6 on 2026-06-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_invoiceembedding'),
        ('core', '0058_invoice_view_token'),
    ]

    operations = [
    ]
