# Generated by Django 6.0.6 on 2026-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_merge_0048_invoiceembedding_0058_invoice_view_token'),
        ('core', '0059_quote_round_trip_fields'),
    ]

    operations = [
    ]
