# Generated by Django 6.0.6 on 2026-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20260629_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Travel time of the chosen TomTom route at quote creation (minutes)', null=True),
        ),
    ]
