# Generated by Django 5.2.15 on 2026-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_quote_estimated_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tollplaza",
            name="route",
            field=models.CharField(
                choices=[
                    ("N1", "N1 — Cape Town to Johannesburg / Polokwane"),
                    ("N2", "N2 — Cape Town to Durban (coastal)"),
                    ("N3", "N3 — Johannesburg to Durban"),
                    ("N4", "N4 — Pretoria to Maputo"),
                    ("N14", "N14 — Johannesburg to Springbok"),
                    ("N17", "N17 — Johannesburg to Ermelo / Swaziland"),
                    ("R30", "R30/R730/R34 — Bloemfontein region"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
