# Generated by Django 6.0.6 on 2026-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_user_security_settings_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='known_devices',
            field=models.JSONField(default=list),
        ),
    ]
