# Generated by Django 6.0.6 on 2026-07-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_update_toll_plaza_routes'),
        ('core', '0063_user_known_devices'),
    ]

    operations = [
    ]
