# Generated by Django 6.0.6 on 2026-07-02 05:32

from django.core.management import call_command
from django.db import migrations


def create_cache_table(apps, schema_editor):
    """Create the Postgres table backing DatabaseCache (see settings.CACHES).

    Idempotent: createcachetable skips the table if it already exists, so this
    is safe to run on every deploy / fresh database.
    """
    call_command('createcachetable', 'tw_cache_table')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_20260701_1231'),
    ]

    operations = [
        migrations.RunPython(create_cache_table, migrations.RunPython.noop),
    ]
