# Generated by Django 6.0.6 on 2026-07-08 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_tollplaza_geofence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilotmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CopilotProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=40)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('display', models.JSONField(default=list)),
                ('warning', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_proposals', to='core.company')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.copilotconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='copilot_pro_user_id_f9467d_idx'), models.Index(fields=['conversation', 'status'], name='copilot_pro_convers_52f917_idx')],
            },
        ),
    ]
