# Generated by Django 5.2.15 on 2026-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_tollplaza_geofence_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Estimated delivery date", null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="pickup_date",
            field=models.DateField(
                blank=True, help_text="Estimated collection date", null=True
            ),
        ),
    ]
