# Generated by Django 6.0.6 on 2026-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_copilotmessage_metadata_copilotproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilotproposal',
            name='analysis_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('DENY', 'Deny'), ('DISBURSE', 'Disburse'), ('SETTLE', 'Settle'), ('CANCEL', 'Cancel'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('EMAIL', 'Email'), ('OTHER', 'Other')], db_index=True, help_text='Type of action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='copilotproposal',
            name='operation',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SEND', 'Send')], max_length=10),
        ),
    ]
