# Generated by Django 5.2.15 on 2026-07-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_quote_delivery_date_quote_pickup_date"),
        ("core", "0068_copilotproposal_analysis_summary_and_more"),
    ]

    operations = []
