# Generated by Django 6.0.6 on 2026-07-13 09:10

import django.db.models.deletion
from django.db import migrations, models


def dedupe_and_backfill(apps, schema_editor):
    """Keep only the newest outcome per quote (the unique constraint below
    requires one row per quote) and backfill the new company FK from the quote."""
    QuoteOutcome = apps.get_model('core', 'QuoteOutcome')

    seen = set()
    duplicate_ids = []
    for row in QuoteOutcome.objects.order_by('quote_id', '-created_at', '-id') \
                                   .values_list('id', 'quote_id'):
        oid, qid = row
        if qid in seen:
            duplicate_ids.append(oid)
        else:
            seen.add(qid)
    if duplicate_ids:
        QuoteOutcome.objects.filter(id__in=duplicate_ids).delete()

    for outcome in QuoteOutcome.objects.select_related('quote').filter(company__isnull=True):
        if outcome.quote and outcome.quote.company_id:
            outcome.company_id = outcome.quote.company_id
            outcome.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_merge_20260710_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoutcome',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_outcomes', to='core.company'),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='days_until_departure',
            field=models.IntegerField(blank=True, help_text='Days between quote creation and pickup date', null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='historical_acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Customer's acceptance rate before this outcome", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='market_rate_at_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lane market rate when the outcome was recorded', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='market_rate_source',
            field=models.CharField(blank=True, help_text='Provenance of market_rate_at_outcome (platform/company/estimate/...)', max_length=20),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='price_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='final_price / market_rate_at_outcome', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='quote_dow',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weekday the quote was created (0=Mon)', null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='quote_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month the quote was created (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(dedupe_and_backfill, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='quoteoutcome',
            constraint=models.UniqueConstraint(fields=('quote',), name='unique_outcome_per_quote'),
        ),
    ]
