# Generated by Django 6.0.6 on 2026-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_quoteoutcome_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoutcome',
            name='route_popularity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Normalized 90-day lane volume at outcome time', max_digits=5, null=True),
        ),
    ]
