# Generated by Django 6.0.6 on 2026-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_merge_toll_plazas_and_quote_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cartrack_base_url',
            field=models.CharField(blank=True, help_text='Regional Cartrack Fleet API base URL, e.g. https://fleetapi-za.cartrack.com', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_last_alert_sync',
            field=models.DateTimeField(blank=True, help_text='Watermark for GET /alerts/notifications polling', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_last_status_sync',
            field=models.DateTimeField(blank=True, help_text='Last time vehicle status/location was polled from Cartrack', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_password',
            field=models.TextField(blank=True, help_text='Cartrack Fleet API password (encrypted at rest)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_username',
            field=models.CharField(blank=True, help_text='Cartrack Fleet API username (Fleetweb > Settings > API Settings)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_webhook_secret',
            field=models.TextField(blank=True, help_text='HMAC key used to verify X-Webhook-Signature on inbound Cartrack webhooks (encrypted at rest)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cartrack_webhook_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique per-company token used in the inbound Cartrack webhook URL', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cartrack_registration',
            field=models.CharField(blank=True, help_text='Registration string Cartrack identifies this vehicle by, if it differs from plate', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='heading',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Compass heading in degrees (0-360)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ignition_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last Cartrack location reading', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
