# Generated by Django 6.0.6 on 2026-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_cartrack_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cartrack_current_driver_ref',
            field=models.CharField(blank=True, help_text='Raw driver/tag identifier Cartrack reports as currently in this vehicle. Informational only — does not affect the authoritative `driver` field.', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='door_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_door_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='temp1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='temp2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='temp3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='temp4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
