# Generated by Django 6.0.6 on 2026-07-16 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_cartrack_extended_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotUserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_memories', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_user_memory',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
