# Generated by Django 6.0.6 on 2026-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('IT', 'In-Transit'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=50),
        ),
    ]
