# Generated by Django 6.0.6 on 2026-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_quote_expired_vehicle_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('pro_50', 'Fleet 1-50'), ('pro_100', 'Fleet 51-100'), ('pro_150', 'Fleet 101-150')], default='free', max_length=20),
        ),
    ]
