# Generated by Django 5.2.16 on 2026-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_company_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_training_started_at',
            field=models.DateTimeField(blank=True, help_text='Outcomes recorded before this timestamp are excluded from win-model training/progress for this company', null=True),
        ),
    ]
