# Generated by Django 5.2.16 on 2026-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_company_ai_training_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('pro_50', 'TruckWys Fleet'), ('pro_100', 'Fleet 51-100 (legacy)'), ('pro_150', 'Fleet 101-150 (legacy)')], default='free', max_length=20),
        ),
    ]
