# Generated by Django 5.2.16 on 2026-07-27 11:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_company_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='take_rate_frozen',
            field=models.BooleanField(default=False, help_text='True when delivery take-rate charges failed past the grace period — blocks new bookings/quotes'),
        ),
        migrations.AddField(
            model_name='company',
            name='take_rate_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryFeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_pct', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Invoice total_amount the rate was applied to', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='base_amount * rate_pct / 100', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('payfast_response', models.JSONField(blank=True, default=dict, help_text='Raw response from the last charge_adhoc call')),
                ('attempt_count', models.IntegerField(default=0)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('first_failed_at', models.DateTimeField(blank=True, null=True)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fee_charges', to='core.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fee_charge', to='core.invoice')),
            ],
            options={
                'db_table': 'delivery_fee_charges',
                'ordering': ['-created_at'],
            },
        ),
    ]
