# Generated by Django 5.2.16 on 2026-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_company_take_rate_frozen_company_take_rate_frozen_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtransaction',
            name='payfast_payment_id',
        ),
        migrations.RemoveField(
            model_name='billingtransaction',
            name='raw_itn_data',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payfast_token',
        ),
        migrations.RemoveField(
            model_name='deliveryfeecharge',
            name='payfast_response',
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text="Paystack's own transaction id (data.id) from the verified charge", max_length=200),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='raw_gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full verify/webhook payload for audit trail'),
        ),
        migrations.AddField(
            model_name='company',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Next date the flat monthly fee is due; advanced by core.services.subscription_billing', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, help_text="Reusable Paystack authorization_code for this company's card on file", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_authorization_email',
            field=models.EmailField(blank=True, help_text='Email the authorization was created with — Paystack requires an exact match on every charge', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_card_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryfeecharge',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from the last charge_authorization call'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=200),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='payment_status',
            field=models.CharField(blank=True, help_text="Raw status from Paystack's verify/webhook response", max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'TruckWys Fleet'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
