# Generated by Django 5.2.16 on 2026-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_billingtransaction_payfast_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password_hash', models.CharField(help_text='Already hashed (make_password) — never plaintext', max_length=255)),
                ('company_name', models.CharField(max_length=200)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_signups',
            },
        ),
    ]
