# Generated by Django 5.2.16 on 2026-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_pendingsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_lapsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='take_rate_frozen',
            field=models.BooleanField(default=False, help_text='True when billing has failed/lapsed past the grace period — blocks new bookings/quotes'),
        ),
        migrations.AlterField(
            model_name='deliveryfeecharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('accrued', 'Accrued — owed, not charged')], default='pending', max_length=20),
        ),
    ]
