# Generated by Django 5.2.16 on 2026-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_billing_state_machine_spec_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='payment_failed_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
