# Generated by Django 5.2.16 on 2026-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_pendingsignup_payment_failed_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_billing_at',
            field=models.DateTimeField(blank=True, help_text='Display-only timestamp version of next_billing_date, for a live countdown on the billing page.', null=True),
        ),
    ]
