# Generated by Django 6.0.6 on 2026-07-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_fcm_device'),
        ('core', '0087_pendingsignup_payment_failed_notified_at'),
    ]

    operations = [
    ]
