# Generated by Django 6.0.6 on 2026-07-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_company_next_billing_at'),
        ('core', '0088_merge_20260730_0755'),
    ]

    operations = [
    ]
