# Generated by Django 6.0.6 on 2026-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_merge_20260730_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_card_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
