# Generated by Django 6.0.6 on 2026-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_merge_20260730_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
