# Generated by Django 6.0.6 on 2026-08-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_company_onboarding_completed_at'),
        ('core', '0090_notification_document_alert_fields'),
    ]

    operations = [
    ]
