# Generated by Django 6.0.6 on 2026-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_remove_vehicletype_fuel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text="Explicit cancellation was requested while still active/grace_period — access and billing keep running until next_billing_date, at which point the daily check_pending_cancellations sweep finalises subscription_status to 'cancelled'. Left False once actually cancelled (a hard, immediate cancel from 'trialing' never sets this at all)."),
        ),
    ]
