# Generated by Django 6.0.6 on 2026-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_company_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fuel_price_electric',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default Electric price per kWh in ZAR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_price_hybrid',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default Hybrid price per litre in ZAR', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_price_per_litre',
            field=models.DecimalField(decimal_places=4, default=23.5, help_text='Default Diesel price per litre in ZAR (default: R23.50)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_price_petrol',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default Petrol price per litre in ZAR', max_digits=8, null=True),
        ),
    ]
