# Generated by Django 6.0.6 on 2026-08-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_widen_company_fuel_price_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=500)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_search_history', to='core.company')),
            ],
            options={
                'db_table': 'location_search_history',
                'ordering': ['-use_count', '-last_used_at'],
                'indexes': [models.Index(fields=['company', '-use_count', '-last_used_at'], name='location_se_company_b38eaa_idx')],
                'unique_together': {('company', 'location_text')},
            },
        ),
    ]
