# Generated by Django 6.0.6 on 2026-08-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_ctrlfleet_integration_fields'),
        ('core', '0098_location_search_history'),
    ]

    operations = [
    ]
