# Generated by Django 6.0.6 on 2026-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_merge_20260827_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='stops',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
