# Generated by Django 6.0.6 on 2026-09-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_quote_load_stops_and_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='route_geometry',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='route_geometry',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
