# Generated by Django 6.0.6 on 2026-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_quote_load_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='fuel_consumption_sensitivity_pct',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Extra fuel burned per tonne over the reference capacity, as a percent (e.g. 2.0 = +2%/tonne). Reference tonnage is this type\'s own "capacity" field.', max_digits=4),
        ),
    ]
