# Generated by Django 6.0.6 on 2026-09-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_vehicletype_fuel_consumption_sensitivity_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='weight_surcharge_pct',
        ),
        migrations.RemoveField(
            model_name='company',
            name='weight_surcharge_threshold_kg',
        ),
    ]
