# Generated by Django 6.0.6 on 2026-09-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_remove_company_weight_surcharge_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demo_quota_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
