# Generated by Django 6.0.6 on 2026-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_company_demo_quota_used_company_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demo_last_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
