# Generated by Django 6.0.6 on 2026-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_company_deleted_at_company_is_deleted_taskrunlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='demo_quote_used',
            field=models.BooleanField(default=False),
        ),
    ]
