# Generated by Django 6.0.6 on 2026-09-09 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_user_session_demo_quote_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_optimizer_max_market_deviation_pct',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Maximum % above market rate the AI optimizer will recommend pricing (default: 35%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_optimizer_min_margin_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Hard floor markup % over cost the AI optimizer will never recommend below (default: 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_optimizer_min_win_probability_pct',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Minimum acceptable win probability % for an AI-recommended price (default: 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Quoting user at outcome time — the per-user ML training key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_outcomes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='feature_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MLUserRetrainQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_queued', models.BooleanField(default=False)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('last_retrain_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_retrain_finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_retrain_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_user_retrain_queue',
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Per-User'), ('global', 'Global')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='candidate', max_length=12)),
                ('algorithm', models.CharField(blank=True, help_text='e.g. logistic_regression, gradient_boosting, lightgbm', max_length=50)),
                ('feature_version', models.CharField(blank=True, max_length=20)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, help_text='e.g. user:123:v7, global:v42', max_length=40)),
                ('training_sample_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('training_period_start', models.DateTimeField(blank=True, null=True)),
                ('training_period_end', models.DateTimeField(blank=True, null=True)),
                ('evaluation_metrics', models.JSONField(blank=True, default=dict)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_model_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'user', 'status'], name='ml_model_ve_scope_405c92_idx'), models.Index(fields=['scope', 'status', '-created_at'], name='ml_model_ve_scope_8b7be7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('scope', 'user'), name='unique_active_model_per_user')],
            },
        ),
    ]
