# Generated by Django 6.0.6 on 2026-09-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_backfill_quoteoutcome_created_by'),
        ('core', '0110_fix_zw_border_fee'),
    ]

    operations = [
    ]
