# Generated by Django 6.0.6 on 2026-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_fix_na_sz_border_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cross_border_crossings_per_year',
            field=models.PositiveIntegerField(default=24, help_text='How many border crossings this fleet makes a year (each leg counts separately). Used to spread the annual C-BRTA permit across crossings.'),
        ),
    ]
