# Generated by Django 6.0.6 on 2026-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_split_sa_permit_out_of_border_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytransitrate',
            name='toll_flat_zar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed one-way toll for the whole country, in ZAR. When above zero this is used instead of toll_rate_per_km — for corridors whose tolls are gate-based, not distance-based.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='countrytransitrate',
            name='toll_rate_per_km',
            field=models.DecimalField(decimal_places=3, help_text='Average toll cost per km in ZAR. Ignored when toll_flat_zar is set.', max_digits=6),
        ),
    ]
