# Generated by Django 6.0.6 on 2026-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_mozambique_flat_toll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordercrossingfee',
            options={'ordering': ['from_country', 'to_country', 'min_weight_kg']},
        ),
        migrations.AlterUniqueTogether(
            name='bordercrossingfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bordercrossingfee',
            name='max_weight_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Highest load weight this row applies to, in kg (inclusive). Blank means no upper limit.', null=True),
        ),
        migrations.AddField(
            model_name='bordercrossingfee',
            name='min_weight_kg',
            field=models.PositiveIntegerField(default=0, help_text='Lowest load weight this row applies to, in kg (inclusive).'),
        ),
        migrations.AlterUniqueTogether(
            name='bordercrossingfee',
            unique_together={('from_country', 'to_country', 'min_weight_kg')},
        ),
    ]
