# Generated by Django 6.0.6 on 2026-09-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_band_border_fees_by_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fuel_zone',
            field=models.CharField(choices=[('INLAND', 'Inland'), ('COASTAL', 'Coastal')], default='INLAND', help_text='Which gazetted diesel price applies to this fleet. COASTAL for Cape Town, Durban, Gqeberha and East London; INLAND for Gauteng and the interior.', max_length=10),
        ),
    ]
