# Generated by Django 6.0.6 on 2026-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_add_company_fuel_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides this vehicle type's rate per km for this truck.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_l_per_100km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides this vehicle type's consumption for this truck.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gvm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross vehicle mass in tonnes — the truck plus its maximum load.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uniq_customer_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'plate'), name='uniq_vehicle_plate_per_company'),
        ),
    ]
