# Generated by Django 6.0.6 on 2026-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_quote_base_rate_per_km_quote_route_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquotepriceanalysis',
            name='failed_at_call',
            field=models.CharField(blank=True, choices=[('research', 'Research call (web_search)'), ('structuring', 'Structuring call'), ('pricing', 'Pricing / win scoring (after both calls)')], max_length=12),
        ),
    ]
