# Generated by Django 6.0.6 on 2026-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_customer_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_default',
            field=models.CharField(choices=[('NET7', 'Net 7 Days'), ('NET14', 'Net 14 Days'), ('NET30', 'Net 30 Days'), ('NET45', 'Net 45 Days'), ('NET60', 'Net 60 Days'), ('NET90', 'Net 90 Days')], default='NET30', help_text='Default payment terms for this customer', max_length=20),
        ),
    ]
