# Generated by Django 6.0.6 on 2026-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_customer_contact_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('CHEQUE', 'Cheque / current'), ('SAVINGS', 'Savings'), ('TRANSMISSION', 'Transmission')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_reference_hint',
            field=models.CharField(blank=True, help_text='Optional wording shown to customers about the payment reference to use; defaults to "use the invoice number as your payment reference".', max_length=200, null=True),
        ),
    ]
