# Generated by Django 6.0.6 on 2026-09-28 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_company_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelprice',
            name='diesel_500ppm_coastal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Diesel 500ppm (0.05% S) coastal wholesale list price (ZAR/litre), when known', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='diesel_500ppm_inland',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Diesel 500ppm (0.05% S) inland wholesale list price (ZAR/litre), when known', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='diesel_grade',
            field=models.CharField(blank=True, choices=[('50ppm', 'Diesel 50ppm (0.005% S)'), ('500ppm', 'Diesel 500ppm (0.05% S)')], help_text='Grade of diesel_inland/diesel_coastal. NULL = not recorded (legacy rows, fallback table, manual entry, regex scrapers).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='When the stored price took effect (SA adjustments: first Wednesday of the month, 00:01 SAST). NULL on legacy/fallback rows.', null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='fetch_failed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the most recent refresh failed and the stored price was kept rather than overwritten; cleared by the next successful refresh.', null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(help_text='Calendar month this row belongs to (always the 1st). The moment the stored price took effect is effective_from.', unique=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='diesel_coastal',
            field=models.DecimalField(decimal_places=4, help_text='Diesel coastal wholesale list price (ZAR/litre); grade in diesel_grade', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='diesel_inland',
            field=models.DecimalField(decimal_places=4, help_text='Diesel inland (Gauteng) wholesale list price (ZAR/litre); grade in diesel_grade', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the stored price was last confirmed by a check that succeeded (or, for fallback rows, last attempted)'),
        ),
    ]
