# Generated by Django 6.0.6 on 2026-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_vehicletype_sanral_toll_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('DISPATCHER', 'Dispatcher'), ('VIEWER', 'Viewer'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner')], default='VIEWER', max_length=20),
        ),
    ]
