# Generated by Django 6.0.6 on 2026-09-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_ai_price_analysis_pricing_stage'),
        ('core', '0130_alter_user_role'),
    ]

    operations = [
    ]
