# Generated by Django 6.0.6 on 2026-09-22 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='base_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='route_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIQuotePriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('auto', 'Auto (first run)'), ('manual', 'Manual re-check')], default='auto', max_length=10)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('reasoning_effort', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('failed_at_call', models.CharField(blank=True, choices=[('research', 'Research call (web_search)'), ('structuring', 'Structuring call')], max_length=12)),
                ('research_input_tokens', models.PositiveIntegerField(default=0)),
                ('research_cached_tokens', models.PositiveIntegerField(default=0)),
                ('research_output_tokens', models.PositiveIntegerField(default=0)),
                ('research_reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('research_web_search_calls', models.PositiveIntegerField(default=0)),
                ('structuring_input_tokens', models.PositiveIntegerField(default=0)),
                ('structuring_cached_tokens', models.PositiveIntegerField(default=0)),
                ('structuring_output_tokens', models.PositiveIntegerField(default=0)),
                ('structuring_reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('token_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('web_search_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('suggested_price_zar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=20)),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('request_context', models.JSONField(blank=True, default=dict)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_price_analyses', to='core.company')),
                ('quote', models.ForeignKey(blank=True, help_text='Null when run against an unsaved draft quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_price_analyses', to='core.quote')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_price_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_quote_price_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='ai_quote_pr_company_f2b330_idx'), models.Index(fields=['triggered_by', '-created_at'], name='ai_quote_pr_trigger_0ae75e_idx'), models.Index(fields=['quote', '-created_at'], name='ai_quote_pr_quote_i_6ff760_idx')],
            },
        ),
    ]
