# Generated by Django 6.0.6 on 2026-09-30 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_ai_price_analysis_pricing_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollplaza',
            name='tariff_effective_from',
            field=models.DateField(blank=True, help_text='Date the stored tariff schedule took effect (SANRAL changes it every 1 March)', null=True),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='tariff_source_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='tariff_source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='tariff_verified_at',
            field=models.DateField(blank=True, help_text='Date the stored tariffs were last confirmed on their source', null=True),
        ),
        migrations.AlterField(
            model_name='aiquotepriceanalysis',
            name='trigger_type',
            field=models.CharField(choices=[('auto', 'Auto (first run)'), ('manual', 'Manual re-check'), ('check', 'Price check (stored figures)'), ('refresh', 'Verified-rate refresh (web search)')], default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='VerifiedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('toll_tariff', 'SANRAL toll tariff'), ('driver_allowance', 'Driver allowance')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('sanral_class', models.PositiveSmallIntegerField(blank=True, help_text='SANRAL class 1-4 (toll tariffs only)', null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('per_passage', 'Rand per passage (one way)'), ('per_night', 'Rand per night away')], max_length=20)),
                ('effective_from', models.DateField()),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_name', models.CharField(blank=True, default='', max_length=300)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=12)),
                ('proposed_by', models.CharField(blank=True, default='', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refresh_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rate_proposals', to='core.aiquotepriceanalysis')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toll_plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_rates', to='core.tollplaza')),
            ],
            options={
                'db_table': 'verified_rates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'key', 'status'], name='verified_ra_kind_9c4428_idx'), models.Index(fields=['status', '-created_at'], name='verified_ra_status_3ac0fe_idx')],
            },
        ),
    ]
