# Generated by Django 6.0.6 on 2026-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_seed_toll_tariff_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_email_invoices',
            field=models.BooleanField(default=False, help_text='Email the invoice to the customer as soon as a load is delivered'),
        ),
    ]
