# Generated by Django 6.0.6 on 2026-10-01 15:40

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Foundation schema: typed invoice lines, credit notes, per-company
    numbering, suppliers, debtor identity, payment source/external id,
    expense VAT. Additive only (new tables, nullable/defaulted columns),
    plus invoice_number uniqueness moving from global to per company."""

    dependencies = [
        ('core', '0135_company_auto_email_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(db_index=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('VOID', 'Void')], db_index=True, default='ISSUED', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered in TruckWys'), ('XERO', 'Xero'), ('QBO', 'QuickBooks Online')], default='MANUAL', max_length=10)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_notes',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('tax_code', models.CharField(choices=[('STANDARD', 'Standard rate (15%)'), ('ZERO_RATED', 'Zero-rated (0%)'), ('EXEMPT', 'Exempt'), ('NO_VAT', 'No VAT (not a VAT vendor)')], default='STANDARD', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'credit_note_lines',
                'ordering': ['credit_note_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DebtorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('legal_name_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('country', models.CharField(default='ZA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Debtor identities',
                'db_table': 'debtor_identities',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note')], max_length=20)),
                ('prefix', models.CharField(default='INV-', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_sequences',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_code', models.CharField(choices=[('STANDARD', 'Standard rate (15%)'), ('ZERO_RATED', 'Zero-rated (0%)'), ('EXEMPT', 'Exempt'), ('NO_VAT', 'No VAT (not a VAT vendor)')], default='STANDARD', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['invoice_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('vat_number', models.CharField(blank=True, default='', max_length=20)),
                ('registration_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='MANUAL', max_length=10)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='vat_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='ZA', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_name_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.load'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_code',
            field=models.CharField(choices=[('STANDARD', 'Standard rate (15%)'), ('ZERO_RATED', 'Zero-rated (0%)'), ('EXEMPT', 'Exempt'), ('NO_VAT', 'No VAT (not a VAT vendor)')], default='NO_VAT', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of issued credit notes against this invoice (incl. VAT)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Days from issue date to due date, from the payment terms'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totals_source',
            # Existing rows are LEGACY (their stored totals are what was
            # issued); the default then flips to LINES for new invoices.
            field=models.CharField(choices=[('LINES', 'Calculated from lines'), ('LEGACY', 'Legacy stored totals')], default='LEGACY', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totals_source',
            field=models.CharField(choices=[('LINES', 'Calculated from lines'), ('LEGACY', 'Legacy stored totals')], default='LINES', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Entered in TruckWys'), ('XERO', 'Xero'), ('QBO', 'QuickBooks Online'), ('BANK', 'Bank feed')], db_index=True, default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLLS', 'Tolls'), ('MAINTENANCE', 'Maintenance'), ('DRIVER_COST', 'Driver Cost'), ('SUBCONTRACTOR', 'Subcontractor'), ('INSURANCE', 'Insurance'), ('OVERHEAD', 'Overhead'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Deprecated mirror of InvoiceLine rows'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('NET7', 'Net 7 Days'), ('NET14', 'Net 14 Days'), ('NET30', 'Net 30 Days'), ('NET45', 'Net 45 Days'), ('NET60', 'Net 60 Days'), ('NET90', 'Net 90 Days')], default='NET30', help_text='Payment terms for this invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Void'), ('DISPUTED', 'Disputed'), ('CREDITED', 'Credited')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_invoice_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'source', 'external_id'), name='uniq_payment_external_id'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.company'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.customer'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.creditnote'),
        ),
        migrations.AddField(
            model_name='customer',
            name='debtor_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='core.company'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.load'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_lines', to='core.invoiceline'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.supplier'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['company', 'issue_date'], name='credit_note_company_bc89c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('company', 'credit_note_number'), name='uniq_credit_note_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'source', 'external_id'), name='uniq_credit_note_external_id'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('company', 'doc_type'), name='uniq_document_sequence'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'name_key'), name='uniq_supplier_name_per_company'),
        ),
    ]
