# Generated by Django 6.0.6 on 2026-10-01 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_capital_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('XERO', 'Xero'), ('QBO', 'QuickBooks Online')], max_length=10)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=40)),
                ('resource_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(blank=True, default='', max_length=40)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounting_webhook_events',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='revenue_type',
            field=models.CharField(choices=[('FREIGHT', 'Freight'), ('FUEL_SURCHARGE', 'Fuel surcharge'), ('TOLLS', 'Tolls recharged'), ('EXTRA_KM', 'Extra km'), ('WAITING_TIME', 'Waiting time'), ('OTHER', 'Other')], default='FREIGHT', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='revenue_type',
            field=models.CharField(choices=[('FREIGHT', 'Freight'), ('FUEL_SURCHARGE', 'Fuel surcharge'), ('TOLLS', 'Tolls recharged'), ('EXTRA_KM', 'Extra km'), ('WAITING_TIME', 'Waiting time'), ('OTHER', 'Other')], default='FREIGHT', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('XERO', 'Xero'), ('QBO', 'QuickBooks Online')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING_ORG', 'Choose organisation'), ('ACTIVE', 'Connected'), ('NEEDS_REAUTH', 'Reconnect required'), ('DISABLED', 'Disconnected')], db_index=True, default='PENDING_ORG', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('tenant_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=255)),
                ('provider_connection_id', models.CharField(blank=True, default='', max_length=100)),
                ('short_code', models.CharField(blank=True, default='', max_length=50)),
                ('base_currency', models.CharField(blank=True, default='', max_length=3)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('pending_tenants', models.JSONField(blank=True, default=list)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('backfill', models.JSONField(blank=True, default=dict)),
                ('cursors', models.JSONField(blank=True, default=dict)),
                ('last_payment_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_connections', to='core.company')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('action', models.CharField(max_length=40)),
                ('object_type', models.CharField(blank=True, default='', max_length=20)),
                ('local_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_events', to='core.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.accountingconnection')),
            ],
            options={
                'db_table': 'accounting_sync_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('XERO', 'Xero'), ('QBO', 'QuickBooks Online')], max_length=10)),
                ('object_type', models.CharField(choices=[('CONTACT_CUSTOMER', 'Customer contact'), ('CONTACT_SUPPLIER', 'Supplier contact'), ('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('BILL', 'Supplier bill'), ('PAYMENT', 'Payment'), ('OVERPAYMENT', 'Overpayment')], max_length=20)),
                ('local_id', models.PositiveBigIntegerField()),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('external_number', models.CharField(blank=True, default='', max_length=100)),
                ('external_version', models.CharField(blank=True, default='', max_length=50)),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SYNCED', 'Synced'), ('ERROR', 'Error'), ('DEAD', 'Dead'), ('BLOCKED', 'Blocked'), ('VOIDED', 'Voided'), ('SUGGESTED', 'Suggested'), ('UNMATCHED', 'Unmatched'), ('CREATE', 'Create'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=12)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requeue', models.BooleanField(default=False)),
                ('match_method', models.CharField(blank=True, default='', max_length=20)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='core.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.accountingconnection')),
            ],
            options={
                'db_table': 'accounting_external_links',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='OK', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('checked', models.JSONField(blank=True, default=dict)),
                ('difference_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='core.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='core.accountingconnection')),
            ],
            options={
                'db_table': 'accounting_reconciliation_runs',
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('field', models.CharField(max_length=40)),
                ('truckwys_value', models.CharField(blank=True, default='', max_length=60)),
                ('provider_value', models.CharField(blank=True, default='', max_length=60)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('local_url', models.CharField(blank=True, default='', max_length=255)),
                ('provider_url', models.CharField(blank=True, default='', max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='core.reconciliationrun')),
            ],
            options={
                'db_table': 'accounting_reconciliation_differences',
                'ordering': ['scope', 'key', 'field'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_ORG', 'ACTIVE', 'NEEDS_REAUTH'])), fields=('company',), name='uniq_live_accounting_connection_per_company'),
        ),
        migrations.AddConstraint(
            model_name='accountingconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'NEEDS_REAUTH']), models.Q(('tenant_id', ''), _negated=True)), fields=('provider', 'tenant_id'), name='uniq_live_accounting_tenant'),
        ),
        migrations.AddIndex(
            model_name='externallink',
            index=models.Index(fields=['company', 'object_type', 'local_id'], name='accounting__company_13edf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(fields=('connection', 'object_type', 'local_id'), name='uniq_external_link_local'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('connection', 'object_type', 'external_id'), name='uniq_external_link_remote'),
        ),
    ]
