# Generated by Django 6.0.6 on 2026-10-01 16:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_capital_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('risk_index', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('band', models.CharField(blank=True, default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'capital_book_snapshots',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='CapitalAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('EXTRACT', 'Document field extraction'), ('EXPLAIN', 'Decision explanation')], max_length=8)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'capital_ai_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LIMIT', 'Limit near or at cap'), ('CONCENTRATION', 'Concentration'), ('RISK_INDEX', 'Book risk index'), ('OVERDUE', 'Funded invoice overdue'), ('DEBTOR_WARNING', 'Debtor early warning'), ('TRANSPORTER_WARNING', 'Transporter early warning'), ('RECONCILIATION', 'Ledger reconciliation'), ('QUEUE', 'Queue'), ('SETTLEMENT', 'Paid invoice awaiting settlement')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('AMBER', 'Amber'), ('RED', 'Red')], default='AMBER', max_length=5)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_alerts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved by the funder'), ('REJECTED', 'Not approved')], default='NOT_STARTED', max_length=12)),
                ('juristic_person', models.BooleanField(default=False, help_text='A company or close corporation, not a sole proprietor')),
                ('declared_annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('turnover_evidenced', models.BooleanField(default=False)),
                ('git_insurer', models.CharField(blank=True, default='', max_length=200)),
                ('git_insurance_expiry', models.DateField(blank=True, null=True)),
                ('tax_compliance_verified', models.BooleanField(default=False)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('consents', models.JSONField(blank=True, default=list)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capital_applications',
            },
        ),
        migrations.CreateModel(
            name='CapitalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening'), ('RESERVE', 'Reserve'), ('CANCEL_RESERVE', 'Cancel Reserve'), ('DISBURSE', 'Disburse'), ('FEE', 'Fee'), ('COLLECTION', 'Collection'), ('RELEASE_HOLDBACK', 'Release Holdback'), ('DILUTION', 'Dilution'), ('BUYBACK', 'Buyback'), ('WRITE_OFF', 'Write Off'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserved_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Capital ledger entries',
                'db_table': 'capital_ledger_entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DEBTOR', 'Debtor'), ('TRANSPORTER', 'Transporter'), ('PAIR', 'Transporter-debtor pair'), ('SECTOR', 'Sector')], max_length=12)),
                ('sector', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hold', models.BooleanField(default=False, help_text='No new exposure in this scope')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_limits',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEBTOR', 'Debtor'), ('TRANSPORTER', 'Transporter')], db_index=True, max_length=12)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('points', models.IntegerField(help_text='Scorecard points 0-100 (higher = safer)')),
                ('pd_12m', models.DecimalField(decimal_places=5, help_text='12-month probability of default (0-1)', max_digits=7)),
                ('expected_dtp_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('hard_stop', models.BooleanField(default=False)),
                ('cold_start', models.BooleanField(default=False)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('inputs_hash', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'db_table': 'capital_scores',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_funder_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_credit_policies',
                'ordering': ['funder_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('files', models.JSONField(default=dict, help_text='{name: storage path}')),
                ('summary', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'capital_data_room_exports',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CIPC', 'CIPC'), ('BUREAU', 'Credit bureau'), ('LLM', 'LLM document extraction')], db_index=True, max_length=10)),
                ('adapter', models.CharField(help_text='fake | null | <vendor>', max_length=30)),
                ('available', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_fake', models.BooleanField(default=False)),
                ('cost_zar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'capital_external_checks',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name. Never shown to transporters.', max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('SANDBOX', 'Sandbox (not signed, no real money)'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused (no new advances)'), ('CLOSED', 'Closed')], db_index=True, default='SANDBOX', max_length=10)),
                ('pot_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Facility size (the pot) in ZAR', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_of_funds_pct', models.DecimalField(decimal_places=3, default=Decimal('13.500'), help_text='Annual cost of funds, % (assumption until signed)', max_digits=6)),
                ('operating_mode', models.CharField(choices=[('A', 'A: funder approves every advance'), ('B', 'B: auto-approve inside a funder-signed envelope')], default='A', max_length=1)),
                ('auto_approve_enabled', models.BooleanField(default=False)),
                ('staff_may_approve', models.BooleanField(default=False)),
                ('recourse', models.CharField(choices=[('TBD', 'To be decided by the owner and funder'), ('RECOURSE', 'With recourse'), ('NON_RECOURSE', 'Without recourse (debtor insolvency)')], default='TBD', max_length=15)),
                ('first_loss_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('insurance_cover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capital_funders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FunderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer (book, ledger, data room)'), ('APPROVER', 'Approver (also approves or declines advances and policy)')], default='VIEWER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'capital_funder_memberships',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('OFFER', 'Offer preview (no money reserved)'), ('REQUEST', 'Transporter request'), ('QUEUE', 'Queue re-evaluation'), ('LENDER', 'Funder API request')], default='OFFER', max_length=8)),
                ('decision', models.CharField(choices=[('FUND', 'Fund in full'), ('PART_FUND', 'Fund part now'), ('QUEUE', 'Queue until capacity frees'), ('REFER', 'Refer to a person'), ('DECLINE', 'Decline')], db_index=True, max_length=10)),
                ('eligible', models.BooleanField(default=False)),
                ('eligibility', models.JSONField(blank=True, default=list, help_text='[{rule, passed, code, text}]')),
                ('checks', models.JSONField(blank=True, default=dict, help_text='Duplicate / fraud / verification checks')),
                ('verification_tier', models.CharField(default='V0', max_length=2)),
                ('fraud_score', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=4)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('advance_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('eligible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='advance rate x balance, before headroom', max_digits=14)),
                ('fundable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What can be advanced now, after every limit', max_digits=14)),
                ('queued_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('binding_limit', models.CharField(blank=True, default='', max_length=30)),
                ('headroom', models.JSONField(blank=True, default=dict)),
                ('expected_dtp_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('pd_horizon', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=7)),
                ('el_pct', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Expected loss as % of the advance', max_digits=7)),
                ('invoice_grade', models.CharField(blank=True, default='', max_length=3)),
                ('fee_pct', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=6)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fee_vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fee_breakdown', models.JSONField(blank=True, default=dict)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('holdback_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('explanation_source', models.CharField(default='TEMPLATE', max_length=10)),
                ('policy_version', models.PositiveIntegerField(default=0)),
                ('model_version', models.CharField(default='', max_length=40)),
                ('content_hash', models.CharField(max_length=64)),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_invoice_assessments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='advancerequest',
            name='uniq_active_advance_per_invoice',
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='approver_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='debtor',
            field=models.ForeignKey(blank=True, help_text='Global debtor identity of the invoice customer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='disbursement_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='holdback_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='queue_priority',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='topup_pending',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='cession_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CLEARED', 'Cleared'), ('ACKNOWLEDGED', 'Acknowledgement on file'), ('PROHIBITED', 'Cession prohibited')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='cipc_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='cipc_status',
            field=models.CharField(choices=[('UNKNOWN', 'Not checked'), ('IN_BUSINESS', 'In business'), ('DEREGISTRATION', 'Deregistration process'), ('DEREGISTERED', 'Deregistered'), ('BUSINESS_RESCUE', 'Business rescue'), ('LIQUIDATION', 'Liquidation')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='is_government',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtoridentity',
            name='sector',
            field=models.CharField(choices=[('RETAIL_FMCG', 'Retail / FMCG'), ('MINING', 'Mining'), ('AGRI', 'Agriculture'), ('CONSTRUCTION', 'Construction'), ('MANUFACTURING', 'Manufacturing'), ('FUEL', 'Fuel'), ('LOGISTICS', 'Logistics'), ('GOVERNMENT', 'Government / SOE'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('QUEUED', 'Queued'), ('REQUESTED', 'Requested'), ('SCORING', 'Scoring'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('DISBURSED', 'Disbursed'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('BOUGHT_BACK', 'Bought back by the transporter'), ('WRITTEN_OFF', 'Written off')], db_index=True, default='ELIGIBLE', help_text='Current status of the advance request', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('DENY', 'Deny'), ('DISBURSE', 'Disburse'), ('SETTLE', 'Settle'), ('CANCEL', 'Cancel'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('EMAIL', 'Email'), ('DECIDE', 'Decision recorded'), ('OVERRIDE', 'Override'), ('OTHER', 'Other')], db_index=True, help_text='Type of action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='limit',
            field=models.DecimalField(decimal_places=2, help_text='Transporter line limit in ZAR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='capitalalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalapplication',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_application', to='core.company'),
        ),
        migrations.AddField(
            model_name='capitalapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.advancerequest'),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_ledger_entries', to='core.company'),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_ledger_entries', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.facility'),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_ledger_entries', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='capitallimit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_limits', to='core.company'),
        ),
        migrations.AddField(
            model_name='capitallimit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitallimit',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_limits', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='capitalscore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_scores', to='core.company'),
        ),
        migrations.AddField(
            model_name='capitalscore',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_scores', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='creditpolicy',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataroomexport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalcheck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_external_checks', to='core.company'),
        ),
        migrations.AddField(
            model_name='externalcheck',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_checks', to='core.debtoridentity'),
        ),
        migrations.AddConstraint(
            model_name='funder',
            constraint=models.CheckConstraint(condition=models.Q(('pot_limit__gte', 0)), name='funder_pot_non_negative'),
        ),
        migrations.AddField(
            model_name='dataroomexport',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_exports', to='core.funder'),
        ),
        migrations.AddField(
            model_name='creditpolicy',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.funder'),
        ),
        migrations.AddField(
            model_name='capitallimit',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='core.funder'),
        ),
        migrations.AddField(
            model_name='capitalledgerentry',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.funder'),
        ),
        migrations.AddField(
            model_name='capitalalert',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.funder'),
        ),
        migrations.AddField(
            model_name='booksnapshot',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.funder'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='funder',
            field=models.ForeignKey(blank=True, help_text='Funder whose pot this advance draws on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='core.funder'),
        ),
        migrations.AddField(
            model_name='facility',
            name='funder',
            field=models.ForeignKey(blank=True, help_text='Funder whose pot this transporter line draws on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.funder'),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='funder',
            field=models.ForeignKey(blank=True, help_text='Funder this LENDER key acts for (book, approvals, ledger, data room).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='core.funder'),
        ),
        migrations.AddField(
            model_name='fundermembership',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.funder'),
        ),
        migrations.AddField(
            model_name='fundermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_assessments', to='core.company'),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_assessments', to='core.debtoridentity'),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='debtor_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.capitalscore'),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.funder'),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_assessments', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceassessment',
            name='transporter_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.capitalscore'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='Decision record behind this advance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='core.invoiceassessment'),
        ),
        migrations.AddConstraint(
            model_name='advancerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'REQUESTED', 'SCORING', 'APPROVED', 'DISBURSED'])), fields=('invoice',), name='uniq_active_advance_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='capitalscore',
            index=models.Index(fields=['kind', 'debtor', '-created_at'], name='capital_sco_kind_ca5d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalscore',
            index=models.Index(fields=['kind', 'company', '-created_at'], name='capital_sco_kind_0fa537_idx'),
        ),
        migrations.AddConstraint(
            model_name='capitalscore',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('debtor__isnull', False), ('kind', 'DEBTOR')), models.Q(('company__isnull', False), ('debtor__isnull', True), ('kind', 'TRANSPORTER')), _connector='OR'), name='capital_score_subject_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='creditpolicy',
            constraint=models.UniqueConstraint(fields=('funder', 'version'), name='uniq_policy_version'),
        ),
        migrations.AddIndex(
            model_name='capitallimit',
            index=models.Index(fields=['funder', 'scope', 'debtor', 'company', 'sector', '-created_at'], name='capital_lim_funder__6e8dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalledgerentry',
            index=models.Index(fields=['funder', 'debtor'], name='capital_led_funder__18e3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalledgerentry',
            index=models.Index(fields=['funder', 'company'], name='capital_led_funder__ba7bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalledgerentry',
            index=models.Index(fields=['advance'], name='capital_led_advance_9ddc85_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalledgerentry',
            index=models.Index(fields=['facility'], name='capital_led_facilit_21eaa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='capitalledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='capital_ledger_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='capitalalert',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('dedupe_key',), name='uniq_open_capital_alert'),
        ),
        migrations.AddConstraint(
            model_name='booksnapshot',
            constraint=models.UniqueConstraint(fields=('funder', 'as_of'), name='uniq_book_snapshot_per_day'),
        ),
        migrations.AddConstraint(
            model_name='fundermembership',
            constraint=models.UniqueConstraint(fields=('funder', 'user'), name='uniq_funder_membership'),
        ),
        migrations.AddIndex(
            model_name='invoiceassessment',
            index=models.Index(fields=['invoice', '-created_at'], name='capital_inv_invoice_df988a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceassessment',
            index=models.Index(fields=['funder', 'decision', '-created_at'], name='capital_inv_funder__a8c305_idx'),
        ),
    ]
