# Generated by Django 6.0.6 on 2026-10-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_accounting_backfill'),
        ('core', '0140_fast_pay_sandbox_and_ledger'),
    ]

    operations = [
    ]
