# Generated by Django 6.0.6 on 2026-10-05 07:17

from django.db import migrations, models


def _route_is_international(snapshot):
    """From a quote's saved route (route_snapshot.response): crossed a border,
    or names a country other than South Africa."""
    resp = (snapshot or {}).get('response') if isinstance(snapshot, dict) else None
    if not isinstance(resp, dict):
        return False
    if resp.get('cross_border') is True:
        return True
    countries = resp.get('countries') or []
    for rt in resp.get('routes') or []:
        if isinstance(rt, dict):
            countries = list(countries) + list(rt.get('country_codes') or [])
    return any(str(c).upper() not in ('ZA', 'ZAF', 'SOUTH AFRICA', '') for c in countries)


def backfill(apps, schema_editor):
    Quote = apps.get_model('core', 'Quote')
    Load = apps.get_model('core', 'Load')
    ids = [q.pk for q in Quote.objects.exclude(route_snapshot={}).only('pk', 'route_snapshot').iterator()
           if _route_is_international(q.route_snapshot)]
    Quote.objects.filter(pk__in=ids).update(is_international=True)
    Load.objects.filter(quote_id__in=ids).update(is_international=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_merge_20261002_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
