# Generated by Django 6.0.6 on 2026-10-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_quote_load_is_international'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePricingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('picked_choice', models.CharField(blank=True, choices=[('safe', 'Safe'), ('balanced', 'Balanced'), ('stretch', 'Stretch'), ('custom', 'Custom')], max_length=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('floor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('likelihood_level', models.CharField(blank=True, choices=[('model', 'Model'), ('rules', 'Rules')], max_length=10)),
                ('likelihood_at_final_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('band_at_final', models.CharField(blank=True, max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('market_tier', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quote_pricing_decisions',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='pool_pricing_data',
            field=models.BooleanField(default=False, help_text="Share this company's quote outcomes with the pooled win model, and use it when there is no company or personal model yet"),
        ),
        migrations.AddField(
            model_name='company',
            name='pricing_include_empty_return',
            field=models.BooleanField(default=False, help_text='Include the empty run home in the cost floor of one-way quotes by default'),
        ),
        migrations.AddField(
            model_name='mlmodelversion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_model_versions', to='core.company'),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('price', 'Price'), ('timing', 'Timing'), ('capacity', 'Capacity'), ('relationship', 'Relationship'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='loss_reason_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='scope',
            field=models.CharField(choices=[('user', 'Per-User'), ('company', 'Per-Company'), ('global', 'Global')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='mlmodelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('status', 'active')), fields=('scope', 'company'), name='unique_active_model_per_company'),
        ),
        migrations.AddField(
            model_name='quotepricingdecision',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_pricing_decisions', to='core.company'),
        ),
        migrations.AddField(
            model_name='quotepricingdecision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_pricing_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotepricingdecision',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_decision', to='core.quote'),
        ),
        migrations.AddIndex(
            model_name='quotepricingdecision',
            index=models.Index(fields=['company', 'picked_choice'], name='quote_prici_company_0f026c_idx'),
        ),
    ]
