# Generated by Django 6.0.6 on 2026-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_pricing_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='driver_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='load',
            name='toll_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
