# Generated by Django 6.0.6 on 2026-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_backfill_load_toll_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operating_cost_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your operating cost per km excl. fuel and tolls (driver wages, finance, insurance, licences, tyres, maintenance, overheads). Blank = worked out from your expenses.', max_digits=8, null=True),
        ),
    ]
