# Generated by Django 6.0.6 on 2026-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_company_operating_cost_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='driver_allowance_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driver allowance you pay per night away (used when no approved allowance is on record).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='was_sent',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
    ]
