# Generated by Django 6.0.6 on 2026-10-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_company_driver_allowance_quote_was_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='empty_return_min_km',
            field=models.DecimalField(decimal_places=1, default=300, help_text='One-way distance (km) from which the empty return is included by default', max_digits=7),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price_mode',
            field=models.CharField(choices=[('LIVE', 'Official price (live)'), ('OWN', 'Own price')], default='LIVE', help_text='LIVE = quote on the official FIASA price for the fuel zone; OWN = quote on fuel_price_own.', max_length=4),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price_own',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="The fleet's own diesel price per litre excl. VAT (fuel card etc.). Empty = LIVE.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price_own_set_at',
            field=models.DateTimeField(blank=True, help_text='When fuel_price_own was last set by a person.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='include_empty_return_default',
            field=models.BooleanField(default=True, help_text='Price the empty run home into one-way quotes of at least empty_return_min_km by default'),
        ),
        migrations.AddField(
            model_name='company',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lowest price (excl. VAT) a quote may go out at. Empty = no minimum.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='cost_floor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost floor when priced (null = incomplete)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='costing_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='costing_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='quote_costing output when priced (lines, warnings)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='empty_return_included',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_effective_from',
            field=models.DateTimeField(blank=True, help_text='Effective date of the official price in force when priced', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_litres',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Litres priced in (loaded + empty return)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_official_at_pricing',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Official zone price in force when priced', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_price_source',
            field=models.CharField(blank=True, default='', help_text='own | official | override (blank = not priced)', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_price_used',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Diesel R/L the quote was priced on', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='fuel_zone',
            field=models.CharField(blank=True, default='', help_text='INLAND | COASTAL', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='priced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='priced_vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle type the quote was priced on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vehicletype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_price_per_litre',
            field=models.DecimalField(decimal_places=4, default=23.5, help_text='Deprecated mirror of the diesel price in use (own price, or the official zone price).', max_digits=8),
        ),
    ]
