# Generated by Django 6.0.6 on 2026-10-07 12:59

from django.db import migrations, models


def _nulls_back_to_default(apps, schema_editor):
    # Reverse only: the column becomes NOT NULL again, so empty = the old 10.00.
    apps.get_model('core', 'Company').objects.filter(default_base_rate_per_km__isnull=True) \
        .update(default_base_rate_per_km=10)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_quote_priced_vehicle_type_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='default_base_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Default price per km for new quotes (ZAR, excl. VAT). Empty = none.', max_digits=8, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, _nulls_back_to_default),
    ]
