# Generated by Django 6.0.6 on 2026-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_company_default_price_per_km_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fuel_price_petrol_grade',
            field=models.CharField(choices=[('95', 'ULP 95'), ('93', 'ULP 93 (inland only)')], default='95', help_text='Official petrol grade for LIVE pricing. 93 applies inland only; coastal is always 95.', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price_petrol_mode',
            field=models.CharField(choices=[('LIVE', 'Official price (live)'), ('OWN', 'Own price')], default='LIVE', help_text='LIVE = quote petrol/hybrid trucks on the official price for the fuel zone; OWN = quote on fuel_price_petrol.', max_length=4),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price_petrol_set_at',
            field=models.DateTimeField(blank=True, help_text='When fuel_price_petrol was last set by a person.', null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='petrol_93_coastal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 93 ULP coastal retail price (ZAR/litre); NULL when not published (93 is normally sold inland only)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='petrol_95_coastal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 95 ULP coastal retail price (ZAR/litre); NULL when not published', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_price_petrol',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="The fleet's own petrol price per litre (used when fuel_price_petrol_mode is OWN). Petrol and hybrid trucks.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_93',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 93 ULP inland (Gauteng) retail price (ZAR/litre); NULL when not published', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='petrol_95',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Petrol 95 ULP inland (Gauteng) retail price (ZAR/litre); NULL when not published', max_digits=8, null=True),
        ),
    ]
