# Generated by Django 6.0.6 on 2026-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_company_petrol_mode_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(db_index=True, help_text='The SAST day the price took effect (legacy rows: the 1st of their month). The exact moment is effective_from. One row per (date, source): a FIASA and a MANUAL price can exist for the same day, and neither ever overwrites the other.'),
        ),
        migrations.AddConstraint(
            model_name='fuelprice',
            constraint=models.UniqueConstraint(fields=('date', 'source'), name='fuel_prices_date_source_uniq'),
        ),
    ]
