# Generated by Django 6.0.6 on 2026-10-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_quote_margin_percentage_wider'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Transporter this subscription acts for on fleet webhooks. Empty = none.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='core.company'),
        ),
    ]
