# Generated by Django 6.0.6 on 2026-10-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_quote_margin_percentage_wider'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='actual_tonnes',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weighbridge tonnes delivered', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='actual_tonnes_source',
            field=models.CharField(blank=True, default='', help_text='weighbridge | manual | tms', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='min_tonnes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='planned_tonnes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pricing_basis',
            field=models.CharField(choices=[('per_load', 'Per load'), ('per_tonne', 'Per tonne')], default='per_load', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='rate_per_tonne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='weighbridge_slip',
            field=models.CharField(blank=True, default='', help_text='Weighbridge ticket / slip number', max_length=60),
        ),
        migrations.AddField(
            model_name='quote',
            name='basis_vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Chosen truck for a tonnage quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vehicletype'),
        ),
        migrations.AddField(
            model_name='quote',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='loads_planned',
            field=models.PositiveIntegerField(blank=True, help_text='Loads on the basis truck (server-set when priced)', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='min_tonnes_per_load',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum tonnes invoiced per load (null = planned load)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='pricing_basis',
            field=models.CharField(choices=[('per_load', 'Per load'), ('per_tonne', 'Per tonne')], default='per_load', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='rate_per_tonne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per tonne excl. VAT (per_tonne quotes)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tonnes_per_load',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tonnes per load (planned load size)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_tonnes',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume contract total tonnes (null = one consignment)', max_digits=12, null=True),
        ),
    ]
