# Generated by Django 6.0.6 on 2026-10-08 09:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_quote_margin_percentage_wider'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_surcharge_enabled', models.BooleanField(default=True)),
                ('fuel_surcharge_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('fuel_surcharge_prompt_pending', models.BooleanField(default=False)),
                ('fuel_surcharge_decided_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_alerts_enabled', models.BooleanField(default=True)),
                ('follow_ups_enabled', models.BooleanField(default=True)),
                ('follow_up_after_days', models.PositiveSmallIntegerField(default=3)),
                ('expiry_nudge_days', models.PositiveSmallIntegerField(default=2)),
                ('weekly_margin_email_enabled', models.BooleanField(default=True)),
                ('pricing_setup', models.JSONField(blank=True, default=dict)),
                ('pricing_setup_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_automation', to='core.company')),
            ],
            options={
                'db_table': 'quote_automation_settings',
            },
        ),
        migrations.CreateModel(
            name='QuoteFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at_source', models.CharField(default='recorded', max_length=10)),
                ('expiry_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_nudged_for', models.DateField(blank=True, help_text='valid_until the expiry nudge was for', null=True)),
                ('no_answer_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('reminder_last_to', models.CharField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='core.quote')),
                ('reminder_last_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_follow_ups',
            },
        ),
        migrations.CreateModel(
            name='QuoteFuelClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basis_price', models.DecimalField(decimal_places=4, help_text='Official zone price at pricing (R/L)', max_digits=8)),
                ('basis_effective_from', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(max_length=10)),
                ('product', models.CharField(help_text="'diesel' | 'petrol_95' | 'petrol_93'", max_length=12)),
                ('litres', models.DecimalField(decimal_places=3, max_digits=10)),
                ('text', models.TextField()),
                ('stamped_at', models.DateTimeField()),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_clause', to='core.quote')),
            ],
            options={
                'db_table': 'quote_fuel_clauses',
            },
        ),
        migrations.CreateModel(
            name='FuelChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First-Wednesday date of the price period (SAST)')),
                ('product', models.CharField(max_length=12)),
                ('zone', models.CharField(max_length=10)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effective_from', models.DateTimeField()),
                ('target_margin_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quotes', models.JSONField(blank=True, default=list)),
                ('quotes_affected', models.PositiveIntegerField(default=0)),
                ('quotes_under_target', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_change_alerts', to='core.company')),
            ],
            options={
                'db_table': 'fuel_change_alerts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'period_start', 'product'), name='uniq_fuel_change_alert_company_period_product')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMarginReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('figures', models.JSONField(blank=True, default=dict)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_margin_reports', to='core.company')),
            ],
            options={
                'db_table': 'weekly_margin_reports',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('company', 'week_start'), name='uniq_weekly_margin_report_company_week')],
            },
        ),
    ]
