# Generated by Django 6.0.6 on 2026-10-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_seed_nbcrfli_driver_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsearchhistory',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
