# Generated by Django 6.0.6 on 2026-10-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_location_search_history_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollplaza',
            name='country',
            field=models.CharField(default='ZA', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='match_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='operator',
            field=models.CharField(blank=True, default='SANRAL', help_text='SANRAL, N3TC, Bakwena, TRAC, …', max_length=40),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='plaza_group',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='plaza_type',
            field=models.CharField(choices=[('mainline', 'Mainline'), ('ramp', 'Ramp')], default='mainline', max_length=10),
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='through_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='route',
            field=models.CharField(choices=[('N1', 'N1 — Cape Town to Johannesburg / Polokwane'), ('N2', 'N2 — Cape Town to Durban (coastal)'), ('N3', 'N3 — Johannesburg to Durban'), ('N4', 'N4 — Pretoria to Maputo'), ('N14', 'N14 — Johannesburg to Springbok'), ('N17', 'N17 — Johannesburg to Ermelo / Swaziland'), ('R30', 'R30/R730/R34 — Bloemfontein region'), ('EN4', 'EN4 — Mozambique, Ressano Garcia to Maputo (TRAC)'), ('REVIMO', 'Mozambique — Maputo–Katembe bridge, Maputo ring road, N200 (REVIMO)')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='TollTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Last day in force (inclusive); blank = open', null=True)),
                ('tariff_class_2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tariff_class_3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tariff_class_4', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tariff_class_5', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_name', models.CharField(blank=True, default='', max_length=300)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to='core.tollplaza')),
            ],
            options={
                'db_table': 'toll_tariffs',
                'ordering': ['plaza_id', '-effective_from'],
                'unique_together': {('plaza', 'effective_from')},
            },
        ),
    ]
