# Generated by Django 6.0.6 on 2026-10-08 09:51

from django.db import migrations, models


def external_ids_from_notes(apps, schema_editor):
    """trips/sync wrote the TMS id into notes as 'ext_id:<id>' before the
    field existed: move it onto external_id (first load per company + id;
    later duplicates keep only the note)."""
    import re
    Load = apps.get_model('core', 'Load')
    seen = set()
    pattern = re.compile(r'(?:^|\s)ext_id:(\S+)')
    qs = (Load.objects.filter(notes__contains='ext_id:', external_id='')
          .order_by('pk').only('id', 'company_id', 'notes'))
    for load in qs.iterator(chunk_size=500):
        m = pattern.search(load.notes or '')
        if not m:
            continue
        key = (load.company_id, m.group(1)[:100])
        if key in seen or Load.objects.filter(company_id=key[0], external_id=key[1]).exists():
            continue
        seen.add(key)
        Load.objects.filter(pk=load.pk).update(external_id=key[1], external_source='tms_api')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_load_estimate_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='load',
            name='external_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='load',
            name='invoice_mismatch',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='load',
            name='return_of_external_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(external_ids_from_notes, migrations.RunPython.noop),
    ]
