# Generated by Django 6.0.6 on 2026-10-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_border_fee_corrections_2026_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollplaza',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='axle_configuration',
            field=models.CharField(blank=True, default='', help_text='Axles per unit, horse first: "3+2+2" interlink, "3+3" semi, "3" rigid', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='gross_mass_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Gross vehicle / combination mass in kg (truck + trailers + maximum load)', null=True),
        ),
    ]
