# Generated by Django 6.0.6 on 2026-10-08 09:30

import django.db.models.deletion
from django.db import migrations, models


SNAPSHOT_KEYS = ('version', 'trip', 'vehicle', 'diesel', 'litres', 'lines', 'floor', 'floor_known',
                 'floor_complete', 'target_margin_pct', 'target_price', 'minimum_charge', 'price', 'margin',
                 'margin_pct', 'warnings', 'blocking', 'resolution')


INPUT_KEYS = ('toll_cost_one_way', 'tolls_confirmed_none', 'tolls_unknown', 'tolls_empty_return', 'duration_minutes',
              'driver_cost_is_override', 'driver_nights', 'include_empty_return', 'vehicle_type_id', 'border_cost',
              'use_official_fuel', 'fuel_price_override', 'toll_cost_return', 'border_cost_empty_return',
              'border_estimate', 'border_estimate_empty_return', 'border_cost_is_override', 'border_costs_unknown',
              'clearing_agent_fee', 'abnormal_load')


def _costing_inputs(q):
    """A frozen copy of trip_costing.quote_costing_inputs (migrations never
    import app services)."""
    ci = dict(q.costing_inputs or {})
    out = {k: ci[k] for k in INPUT_KEYS if k in ci and ci[k] not in (None, '')}
    out['toll_cost'] = float(q.toll_charges or 0)
    if q.estimated_duration_minutes and 'duration_minutes' not in out:
        out['duration_minutes'] = float(q.estimated_duration_minutes)
    if ci.get('driver_cost_is_override'):
        out['driver_cost'] = float(q.driver_allowance or 0)
    if q.priced_vehicle_type_id and 'vehicle_type_id' not in out:
        out['vehicle_type_id'] = q.priced_vehicle_type_id
    if q.empty_return_included is not None and 'include_empty_return' not in out:
        out['include_empty_return'] = bool(q.empty_return_included)
    return out


def copy_from_quotes(apps, schema_editor):
    """Loads converted before this migration: carry their quote's pricing
    snapshot (same rule as convert_to_load). Loads without a priced quote stay
    costing_source '' (legacy: labelled standard estimate)."""
    Load = apps.get_model('core', 'Load')
    qs = (Load.objects.filter(quote__isnull=False, costing_source='')
          .select_related('quote').only('id', 'quote'))
    for load in qs.iterator(chunk_size=500):
        q = load.quote
        snap = q.costing_snapshot or {}
        # Trip shape and costing inputs come over whether or not it was priced
        # (same as convert_to_load).
        common = dict(trip_type=q.trip_type or 'ONE_WAY', return_location=q.return_location or '',
                      return_distance=q.return_distance, return_date=q.return_date,
                      return_cargo=q.return_cargo or '', costing_inputs=_costing_inputs(q))
        if not snap.get('lines'):
            Load.objects.filter(pk=load.pk).update(**common)
            continue
        Load.objects.filter(pk=load.pk).update(
            **common,
            costing_snapshot={k: snap.get(k) for k in SNAPSHOT_KEYS if k in snap},
            cost_floor=q.cost_floor, empty_return_assumed=q.empty_return_included,
            fuel_price_used=q.fuel_price_used, fuel_price_source=q.fuel_price_source or '',
            fuel_zone=q.fuel_zone or '', fuel_effective_from=q.fuel_effective_from, fuel_litres=q.fuel_litres,
            priced_vehicle_type_id=q.priced_vehicle_type_id, costed_at=q.priced_at,
            quoted_price=q.total_amount, quoted_cost_floor=q.cost_floor, quoted_margin_pct=q.margin_percentage,
            costing_source='quote',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_webhooksubscription_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='cost_floor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor of costing_snapshot (null = incomplete / unknown)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='costed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='costing_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='load',
            name='costing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='load',
            name='costing_source',
            field=models.CharField(blank=True, choices=[('', 'Not costed (legacy)'), ('quote', 'Quote snapshot'), ('computed', 'Computed from the load'), ('unknown', 'Not enough information')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='empty_return_assumed',
            field=models.BooleanField(blank=True, help_text='The costing includes an empty return leg (null = unknown)', null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='fuel_effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='fuel_litres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='fuel_price_source',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='fuel_price_used',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='fuel_zone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='priced_vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vehicletype'),
        ),
        migrations.AddField(
            model_name='load',
            name='quoted_cost_floor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='quoted_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='return_cargo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='load',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='return_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='return_location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='load',
            name='trip_type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], default='ONE_WAY', max_length=20),
        ),
        migrations.RunPython(copy_from_quotes, migrations.RunPython.noop),
    ]
