# Generated by Django 6.0.6 on 2026-10-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_quoteoutcome_actuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='costs_closed',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteoutcome',
            name='estimated_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='allow_legacy_signature',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='load',
            name='costing_inputs',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='costing_snapshot',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='costing_source',
            field=models.CharField(blank=True, choices=[('', 'Not costed (legacy)'), ('quote', 'Quote snapshot'), ('computed', 'Computed from the load'), ('unknown', 'Not enough information')], db_default='', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='estimate_basis',
            field=models.CharField(blank=True, db_default='', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='load',
            name='expecting_return',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='load',
            name='external_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='load',
            name='external_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='load',
            name='fuel_price_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='fuel_zone',
            field=models.CharField(blank=True, db_default='', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='invoice_mismatch',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='return_cargo',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='load',
            name='return_link_source',
            field=models.CharField(blank=True, choices=[('manual', 'Linked by a user'), ('tms', 'Linked by the TMS'), ('convert', 'Linked when booking the quote')], db_default='', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='return_location',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='load',
            name='return_of_external_ref',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], db_default='ONE_WAY', default='ONE_WAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteoutcome',
            name='actual_cost_basis',
            field=models.CharField(blank=True, db_default='', default='', help_text='actual (expenses) | estimate', max_length=12),
        ),
    ]
