# Generated by Django 6.0.6 on 2026-10-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_company_is_test_company'),
        ('core', '0177_quote_load_tonnage'),
    ]

    operations = [
    ]
