# Generated by Django 6.0.6 on 2026-10-08 20:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# ON DELETE in the database (PostgreSQL only, production; SQLite keeps
# Django's own handling), as 0176 does for loads: an older app image that
# doesn't know these tables can still delete a quote, a company or a user
# (Quote.delete(), Company.delete(), demo_seed.reset_demo_company) without an
# IntegrityError from the new rows pointing at them.
DB_ON_DELETE = (
    ('quote_automation_settings', 'company_id', 'CASCADE'),
    ('quote_follow_ups', 'quote_id', 'CASCADE'),
    ('quote_follow_ups', 'reminder_last_by_id', 'SET NULL'),
    ('quote_fuel_clauses', 'quote_id', 'CASCADE'),
    ('fuel_change_alerts', 'company_id', 'CASCADE'),
    ('weekly_margin_reports', 'company_id', 'CASCADE'),
)


_REWRITE = """
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT con.conname, pg_get_constraintdef(con.oid) AS def
             FROM pg_constraint con
             JOIN pg_class rel ON rel.oid = con.conrelid
             JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY (con.conkey)
            WHERE rel.relname = '{table}' AND con.contype = 'f' AND att.attname = '{column}'
  LOOP
    EXECUTE format('ALTER TABLE {table} DROP CONSTRAINT %I', r.conname);
    EXECUTE format('ALTER TABLE {table} ADD CONSTRAINT %I %s ON DELETE {action} DEFERRABLE INITIALLY DEFERRED',
                   r.conname, split_part(split_part(r.def, ' ON DELETE ', 1), ' DEFERRABLE', 1));
  END LOOP;
END $$;
"""


def db_on_delete(apps, schema_editor):
    """Queued after the foreign keys themselves: CreateModel adds them as
    deferred SQL at the end of this migration, so the rewrite is queued there
    too (runs last, in the same transaction)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table, column, action in DB_ON_DELETE:
        schema_editor.deferred_sql.append(_REWRITE.format(table=table, column=column, action=action))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_quote_load_tonnage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_surcharge_enabled', models.BooleanField(db_default=True, default=True)),
                ('fuel_surcharge_threshold_pct', models.DecimalField(db_default=Decimal('5.00'), decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('fuel_surcharge_prompt_pending', models.BooleanField(db_default=False, default=False)),
                ('fuel_surcharge_decided_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_alerts_enabled', models.BooleanField(db_default=True, default=True)),
                ('follow_ups_enabled', models.BooleanField(db_default=True, default=True)),
                ('follow_up_after_days', models.PositiveSmallIntegerField(db_default=3, default=3)),
                ('expiry_nudge_days', models.PositiveSmallIntegerField(db_default=2, default=2)),
                ('weekly_margin_email_enabled', models.BooleanField(db_default=True, default=True)),
                ('pricing_setup', models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict)),
                ('pricing_setup_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_automation', to='core.company')),
            ],
            options={
                'db_table': 'quote_automation_settings',
            },
        ),
        migrations.CreateModel(
            name='QuoteFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at_source', models.CharField(db_default='recorded', default='recorded', max_length=10)),
                ('expiry_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_nudged_for', models.DateField(blank=True, help_text='valid_until the expiry nudge was for', null=True)),
                ('no_answer_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('reminder_last_to', models.CharField(blank=True, db_default='', default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='core.quote')),
                ('reminder_last_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_follow_ups',
            },
        ),
        migrations.CreateModel(
            name='QuoteFuelClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basis_price', models.DecimalField(decimal_places=4, help_text='Official zone price at pricing (R/L)', max_digits=8)),
                ('basis_effective_from', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(max_length=10)),
                ('product', models.CharField(help_text="'diesel' | 'petrol_95' | 'petrol_93'", max_length=12)),
                ('litres', models.DecimalField(decimal_places=3, max_digits=10)),
                ('text', models.TextField()),
                ('stamped_at', models.DateTimeField()),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_clause', to='core.quote')),
            ],
            options={
                'db_table': 'quote_fuel_clauses',
            },
        ),
        migrations.CreateModel(
            name='FuelChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First-Wednesday date of the price period (SAST)')),
                ('product', models.CharField(max_length=12)),
                ('zone', models.CharField(max_length=10)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effective_from', models.DateTimeField()),
                ('target_margin_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quotes', models.JSONField(blank=True, db_default=models.Value([], output_field=models.JSONField()), default=list)),
                ('quotes_affected', models.PositiveIntegerField(db_default=0, default=0)),
                ('quotes_under_target', models.PositiveIntegerField(db_default=0, default=0)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('message', models.TextField(blank=True, db_default='', default='')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_change_alerts', to='core.company')),
            ],
            options={
                'db_table': 'fuel_change_alerts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'period_start', 'product'), name='uniq_fuel_change_alert_company_period_product')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMarginReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('figures', models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict)),
                ('recipients', models.PositiveIntegerField(db_default=0, default=0)),
                ('emails_sent', models.PositiveIntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_margin_reports', to='core.company')),
            ],
            options={
                'db_table': 'weekly_margin_reports',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('company', 'week_start'), name='uniq_weekly_margin_report_company_week')],
            },
        ),
        # Last: the tables exist. Reverse is a no-op (the tables go with this migration).
        migrations.RunPython(db_on_delete, migrations.RunPython.noop),
    ]
