# Generated by Django 6.0.6 on 2026-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_merge_20261009_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='fleet_write_enabled',
            field=models.BooleanField(db_default=False, default=False, help_text="May create and update this company's loads, vehicles and drivers through fleet webhooks."),
        ),
    ]
