# Generated by Django 6.0.6 on 2026-10-08 21:15 (fleet actuals; two new tables, every NOT NULL column has a db_default)

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_quote_followups_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetFuelMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('VEHICLE', 'One truck'), ('VEHICLE_TYPE', 'Vehicle type')], max_length=20)),
                ('provider', models.CharField(db_default='cartrack', default='cartrack', max_length=20)),
                ('fuel_source', models.CharField(blank=True, db_default='', default='', max_length=20)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(db_default=0, default=0)),
                ('litres', models.FloatField(db_default=0, default=0)),
                ('l_per_100km', models.FloatField(blank=True, null=True)),
                ('loaded_km', models.FloatField(db_default=0, default=0)),
                ('loaded_litres', models.FloatField(db_default=0, default=0)),
                ('loaded_l_per_100km', models.FloatField(blank=True, null=True)),
                ('loaded_mean_load_ratio', models.FloatField(blank=True, null=True)),
                ('other_km', models.FloatField(db_default=0, default=0)),
                ('other_l_per_100km', models.FloatField(blank=True, null=True)),
                ('rated_burn_l_per_100km', models.FloatField(blank=True, null=True)),
                ('rated_method', models.CharField(blank=True, db_default='', default='', max_length=30)),
                ('vehicles_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('windows_used', models.PositiveIntegerField(db_default=0, default=0)),
                ('windows_rejected', models.PositiveIntegerField(db_default=0, default=0)),
                ('rejections', models.JSONField(blank=True, db_default=[], default=list)),
                ('confidence', models.CharField(db_default='insufficient', default='insufficient', max_length=20)),
                ('sufficient', models.BooleanField(db_default=False, default=False)),
                ('note', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('burn_mode', models.CharField(choices=[('AUTO', 'Automatic'), ('MEASURED', 'Use measured figure'), ('CONFIGURED', 'Use my figure')], db_default='AUTO', default='AUTO', max_length=20)),
                ('burn_mode_set_at', models.DateTimeField(blank=True, null=True)),
                ('burn_mode_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_fuel_measurements', to='core.company')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_measurements', to='core.vehicle')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_measurements', to='core.vehicletype')),
            ],
            options={
                'db_table': 'fleet_fuel_measurements',
                'indexes': [models.Index(fields=['company', 'scope'], name='fleet_fuel__company_672ed5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'VEHICLE_TYPE')), fields=('company', 'vehicle_type'), name='uniq_fuel_measurement_per_company_type'), models.UniqueConstraint(condition=models.Q(('scope', 'VEHICLE')), fields=('company', 'vehicle'), name='uniq_fuel_measurement_per_company_vehicle')],
            },
        ),
        migrations.CreateModel(
            name='FleetFuelSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, db_default='', default='', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_default='running', default='running', max_length=20)),
                ('message', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('summary', models.JSONField(blank=True, db_default={}, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_fuel_runs', to='core.company')),
            ],
            options={
                'db_table': 'fleet_fuel_sync_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', '-started_at'], name='fleet_fuel__company_58197f_idx')],
            },
        ),
    ]
