# Generated by Django 6.0.6 on 2026-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_quote_followups_backfill'),
        ('core', '0179_webhooksubscription_fleet_write'),
    ]

    operations = [
    ]
