# Generated by Django 6.0.6 on 2026-10-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_fleet_fuel_measurements'),
        ('core', '0180_merge_20261009_1707'),
    ]

    operations = [
    ]
