"""Independent reference calculator for the golden ledger dataset.

Pure standard library (decimal, datetime, json): it imports nothing from
TruckWys, so the figures it derives are a second, independent reading of
the accounting rules, not a re-run of the app code. The `expected` block in
core/tests/fixtures/golden_ledger.json was generated by this module and
frozen; test_golden_ledger asserts (a) this module still derives exactly the
frozen block and (b) the real services produce the same figures.

Regenerate after deliberately editing the dataset:

    python core/tests/golden_reference.py --freeze core/tests/fixtures/golden_ledger.json

Rules implemented (docs/foundation/SPEC.md, core/tax_codes.py and the
module docstring of core/services/accounting_reports.py):

  Lines      gross = qty x unit_price; discount = discount_amount, or
             gross x pct / 100; net = round2(gross - discount) (discount
             BEFORE VAT); vat = round2(net x rate); total = net + vat.
             round2 = ROUND_HALF_UP to the cent. Rate: STANDARD 15% (from
             2018-04-01), ZERO_RATED / EXEMPT / NO_VAT 0%.
             Line discount reported = round2(gross) - net when a discount
             was given.
  Invoice    subtotal/vat/discount/total = sums of the lines.
             due_date = issue_date + N days for payment_terms NETN.
  Counting   An invoice counts (accrual) when it ends ISSUED (not draft,
             not void), on its issue_date. A credit note counts on its own
             issue_date while ISSUED; a voided credit note never counts.
  Revenue    accrual: sum(invoice subtotal) - sum(credit note subtotal).
             output VAT: sum(invoice VAT) - sum(credit note VAT); split by
             tax code from the lines.
  Full CN    mirrors every still-uncredited part of each line: an untouched
             line exactly (net and VAT), a partly credited line its
             remaining net and VAT.
  Cash       payments by payment_date (after edits; deleted payments gone).
             Each payment's applicable part = min(amount, invoice total -
             earlier payments on that invoice), never below 0, where earlier
             = (payment_date, creation order) before it. Its revenue share
             = round2(applicable x subtotal / total). The rest is
             overpayment (customer credit, not revenue).
  Expenses   amount is gross. Input VAT = vat_amount if the fixture gives
             one, else round2(gross x 15/115) for STANDARD, 0 otherwise.
             REJECTED never counts; PENDING and APPROVED do.
  Profit     accrual: revenue - expenses excl. VAT; cash: cash revenue -
             expenses excl. VAT. margin_pct = round2(profit / revenue x 100).
  Ageing     as at D, per invoice that is (finally) issued with
             issue_date <= D: outstanding = total - payments dated <= D -
             ISSUED credit notes dated <= D. Negative -> customer credit,
             zero -> skipped, positive -> bucket by days = D - due_date:
             <=0 current, 1-30, 31-60, 61-90, >90.
  Status     final status as the ledger derives it with "today" =
             dataset.status_as_of: void -> CANCELLED, draft -> DRAFT;
             balance <= 0 with money against it -> PAID if anything was
             paid else CREDITED; paid > 0 -> PARTIALLY_PAID; due_date <
             today -> OVERDUE; else SENT.
"""
import json
import sys
from collections import OrderedDict
from datetime import date, timedelta
from decimal import Decimal, ROUND_HALF_UP

CENT = Decimal('0.01')
ZERO = Decimal('0.00')
TAX_CODES = ('STANDARD', 'ZERO_RATED', 'EXEMPT', 'NO_VAT')
BUCKETS = ('current', '1_30', '31_60', '61_90', '90_plus')


class FixtureError(ValueError):
    """The dataset asks for something the rules forbid (e.g. an
    overpayment without allow_overpayment). Fix the fixture."""


def r2(x):
    return Decimal(x).quantize(CENT, rounding=ROUND_HALF_UP)


def D(x):
    return Decimal(str(x))


def money(x):
    return str(r2(x))


def rate(code, on):
    if code not in TAX_CODES:
        raise FixtureError(f'unknown tax code {code}')
    if code != 'STANDARD':
        return Decimal('0')
    return Decimal('0.15') if on >= date(2018, 4, 1) else Decimal('0.14')


def d(s):
    return date.fromisoformat(s)


def line_amounts(line, on):
    """One line under the rounding rule -> dict(net, vat, total, discount, gross)."""
    qty = D(line.get('quantity', '1'))
    price = D(line['unit_price'])
    gross = qty * price
    if line.get('discount_amount') not in (None, ''):
        disc = D(line['discount_amount'])
    elif line.get('discount_percent') not in (None, ''):
        disc = gross * D(line['discount_percent']) / Decimal('100')
    else:
        disc = Decimal('0')
    net = r2(gross - disc)
    vat = r2(net * rate(line['tax_code'], on))
    return {'gross': r2(gross), 'net': net, 'vat': vat, 'total': net + vat,
            'discount': (r2(gross) - net) if disc else ZERO}


def terms_days(terms):
    t = str(terms).upper()
    if not t.startswith('NET') or not t[3:].isdigit():
        raise FixtureError(f'bad terms {terms}')
    return int(t[3:])


class Book:
    """Replays a dataset into plain in-memory records."""

    def __init__(self, ds, check=True):
        self.ds = ds
        self.customers = {c['id']: c for c in ds['customers']}
        self.invoices = OrderedDict()
        for inv in ds['invoices']:
            issue = d(inv['issue_date'])
            lines = []
            for ln in inv['lines']:
                a = line_amounts(ln, issue)
                lines.append({'id': ln['id'], 'tax_code': ln['tax_code'], **a})
            days = terms_days(inv['payment_terms'])
            self.invoices[inv['id']] = {
                'id': inv['id'], 'customer': inv['customer'], 'issue_date': issue,
                'due_date': issue + timedelta(days=days), 'terms_days': days,
                'status': 'DRAFT' if inv['status'] == 'draft' else 'ISSUED',
                'lines': lines,
                'subtotal': sum((l['net'] for l in lines), ZERO),
                'vat': sum((l['vat'] for l in lines), ZERO),
                'discount': sum((l['discount'] for l in lines), ZERO),
            }
            self.invoices[inv['id']]['total'] = self.invoices[inv['id']]['subtotal'] + self.invoices[inv['id']]['vat']
        self.payments = OrderedDict()   # id -> dict, insertion = creation order
        self.credit_notes = OrderedDict()
        self._seq = 0
        for ev in ds['events']:
            getattr(self, '_ev_' + ev['type'])(ev)
        for inv in ds['invoices'] if check else ():
            want = inv['status']
            got = self.invoices[inv['id']]['status']
            if (want, got) not in (('draft', 'DRAFT'), ('void', 'VOID'), ('sent', 'ISSUED')):
                raise FixtureError(f'{inv["id"]}: final status intent {want} but replay ends {got}')

    # -- ledger helpers ------------------------------------------------------
    def paid(self, inv_id, as_of=None):
        return sum((p['amount'] for p in self.payments.values()
                    if p['invoice'] == inv_id and (as_of is None or p['date'] <= as_of)), ZERO)

    def credited(self, inv_id, as_of=None):
        return sum((c['total'] for c in self.credit_notes.values()
                    if c['invoice'] == inv_id and c['status'] == 'ISSUED'
                    and (as_of is None or c['date'] <= as_of)), ZERO)

    def balance(self, inv_id):
        inv = self.invoices[inv_id]
        return inv['total'] - self.paid(inv_id) - self.credited(inv_id)

    def _issued(self, inv_id, what):
        inv = self.invoices[inv_id]
        if inv['status'] != 'ISSUED':
            raise FixtureError(f'{what}: invoice {inv_id} is {inv["status"]}')
        return inv

    # -- events --------------------------------------------------------------
    def _ev_payment(self, ev):
        self._issued(ev['invoice'], ev['id'])
        amount = r2(D(ev['amount']))
        if amount <= 0:
            raise FixtureError(f'{ev["id"]}: amount must be positive')
        if amount > self.balance(ev['invoice']) and not ev.get('allow_overpayment'):
            raise FixtureError(f'{ev["id"]}: {amount} exceeds balance {self.balance(ev["invoice"])}')
        if d(ev['payment_date']) < self.invoices[ev['invoice']]['issue_date']:
            raise FixtureError(f'{ev["id"]}: dated before its invoice')
        self._seq += 1
        self.payments[ev['id']] = {'id': ev['id'], 'invoice': ev['invoice'], 'amount': amount,
                                   'date': d(ev['payment_date']), 'seq': self._seq,
                                   'source': ev.get('source', 'MANUAL')}

    def _ev_payment_edit(self, ev):
        p = self.payments[ev['payment']]
        if p['source'] != 'MANUAL':
            raise FixtureError(f'{ev["payment"]}: only MANUAL payments can be edited')
        if 'amount' in ev:
            new = r2(D(ev['amount']))
            if new > self.balance(p['invoice']) + p['amount'] and not ev.get('allow_overpayment'):
                raise FixtureError(f'{ev["payment"]}: edit exceeds balance')
            p['amount'] = new
        if 'payment_date' in ev:
            p['date'] = d(ev['payment_date'])

    def _ev_payment_delete(self, ev):
        if self.payments[ev['payment']]['source'] != 'MANUAL':
            raise FixtureError(f'{ev["payment"]}: only MANUAL payments can be deleted')
        del self.payments[ev['payment']]

    def _credited_lines(self, inv_id):
        out = {}
        for c in self.credit_notes.values():
            if c['invoice'] != inv_id or c['status'] != 'ISSUED':
                continue
            for l in c['lines']:
                if l['invoice_line']:
                    n, v = out.get(l['invoice_line'], (ZERO, ZERO))
                    out[l['invoice_line']] = (n + l['net'], v + l['vat'])
        return out

    def _ev_credit_note(self, ev):
        inv = self._issued(ev['invoice'], ev['id'])
        on = d(ev['issue_date'])
        if on < inv['issue_date']:
            raise FixtureError(f'{ev["id"]}: dated before its invoice')
        credited = self._credited_lines(inv['id'])
        lines = []
        if ev.get('full'):
            for l in inv['lines']:
                cn, cv = credited.get(l['id'], (ZERO, ZERO))
                rn, rv = l['net'] - cn, l['vat'] - cv
                if rn <= 0 and rv <= 0:
                    continue
                lines.append({'invoice_line': l['id'], 'tax_code': l['tax_code'], 'net': rn, 'vat': rv})
            if not lines:
                raise FixtureError(f'{ev["id"]}: nothing left to credit')
        else:
            by_id = {l['id']: l for l in inv['lines']}
            for raw in ev['lines']:
                a = line_amounts(raw, on)
                ref = raw.get('invoice_line')
                if ref:
                    il = by_id[ref]
                    if il['tax_code'] != raw['tax_code']:
                        raise FixtureError(f'{ev["id"]}: tax code differs from {ref}')
                    cn, _ = credited.get(ref, (ZERO, ZERO))
                    if cn + a['net'] > il['net']:
                        raise FixtureError(f'{ev["id"]}: over-credits {ref}')
                    credited[ref] = (cn + a['net'], ZERO)
                lines.append({'invoice_line': ref, 'tax_code': raw['tax_code'], 'net': a['net'], 'vat': a['vat']})
        subtotal = sum((l['net'] for l in lines), ZERO)
        vat = sum((l['vat'] for l in lines), ZERO)
        if subtotal + vat <= 0:
            raise FixtureError(f'{ev["id"]}: must be more than zero')
        if self.credited(inv['id']) + subtotal + vat > inv['total']:
            raise FixtureError(f'{ev["id"]}: credits more than the invoice total')
        self.credit_notes[ev['id']] = {'id': ev['id'], 'invoice': inv['id'], 'date': on, 'status': 'ISSUED',
                                       'lines': lines, 'subtotal': subtotal, 'vat': vat, 'total': subtotal + vat}

    def _ev_credit_note_void(self, ev):
        self.credit_notes[ev['credit_note']]['status'] = 'VOID'

    def _ev_invoice_void(self, ev):
        inv = self._issued(ev['invoice'], ev['id'] if 'id' in ev else 'void')
        if any(p['invoice'] == inv['id'] for p in self.payments.values()):
            raise FixtureError(f'void {inv["id"]}: has payments')
        if self.credited(inv['id']):
            raise FixtureError(f'void {inv["id"]}: has credit notes')
        inv['status'] = 'VOID'

    # -- reports -------------------------------------------------------------
    def issued(self):
        return [i for i in self.invoices.values() if i['status'] == 'ISSUED']

    def period(self, start, end):
        inside = lambda x: start <= x <= end  # noqa: E731
        invs = [i for i in self.issued() if inside(i['issue_date'])]
        cns = [c for c in self.credit_notes.values() if c['status'] == 'ISSUED' and inside(c['date'])]
        by_code = {c: {'net': ZERO, 'vat': ZERO} for c in TAX_CODES}
        for i in invs:
            for l in i['lines']:
                by_code[l['tax_code']]['net'] += l['net']
                by_code[l['tax_code']]['vat'] += l['vat']
        for c in cns:
            for l in c['lines']:
                by_code[l['tax_code']]['net'] -= l['net']
                by_code[l['tax_code']]['vat'] -= l['vat']
        invoiced_excl = sum((i['subtotal'] for i in invs), ZERO)
        invoiced_vat = sum((i['vat'] for i in invs), ZERO)
        credited_excl = sum((c['subtotal'] for c in cns), ZERO)
        credited_vat = sum((c['vat'] for c in cns), ZERO)
        revenue = invoiced_excl - credited_excl
        output_vat = invoiced_vat - credited_vat

        # expenses
        exps = [e for e in self.ds['expenses'] if e['status'] != 'REJECTED' and inside(d(e['expense_date']))]
        gross = vat_in = ZERO
        by_cat = {}
        for e in exps:
            g, v = r2(D(e['amount'])), expense_vat(e)
            gross += g
            vat_in += v
            by_cat[e['category']] = by_cat.get(e['category'], ZERO) + g - v
        exp_excl = gross - vat_in

        # cash
        pays = sorted((p for p in self.payments.values() if inside(p['date'])),
                      key=lambda p: (p['date'], p['seq']))
        received = cash_rev = overpaid = ZERO
        for p in pays:
            inv = self.invoices[p['invoice']]
            prior = sum((q['amount'] for q in self.payments.values() if q['invoice'] == p['invoice']
                         and (q['date'], q['seq']) < (p['date'], p['seq'])), ZERO)
            applicable = max(ZERO, min(p['amount'], inv['total'] - prior))
            received += p['amount']
            overpaid += p['amount'] - applicable
            if inv['total'] > 0:
                cash_rev += r2(applicable * inv['subtotal'] / inv['total'])

        profit_acc = revenue - exp_excl
        profit_cash = cash_rev - exp_excl
        return OrderedDict([
            ('start', start.isoformat()), ('end', end.isoformat()),
            ('invoice_count', len(invs)),
            ('credit_note_count', len(cns)),
            ('invoiced_excl_vat', money(invoiced_excl)),
            ('credited_excl_vat', money(credited_excl)),
            ('revenue_excl_vat', money(revenue)),
            ('invoiced_incl_vat', money(invoiced_excl + invoiced_vat)),
            ('credited_incl_vat', money(credited_excl + credited_vat)),
            ('output_vat', money(output_vat)),
            ('output_by_code', OrderedDict((c, {'net': money(v['net']), 'vat': money(v['vat'])})
                                           for c, v in by_code.items())),
            ('expense_count', len(exps)),
            ('expenses_incl_vat', money(gross)),
            ('input_vat', money(vat_in)),
            ('expenses_excl_vat', money(exp_excl)),
            ('expenses_by_category_excl_vat', OrderedDict(sorted((k, money(v)) for k, v in by_cat.items()))),
            ('net_vat_payable', money(output_vat - vat_in)),
            ('profit_excl_vat', money(profit_acc)),
            ('margin_pct', money(profit_acc / revenue * 100) if revenue else None),
            ('payment_count', len(pays)),
            ('cash_received_incl_vat', money(received)),
            ('cash_revenue_excl_vat', money(cash_rev)),
            ('overpayments', money(overpaid)),
            ('profit_cash_basis_excl_vat', money(profit_cash)),
            ('margin_pct_cash_basis', money(profit_cash / cash_rev * 100) if cash_rev else None),
        ])

    def ageing(self, as_of):
        buckets = {b: ZERO for b in BUCKETS}
        credits = ZERO
        customers = {}
        rows = OrderedDict()
        for inv in self.issued():
            if inv['issue_date'] > as_of:
                continue
            out = inv['total'] - self.paid(inv['id'], as_of) - self.credited(inv['id'], as_of)
            if out < 0:
                credits += -out
                continue
            if out == 0:
                continue
            days = (as_of - inv['due_date']).days
            b = ('current' if days <= 0 else '1_30' if days <= 30 else '31_60' if days <= 60
                 else '61_90' if days <= 90 else '90_plus')
            buckets[b] += out
            c = customers.setdefault(inv['customer'], {k: ZERO for k in BUCKETS + ('total',)})
            c[b] += out
            c['total'] += out
            rows[inv['id']] = OrderedDict([('outstanding', money(out)), ('days_past_due', max(0, days)),
                                           ('bucket', b)])
        return OrderedDict([
            ('buckets', OrderedDict((b, money(buckets[b])) for b in BUCKETS)),
            ('total', money(sum(buckets.values(), ZERO))),
            ('customer_credits', money(credits)),
            ('customers', OrderedDict((cid, OrderedDict((k, money(v)) for k, v in customers[cid].items()))
                                      for cid in sorted(customers))),
            ('invoices', rows),
        ])

    def invoice_final(self, today):
        out = OrderedDict()
        for inv in self.invoices.values():
            paid, credited = self.paid(inv['id']), self.credited(inv['id'])
            bal = inv['total'] - paid - credited
            if inv['status'] == 'DRAFT':
                status = 'DRAFT'
            elif inv['status'] == 'VOID':
                status = 'CANCELLED'
            elif bal <= 0 and (paid > 0 or credited > 0):
                status = 'PAID' if paid > 0 else 'CREDITED'
            elif paid > 0:
                status = 'PARTIALLY_PAID'
            elif inv['due_date'] < today:
                status = 'OVERDUE'
            else:
                status = 'SENT'
            out[inv['id']] = OrderedDict([
                ('due_date', inv['due_date'].isoformat()), ('terms_days', inv['terms_days']),
                ('subtotal', money(inv['subtotal'])), ('discount', money(inv['discount'])),
                ('vat_amount', money(inv['vat'])), ('total_amount', money(inv['total'])),
                ('paid_amount', money(paid)), ('credited_amount', money(credited)),
                ('balance', money(bal)), ('status', status),
                ('lines', [OrderedDict([('net', money(l['net'])), ('vat', money(l['vat'])),
                                        ('total', money(l['total']))]) for l in inv['lines']]),
            ])
        return out

    def credit_note_final(self):
        return OrderedDict((c['id'], OrderedDict([
            ('status', c['status']), ('subtotal', money(c['subtotal'])), ('vat_amount', money(c['vat'])),
            ('total_amount', money(c['total']))])) for c in self.credit_notes.values())


def expense_vat(e):
    if e.get('vat_amount') not in (None, ''):
        v = r2(D(e['vat_amount']))
        if e['tax_code'] != 'STANDARD' and v != 0:
            raise FixtureError(f'{e["id"]}: {e["tax_code"]} carries no VAT')
        return v
    if e['tax_code'] != 'STANDARD':
        return ZERO
    return r2(D(e['amount']) * 15 / 115)


def compute_expected(ds):
    book = Book(ds)
    periods = OrderedDict()
    for p in ds['periods']:
        periods[p['key']] = book.period(d(p['start']), d(p['end']))
    return OrderedDict([
        ('generated_by', 'core/tests/golden_reference.py'),
        ('periods', periods),
        ('ageing', OrderedDict((a, book.ageing(d(a))) for a in ds['ageing_as_of'])),
        ('invoices', book.invoice_final(d(ds['status_as_of']))),
        ('credit_notes', book.credit_note_final()),
        ('expenses', OrderedDict((e['id'], OrderedDict([
            ('amount', money(D(e['amount']))), ('vat_amount', money(expense_vat(e))),
            ('net_amount', money(D(e['amount']) - expense_vat(e)))])) for e in ds['expenses'])),
    ])


def load(path):
    with open(path) as f:
        return json.load(f, object_pairs_hook=OrderedDict)


def freeze(path):
    ds = load(path)
    ds['expected'] = compute_expected(ds)
    with open(path, 'w') as f:
        json.dump(ds, f, indent=2)
        f.write('\n')
    return ds


if __name__ == '__main__':  # pragma: no cover
    if len(sys.argv) == 3 and sys.argv[1] == '--freeze':
        freeze(sys.argv[2])
        print('expected block frozen into', sys.argv[2])
    else:
        print(json.dumps(compute_expected(load(sys.argv[1]))['periods'], indent=2))
