"""Phrase fixtures for voice / natural-language quoting (English, Afrikaans,
mixed "Afrikaans-English", typos and STT errors).

Each case: `text`, `lang` (en/af/mixed — what a speaker would call it),
`expect` (fields the parser must fill, with exact values), `absent` (fields
it must NOT fill — "never invent"), and optionally `customers` and `llm`
(a handwritten model response, in the EXTRACTION_SCHEMA shape, used by the
merge tests with the LLM mocked — no real model is ever called).

TODAY is fixed: Thursday 8 October 2026. `vehicle_hint` refers to the
pre-parser's canonical body key (interlink/tautliner/reefer/tipper/...).
"""
from datetime import date

TODAY = date(2026, 10, 8)  # a Thursday

CUSTOMERS = [
    {"id": 11, "name": "Nampak Ltd"},
    {"id": 12, "name": "Shoprite Holdings"},
    {"id": 13, "name": "Bokomo Foods"},
    {"id": 14, "name": "Afrisam (Pty) Ltd"},
]

CASES = [
    {"id": "en_basic", "lang": "en",
     "text": "28 tons of steel coils from Johannesburg to Durban tomorrow",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban", "pickup_date": "2026-10-09"},
     "absent": ["trip_type", "return_load_booked", "customer_id"]},
    {"id": "af_basic_numbers", "lang": "af",
     "text": "agt-en-twintig ton staalrolle van Joburg na Durban môre",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban", "pickup_date": "2026-10-09"}},
    {"id": "af_superlink_vrydag", "lang": "af",
     "text": "Ek het 'n superlink nodig, 34 ton mielies van Bloemfontein na Kaapstad, Vrydag",
     "expect": {"weight": 34000, "cargo_description": "maize", "pickup_location": "Bloemfontein",
                "delivery_location": "Cape Town", "pickup_date": "2026-10-09", "vehicle_hint": "interlink"}},
    {"id": "en_reefer_return_load", "lang": "en",
     "text": "Need a reefer, 12 ton frozen chicken, Durban to Joburg, return load booked",
     "expect": {"weight": 12000, "cargo_description": "frozen chicken", "pickup_location": "Durban",
                "delivery_location": "Johannesburg", "return_load_booked": True, "trip_type": "ONE_WAY",
                "vehicle_hint": "reefer"}},
    {"id": "af_leeg_terug", "lang": "af",
     "text": "Twintig ton sement van Pretoria na Polokwane, leeg terug",
     "expect": {"weight": 20000, "cargo_description": "cement", "pickup_location": "Pretoria",
                "delivery_location": "Polokwane", "return_load_booked": False, "trip_type": "ONE_WAY"}},
    {"id": "af_heen_en_terug", "lang": "af",
     "text": "Heen en terug Kaapstad na Gqeberha, 30 ton bier",
     "expect": {"trip_type": "ROUND_TRIP", "pickup_location": "Cape Town", "delivery_location": "Gqeberha",
                "weight": 30000, "cargo_description": "beer"},
     "absent": ["return_load_booked"]},
    {"id": "en_tautliner_crossborder_via", "lang": "en",
     "text": "Quote for a tautliner Joburg to Windhoek via Upington, 22 tons pallets, cross border",
     "expect": {"vehicle_hint": "tautliner", "pickup_location": "Johannesburg", "delivery_location": "Windhoek",
                "stops": ["Upington"], "weight": 22000, "cargo_description": "pallets", "international": True}},
    {"id": "af_8ton_trok_is_truck_size", "lang": "af",
     "text": "van PE na Oos-Londen, 8 ton trok, meubels, Maandag",
     "expect": {"pickup_location": "Gqeberha", "delivery_location": "East London", "cargo_description": "furniture",
                "pickup_date": "2026-10-12", "vehicle_hint": "rigid"},
     "absent": ["weight"]},
    {"id": "en_kg_deliver_friday", "lang": "en",
     "text": "Load 15000 kg of maize in Kroonstad, deliver to Richardsbaai on Friday",
     "expect": {"weight": 15000, "cargo_description": "maize", "pickup_location": "Kroonstad",
                "delivery_location": "Richards Bay", "delivery_date": "2026-10-09"},
     "absent": ["pickup_date"]},
    {"id": "af_tipper_oormore", "lang": "af",
     "text": "Wipbak, 30 ton sand, Vereeniging na Rustenburg, oormôre",
     "expect": {"vehicle_hint": "tipper", "weight": 30000, "cargo_description": "sand",
                "pickup_location": "Vereeniging", "delivery_location": "Rustenburg", "pickup_date": "2026-10-10"}},
    {"id": "af_retoervrag", "lang": "af",
     "text": "Retoervrag is gereel. 26 ton hout van Mbombela na Durban",
     "expect": {"return_load_booked": True, "trip_type": "ONE_WAY", "weight": 26000, "cargo_description": "timber",
                "pickup_location": "Mbombela", "delivery_location": "Durban"}},
    {"id": "en_oneway_zulu_names", "lang": "en",
     "text": "one way, 5 ton parcels, Jozi to eThekwini, Tuesday",
     "expect": {"trip_type": "ONE_WAY", "weight": 5000, "cargo_description": "parcels",
                "pickup_location": "Johannesburg", "delivery_location": "Durban", "pickup_date": "2026-10-13"}},
    {"id": "af_border_koelwa", "lang": "af",
     "text": "Kaapstad na Windhoek oor Vioolsdrif, 28 ton druiwe, koelwa",
     "expect": {"pickup_location": "Cape Town", "delivery_location": "Windhoek", "border_post": "Vioolsdrif",
                "international": True, "weight": 28000, "cargo_description": "grapes", "vehicle_hint": "reefer"}},
    {"id": "en_border_flatbed", "lang": "en",
     "text": "From Joburg to Gaborone through Kopfontein, 18 tons chrome, flatbed",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Gaborone", "border_post": "Kopfontein",
                "international": True, "weight": 18000, "cargo_description": "chrome ore", "vehicle_hint": "flatbed"}},
    {"id": "typo_place_names", "lang": "en",
     "text": "Johannesberg to Bloemfontain 20 ton steel",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Bloemfontein", "weight": 20000,
                "cargo_description": "steel"}},
    {"id": "official_names_next_monday", "lang": "en",
     "text": "Tshwane to Mangaung, 10 tonnes fertilizer, next Monday",
     "expect": {"pickup_location": "Pretoria", "delivery_location": "Bloemfontein", "weight": 10000,
                "cargo_description": "fertiliser", "pickup_date": "2026-10-12"}},
    {"id": "af_kilo_words_george", "lang": "af",
     "text": "twee duisend vyf honderd kilo palette van Bellville na George",
     "expect": {"weight": 2500, "cargo_description": "pallets", "pickup_location": "Bellville",
                "delivery_location": "George"}},
    {"id": "af_beitbridge_toe", "lang": "af",
     "text": "Ons het 'n vrag van Polokwane na Musina en dan Beitbridge toe, 32 ton, superlink",
     "expect": {"pickup_location": "Polokwane", "delivery_location": "Musina", "border_post": "Beitbridge",
                "international": True, "weight": 32000, "vehicle_hint": "interlink"},
     "absent": ["cargo_description"]},
    {"id": "en_dash_route_nights", "lang": "en",
     "text": "Need a quote: Durban - Lusaka, 30t copper, 3 nights",
     "expect": {"pickup_location": "Durban", "delivery_location": "Lusaka", "international": True,
                "weight": 30000, "cargo_description": "copper", "driver_nights": 3}},
    {"id": "en_empty_back_fuel", "lang": "en",
     "text": "Can you price 34 ton coal from Witbank to Richards Bay, empty back, diesel at R23,50 a litre",
     "expect": {"weight": 34000, "cargo_description": "coal", "pickup_location": "Witbank",
                "delivery_location": "Richards Bay", "return_load_booked": False, "trip_type": "ONE_WAY",
                "fuel_price_override": 23.5}},
    {"id": "af_customer_no_marker", "lang": "af", "customers": CUSTOMERS,
     "text": "Hallo, ek soek 'n prys vir Nampak, 20 palette koeldrank Kaapstad na Paarl",
     "expect": {"customer_id": 11, "customer_name": "Nampak Ltd", "cargo_description": "beverages on pallets",
                "pickup_location": "Cape Town", "delivery_location": "Paarl"},
     "absent": ["weight"]},
    {"id": "en_client_is", "lang": "en", "customers": CUSTOMERS,
     "text": "client is Shoprite, 14 ton groceries Midrand to Polokwane Friday",
     "expect": {"customer_id": 12, "customer_name": "Shoprite Holdings", "weight": 14000,
                "cargo_description": "groceries", "pickup_location": "Midrand", "delivery_location": "Polokwane",
                "pickup_date": "2026-10-09"}},
    {"id": "stt_fillers_ordinal", "lang": "en",
     "text": "uh so we've got um twenty two tons of steel going from germiston to durbs on the fourteenth",
     "expect": {"weight": 22000, "cargo_description": "steel", "pickup_location": "Germiston",
                "delivery_location": "Durban", "pickup_date": "2026-10-14"}},
    {"id": "mixed_codeswitch", "lang": "mixed",
     "text": "Ons moet 25 ton maize van Joburg af haal en dit na Kaapstad deliver, Thursday",
     "expect": {"weight": 25000, "cargo_description": "maize", "pickup_location": "Johannesburg",
                "delivery_location": "Cape Town", "delivery_date": "2026-10-15"}},
    {"id": "stt_spelled_letters_homophone", "lang": "en",
     "text": "28 tons steal coils from J H B to D B N",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban"}},
    {"id": "af_lowbed_kwotasie", "lang": "af",
     "text": "Kan jy my 'n kwotasie gee vir 'n lowbed, 40 ton masjinerie van Secunda na Saldanha",
     "expect": {"vehicle_hint": "lowbed", "weight": 40000, "cargo_description": "machinery",
                "pickup_location": "Secunda", "delivery_location": "Saldanha"},
     "absent": ["customer_id"]},
    {"id": "en_round_trip_and_back", "lang": "en",
     "text": "Round trip Cape Town to Worcester and back, 12 ton apples, Saturday",
     "expect": {"trip_type": "ROUND_TRIP", "pickup_location": "Cape Town", "delivery_location": "Worcester",
                "weight": 12000, "cargo_description": "apples", "pickup_date": "2026-10-10"}},
    {"id": "en_ldv_kg", "lang": "en",
     "text": "1500 kg electronics Centurion to Bloem tomorrow, LDV",
     "expect": {"weight": 1500, "cargo_description": "electronics", "pickup_location": "Centurion",
                "delivery_location": "Bloemfontein", "pickup_date": "2026-10-09", "vehicle_hint": "ldv"}},
    {"id": "af_gordynkant_maseru_nagte", "lang": "af",
     "text": "Gordynkant, 30 ton suiker van Durban na Maseru, Maseru Bridge, 2 nagte",
     "expect": {"vehicle_hint": "tautliner", "weight": 30000, "cargo_description": "sugar",
                "pickup_location": "Durban", "delivery_location": "Maseru", "border_post": "Maseru Bridge",
                "international": True, "driver_nights": 2}},
    {"id": "en_numeric_dates_tanker", "lang": "en",
     "text": "Pick up 15/10 in Rustenburg, deliver Upington by 17/10, 24 ton chemicals, tanker",
     "expect": {"pickup_date": "2026-10-15", "delivery_date": "2026-10-17", "pickup_location": "Rustenburg",
                "delivery_location": "Upington", "weight": 24000, "cargo_description": "chemicals",
                "vehicle_hint": "tanker"}},
    {"id": "af_namibia_nakop", "lang": "af",
     "text": "vrag van Upington na Keetmanshoop via Nakop, 20 ton druiwe",
     "expect": {"pickup_location": "Upington", "delivery_location": "Keetmanshoop", "border_post": "Nakop",
                "international": True, "weight": 20000, "cargo_description": "grapes"}},
    {"id": "en_only_date", "lang": "en",
     "text": "need a truck tomorrow",
     "expect": {"pickup_date": "2026-10-09"},
     "absent": ["pickup_location", "delivery_location", "weight", "cargo_description", "vehicle_type"]},
    {"id": "greeting_only", "lang": "en",
     "text": "hi there",
     "expect": {},
     "absent": ["pickup_location", "delivery_location", "weight", "cargo_description", "pickup_date"]},
    {"id": "insane_weight_rejected", "lang": "en",
     "text": "500 ton of sand Joburg to Pretoria",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Pretoria", "cargo_description": "sand"},
     "absent": ["weight"], "not_understood": True},
    {"id": "af_laai_aflaai_lebombo", "lang": "af",
     "text": "Laai môre in Komatipoort, aflaai in Maputo, 30 ton suiker, oor Lebombo",
     "expect": {"pickup_location": "Komatipoort", "delivery_location": "Maputo", "pickup_date": "2026-10-09",
                "border_post": "Lebombo", "international": True, "weight": 30000, "cargo_description": "sugar"}},
    {"id": "en_pallet_count_valid_for", "lang": "en",
     "text": "From Isando to City Deep, 6 pallets, 3 ton, tautliner, valid for 7 days",
     "expect": {"pickup_location": "Isando", "delivery_location": "City Deep", "weight": 3000,
                "cargo_description": "pallets", "vehicle_hint": "tautliner", "valid_until": "2026-10-15"}},
    {"id": "af_daar_wees_teen_woensdag", "lang": "af",
     "text": "Joburg na Harare, 34 ton, 'n superlink, moet daar wees teen Woensdag",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Harare", "international": True,
                "weight": 34000, "vehicle_hint": "interlink", "delivery_date": "2026-10-14"},
     "absent": ["pickup_date"]},
    {"id": "stt_misheard_places_empty_return", "lang": "en",
     "text": "twenty eight ton steel coils from Pietermaritsburg to Kaapsted, empty return",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Pietermaritzburg",
                "delivery_location": "Cape Town", "return_load_booked": False, "trip_type": "ONE_WAY"}},
    {"id": "af_toe_postposition_comma_decimal", "lang": "af",
     "text": "Ek wil 12,5 ton vrugte Kaapstad toe vat van Upington af, Dinsdag",
     "expect": {"weight": 12500, "cargo_description": "fruit", "pickup_location": "Upington",
                "delivery_location": "Cape Town", "pickup_date": "2026-10-13"}},
    {"id": "mixed_tomorrow_af_superlink_backload", "lang": "mixed",
     "text": "Môre a superlink van Richards Bay na Joburg, 34 ton chrome, ons het 'n backload",
     "expect": {"pickup_date": "2026-10-09", "vehicle_hint": "interlink", "pickup_location": "Richards Bay",
                "delivery_location": "Johannesburg", "weight": 34000, "cargo_description": "chrome ore",
                "return_load_booked": True, "trip_type": "ONE_WAY"}},
]

# Handwritten model responses (EXTRACTION_SCHEMA shape) for the merge tests.
# They deliberately include realistic model mistakes: Afrikaans number words
# mis-converted, a swapped route, an invented/insane value — the merge layer
# must keep the deterministic value where the rules are sure, and validation
# must drop anything out of range.
def llm_payload(**kw):
    base = {
        "pickup_location": "", "delivery_location": "", "stops": [], "weight_kg": 0, "vehicle_type": "",
        "customer_name": "", "cargo_description": "", "pickup_date": "", "delivery_date": "",
        "valid_until": "", "trip_type": "", "return_load_booked": "", "international": "", "border_post": "",
        "driver_nights": 0, "fuel_price_override": 0, "not_understood": [], "reply": "",
        "field_confidence": {},
    }
    base.update(kw)
    return base


LLM_CASES = {
    # LLM mis-converts "agt-en-twintig" to 20 t — the rules (0.95) win, confidence drops.
    "af_basic_numbers": llm_payload(
        pickup_location="Johannesburg", delivery_location="Durban", weight_kg=20000,
        cargo_description="steel coils", pickup_date="2026-10-09",
        reply="Reg so: staalrolle van Johannesburg na Durban, môre."),
    # LLM agrees with everything — confidence goes up.
    "en_basic": llm_payload(
        pickup_location="Johannesburg", delivery_location="Durban", weight_kg=28000,
        cargo_description="steel coils", pickup_date="2026-10-09",
        reply="Got it: 28 t steel coils, Johannesburg to Durban, tomorrow."),
    # LLM returns an insane weight and a malformed date — validation must drop both.
    "greeting_only": llm_payload(weight_kg=9_000_000, pickup_date="next week", trip_type="SOMETIMES",
                                 reply="Hi! Describe the load and I'll quote it."),
}


# Held-out phrases: written after the parser was tuned on CASES and never
# tuned against, so their score is the honest generalisation number.
HELDOUT = [
    {"id": "h1", "lang": "en", "text": "Got 30 tons of wheat to move from Bethlehem to Durban next Wednesday",
     "expect": {"weight": 30000, "cargo_description": "wheat", "pickup_location": "Bethlehem",
                "delivery_location": "Durban", "pickup_date": "2026-10-14"}},
    {"id": "h2", "lang": "af", "text": "Hoeveel vir vyftien ton kunsmis van Sasolburg na Kimberley?",
     "expect": {"weight": 15000, "cargo_description": "fertiliser", "pickup_location": "Sasolburg",
                "delivery_location": "Kimberley"}},
    {"id": "h3", "lang": "af", "text": "Koelwa van Kaapstad na Johannesburg, 18 ton vleis, Saterdag oplaai",
     "expect": {"vehicle_hint": "reefer", "pickup_location": "Cape Town", "delivery_location": "Johannesburg",
                "weight": 18000, "cargo_description": "meat", "pickup_date": "2026-10-10"}},
    {"id": "h4", "lang": "en", "text": "flatbed for 25t steel beams Vanderbijlpark to Port Elizabeth, one way",
     "expect": {"vehicle_hint": "flatbed", "weight": 25000, "cargo_description": "steel beams",
                "pickup_location": "Vanderbijlpark", "delivery_location": "Gqeberha", "trip_type": "ONE_WAY"}},
    {"id": "h5", "lang": "mixed", "text": "Joburg na Polokwane en back, loaded both ways, 20 ton cement",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Polokwane", "trip_type": "ROUND_TRIP",
                "weight": 20000, "cargo_description": "cement"}},
    {"id": "h6", "lang": "af", "text": "Ons gaan leeg terug kom van Upington af, 10 ton druiwe na Kaapstad",
     "expect": {"return_load_booked": False, "pickup_location": "Upington", "delivery_location": "Cape Town",
                "weight": 10000, "cargo_description": "grapes"}},
    {"id": "h7", "lang": "en", "text": "Harare from Joburg via Beitbridge, 34t fertiliser, superlink, 4 nights",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Harare", "border_post": "Beitbridge",
                "international": True, "weight": 34000, "cargo_description": "fertiliser",
                "vehicle_hint": "interlink", "driver_nights": 4}},
    {"id": "h8", "lang": "af", "text": "drie en dertig ton steenkool, Ermelo na Richardsbaai, more oggend",
     "expect": {"weight": 33000, "cargo_description": "coal", "pickup_location": "Ermelo",
                "delivery_location": "Richards Bay", "pickup_date": "2026-10-09"}},
    {"id": "h9", "lang": "en", "text": "8000kg furniture Pretoria to George, deliver by the 20th",
     "expect": {"weight": 8000, "cargo_description": "furniture", "pickup_location": "Pretoria",
                "delivery_location": "George", "delivery_date": "2026-10-20"}},
    {"id": "h10", "lang": "en", "text": "Tanker, diesel from Durban to Lubumbashi, 35000 litres",
     "expect": {"vehicle_hint": "tanker", "pickup_location": "Durban", "delivery_location": "Lubumbashi",
                "international": True},
     "absent": ["weight", "fuel_price_override"]},
    {"id": "h11", "lang": "af", "text": "Tautliner asseblief, Bloem na Durban, 22 ton meel, Donderdag",
     "expect": {"vehicle_hint": "tautliner", "pickup_location": "Bloemfontein", "delivery_location": "Durban",
                "weight": 22000, "cargo_description": "flour", "pickup_date": "2026-10-15"}},
    {"id": "h12", "lang": "en", "text": "Need a side tipper 32 ton gravel Brits to Rustenburg today",
     "expect": {"vehicle_hint": "tipper", "weight": 32000, "cargo_description": "aggregate",
                "pickup_location": "Brits", "delivery_location": "Rustenburg", "pickup_date": "2026-10-08"}},
    {"id": "h13", "lang": "mixed", "text": "Die client is Bokomo, 15 ton flour Paarl to Bellville",
     "customers": CUSTOMERS,
     "expect": {"customer_id": 13, "weight": 15000, "cargo_description": "flour", "pickup_location": "Paarl",
                "delivery_location": "Bellville"}},
    {"id": "h14", "lang": "en", "text": "Cape Town to Walvis Bay 28 tons wine return load sorted",
     "expect": {"pickup_location": "Cape Town", "delivery_location": "Walvis Bay", "international": True,
                "weight": 28000, "cargo_description": "wine", "return_load_booked": True}},
    {"id": "h15", "lang": "af", "text": "nege ton hoender bevrore, Rustenburg na Mahikeng, Vrydag aflewer",
     "expect": {"weight": 9000, "pickup_location": "Rustenburg", "delivery_location": "Mahikeng",
                "delivery_date": "2026-10-09"}},
    {"id": "h16", "lang": "en", "text": "pick up in nelspruit tomorrow drop in maputo 12 tons citrus",
     "expect": {"pickup_location": "Mbombela", "delivery_location": "Maputo", "pickup_date": "2026-10-09",
                "weight": 12000, "cargo_description": "citrus", "international": True}},
    {"id": "h17", "lang": "en", "text": "Twenty-four tonnes maize meal, Klerksdorp to Gaborone, cross-border",
     "expect": {"weight": 24000, "cargo_description": "maize", "pickup_location": "Klerksdorp",
                "delivery_location": "Gaborone", "international": True}},
    {"id": "h18", "lang": "af", "text": "Van Gqeberha na Oos Londen met 'n stop in Makhanda, 6 ton pakkies",
     "expect": {"pickup_location": "Gqeberha", "delivery_location": "East London", "stops": ["Makhanda"],
                "weight": 6000, "cargo_description": "parcels"}},
    {"id": "h19", "lang": "en", "text": "how much for a load to Durban",
     "expect": {"delivery_location": "Durban"}, "absent": ["pickup_location", "weight"]},
    {"id": "h20", "lang": "en", "text": "34 ton chrome Steelpoort to Maputo port via Lebombo",
     "expect": {"weight": 34000, "cargo_description": "chrome ore", "delivery_location": "Maputo",
                "border_post": "Lebombo", "international": True}},
]
