"""Phrase fixtures for voice / natural-language quoting (English, Afrikaans,
mixed "Afrikaans-English", typos and STT errors).

Each case: `text`, `lang` (en/af/mixed — what a speaker would call it),
`expect` (fields the parser must fill, with exact values), `absent` (fields
it must NOT fill — "never invent"), and optionally `customers` and `llm`
(a handwritten model response, in the EXTRACTION_SCHEMA shape, used by the
merge tests with the LLM mocked — no real model is ever called).

TODAY is fixed: Thursday 8 October 2026. `vehicle_hint` refers to the
pre-parser's canonical body key (interlink/tautliner/reefer/tipper/...).
"""
from datetime import date

TODAY = date(2026, 10, 8)  # a Thursday

CUSTOMERS = [
    {"id": 11, "name": "Nampak Ltd"},
    {"id": 12, "name": "Shoprite Holdings"},
    {"id": 13, "name": "Bokomo Foods"},
    {"id": 14, "name": "Afrisam (Pty) Ltd"},
]

CASES = [
    {"id": "en_basic", "lang": "en",
     "text": "28 tons of steel coils from Johannesburg to Durban tomorrow",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban", "pickup_date": "2026-10-09"},
     "absent": ["trip_type", "return_load_booked", "customer_id"]},
    {"id": "af_basic_numbers", "lang": "af",
     "text": "agt-en-twintig ton staalrolle van Joburg na Durban môre",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban", "pickup_date": "2026-10-09"}},
    {"id": "af_superlink_vrydag", "lang": "af",
     "text": "Ek het 'n superlink nodig, 34 ton mielies van Bloemfontein na Kaapstad, Vrydag",
     "expect": {"weight": 34000, "cargo_description": "maize", "pickup_location": "Bloemfontein",
                "delivery_location": "Cape Town", "pickup_date": "2026-10-09", "vehicle_hint": "interlink"}},
    {"id": "en_reefer_return_load", "lang": "en",
     "text": "Need a reefer, 12 ton frozen chicken, Durban to Joburg, return load booked",
     "expect": {"weight": 12000, "cargo_description": "frozen chicken", "pickup_location": "Durban",
                "delivery_location": "Johannesburg", "return_load_booked": True, "trip_type": "ONE_WAY",
                "vehicle_hint": "reefer"}},
    {"id": "af_leeg_terug", "lang": "af",
     "text": "Twintig ton sement van Pretoria na Polokwane, leeg terug",
     "expect": {"weight": 20000, "cargo_description": "cement", "pickup_location": "Pretoria",
                "delivery_location": "Polokwane", "return_load_booked": False, "trip_type": "ONE_WAY"}},
    {"id": "af_heen_en_terug", "lang": "af",
     "text": "Heen en terug Kaapstad na Gqeberha, 30 ton bier",
     "expect": {"trip_type": "ROUND_TRIP", "pickup_location": "Cape Town", "delivery_location": "Gqeberha",
                "weight": 30000, "cargo_description": "beer"},
     "absent": ["return_load_booked"]},
    {"id": "en_tautliner_crossborder_via", "lang": "en",
     "text": "Quote for a tautliner Joburg to Windhoek via Upington, 22 tons pallets, cross border",
     "expect": {"vehicle_hint": "tautliner", "pickup_location": "Johannesburg", "delivery_location": "Windhoek",
                "stops": ["Upington"], "weight": 22000, "cargo_description": "pallets", "international": True}},
    {"id": "af_8ton_trok_is_truck_size", "lang": "af",
     "text": "van PE na Oos-Londen, 8 ton trok, meubels, Maandag",
     "expect": {"pickup_location": "Gqeberha", "delivery_location": "East London", "cargo_description": "furniture",
                "pickup_date": "2026-10-12", "vehicle_hint": "rigid"},
     "absent": ["weight"]},
    {"id": "en_kg_deliver_friday", "lang": "en",
     "text": "Load 15000 kg of maize in Kroonstad, deliver to Richardsbaai on Friday",
     "expect": {"weight": 15000, "cargo_description": "maize", "pickup_location": "Kroonstad",
                "delivery_location": "Richards Bay", "delivery_date": "2026-10-09"},
     "absent": ["pickup_date"]},
    {"id": "af_tipper_oormore", "lang": "af",
     "text": "Wipbak, 30 ton sand, Vereeniging na Rustenburg, oormôre",
     "expect": {"vehicle_hint": "tipper", "weight": 30000, "cargo_description": "sand",
                "pickup_location": "Vereeniging", "delivery_location": "Rustenburg", "pickup_date": "2026-10-10"}},
    {"id": "af_retoervrag", "lang": "af",
     "text": "Retoervrag is gereel. 26 ton hout van Mbombela na Durban",
     "expect": {"return_load_booked": True, "trip_type": "ONE_WAY", "weight": 26000, "cargo_description": "timber",
                "pickup_location": "Mbombela", "delivery_location": "Durban"}},
    {"id": "en_oneway_zulu_names", "lang": "en",
     "text": "one way, 5 ton parcels, Jozi to eThekwini, Tuesday",
     "expect": {"trip_type": "ONE_WAY", "weight": 5000, "cargo_description": "parcels",
                "pickup_location": "Johannesburg", "delivery_location": "Durban", "pickup_date": "2026-10-13"}},
    {"id": "af_border_koelwa", "lang": "af",
     "text": "Kaapstad na Windhoek oor Vioolsdrif, 28 ton druiwe, koelwa",
     "expect": {"pickup_location": "Cape Town", "delivery_location": "Windhoek", "border_post": "Vioolsdrif / Noordoewer",
                "international": True, "weight": 28000, "cargo_description": "grapes", "vehicle_hint": "reefer"}},
    {"id": "en_border_flatbed", "lang": "en",
     "text": "From Joburg to Gaborone through Kopfontein, 18 tons chrome, flatbed",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Gaborone", "border_post": "Kopfontein / Tlokweng",
                "international": True, "weight": 18000, "cargo_description": "chrome", "vehicle_hint": "flatbed"}},
    {"id": "typo_place_names", "lang": "en",
     "text": "Johannesberg to Bloemfontain 20 ton steel",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Bloemfontein", "weight": 20000,
                "cargo_description": "steel"}},
    {"id": "official_names_next_monday", "lang": "en",
     "text": "Tshwane to Mangaung, 10 tonnes fertilizer, next Monday",
     "expect": {"pickup_location": "Pretoria", "delivery_location": "Bloemfontein", "weight": 10000,
                "cargo_description": "fertiliser", "pickup_date": "2026-10-12"}},
    {"id": "af_kilo_words_george", "lang": "af",
     "text": "twee duisend vyf honderd kilo palette van Bellville na George",
     "expect": {"weight": 2500, "cargo_description": "pallets", "pickup_location": "Bellville",
                "delivery_location": "George"}},
    {"id": "af_beitbridge_toe", "lang": "af",
     "text": "Ons het 'n vrag van Polokwane na Musina en dan Beitbridge toe, 32 ton, superlink",
     "expect": {"pickup_location": "Polokwane", "delivery_location": "Musina", "border_post": "Beitbridge",
                "international": True, "weight": 32000, "vehicle_hint": "interlink"},
     "absent": ["cargo_description"]},
    {"id": "en_dash_route_nights", "lang": "en",
     "text": "Need a quote: Durban - Lusaka, 30t copper, 3 nights",
     "expect": {"pickup_location": "Durban", "delivery_location": "Lusaka", "international": True,
                "weight": 30000, "cargo_description": "copper", "driver_nights": 3}},
    {"id": "en_empty_back_fuel", "lang": "en",
     "text": "Can you price 34 ton coal from Witbank to Richards Bay, empty back, diesel at R23,50 a litre",
     "expect": {"weight": 34000, "cargo_description": "coal", "pickup_location": "Witbank",
                "delivery_location": "Richards Bay", "return_load_booked": False, "trip_type": "ONE_WAY",
                "fuel_price_override": 23.5}},
    {"id": "af_customer_no_marker", "lang": "af", "customers": CUSTOMERS,
     "text": "Hallo, ek soek 'n prys vir Nampak, 20 palette koeldrank Kaapstad na Paarl",
     "expect": {"customer_id": 11, "customer_name": "Nampak Ltd", "cargo_description": "beverages on pallets",
                "pickup_location": "Cape Town", "delivery_location": "Paarl"},
     "absent": ["weight"]},
    {"id": "en_client_is", "lang": "en", "customers": CUSTOMERS,
     "text": "client is Shoprite, 14 ton groceries Midrand to Polokwane Friday",
     "expect": {"customer_id": 12, "customer_name": "Shoprite Holdings", "weight": 14000,
                "cargo_description": "groceries", "pickup_location": "Midrand", "delivery_location": "Polokwane",
                "pickup_date": "2026-10-09"}},
    {"id": "stt_fillers_ordinal", "lang": "en",
     "text": "uh so we've got um twenty two tons of steel going from germiston to durbs on the fourteenth",
     "expect": {"weight": 22000, "cargo_description": "steel", "pickup_location": "Germiston",
                "delivery_location": "Durban", "pickup_date": "2026-10-14"}},
    {"id": "mixed_codeswitch", "lang": "mixed",
     "text": "Ons moet 25 ton maize van Joburg af haal en dit na Kaapstad deliver, Thursday",
     "expect": {"weight": 25000, "cargo_description": "maize", "pickup_location": "Johannesburg",
                "delivery_location": "Cape Town", "delivery_date": "2026-10-15"}},
    {"id": "stt_spelled_letters_homophone", "lang": "en",
     "text": "28 tons steal coils from J H B to D B N",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Johannesburg",
                "delivery_location": "Durban"}},
    {"id": "af_lowbed_kwotasie", "lang": "af",
     "text": "Kan jy my 'n kwotasie gee vir 'n lowbed, 40 ton masjinerie van Secunda na Saldanha",
     "expect": {"vehicle_hint": "lowbed", "weight": 40000, "cargo_description": "machinery",
                "pickup_location": "Secunda", "delivery_location": "Saldanha"},
     "absent": ["customer_id"]},
    {"id": "en_round_trip_and_back", "lang": "en",
     "text": "Round trip Cape Town to Worcester and back, 12 ton apples, Saturday",
     "expect": {"trip_type": "ROUND_TRIP", "pickup_location": "Cape Town", "delivery_location": "Worcester",
                "weight": 12000, "cargo_description": "apples", "pickup_date": "2026-10-10"}},
    {"id": "en_ldv_kg", "lang": "en",
     "text": "1500 kg electronics Centurion to Bloem tomorrow, LDV",
     "expect": {"weight": 1500, "cargo_description": "electronics", "pickup_location": "Centurion",
                "delivery_location": "Bloemfontein", "pickup_date": "2026-10-09", "vehicle_hint": "ldv"}},
    {"id": "af_gordynkant_maseru_nagte", "lang": "af",
     "text": "Gordynkant, 30 ton suiker van Durban na Maseru, Maseru Bridge, 2 nagte",
     "expect": {"vehicle_hint": "tautliner", "weight": 30000, "cargo_description": "sugar",
                "pickup_location": "Durban", "delivery_location": "Maseru", "border_post": "Maseru Bridge",
                "international": True, "driver_nights": 2}},
    {"id": "en_numeric_dates_tanker", "lang": "en",
     "text": "Pick up 15/10 in Rustenburg, deliver Upington by 17/10, 24 ton chemicals, tanker",
     "expect": {"pickup_date": "2026-10-15", "delivery_date": "2026-10-17", "pickup_location": "Rustenburg",
                "delivery_location": "Upington", "weight": 24000, "cargo_description": "chemicals",
                "vehicle_hint": "tanker"}},
    {"id": "af_namibia_nakop", "lang": "af",
     "text": "vrag van Upington na Keetmanshoop via Nakop, 20 ton druiwe",
     "expect": {"pickup_location": "Upington", "delivery_location": "Keetmanshoop", "border_post": "Nakop / Ariamsvlei",
                "international": True, "weight": 20000, "cargo_description": "grapes"}},
    {"id": "en_only_date", "lang": "en",
     "text": "need a truck tomorrow",
     "expect": {"pickup_date": "2026-10-09"},
     "absent": ["pickup_location", "delivery_location", "weight", "cargo_description", "vehicle_type"]},
    {"id": "greeting_only", "lang": "en",
     "text": "hi there",
     "expect": {},
     "absent": ["pickup_location", "delivery_location", "weight", "cargo_description", "pickup_date"]},
    {"id": "insane_weight_rejected", "lang": "en",
     "text": "500 ton of sand Joburg to Pretoria",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Pretoria", "cargo_description": "sand"},
     "absent": ["weight"], "not_understood": True},
    {"id": "af_laai_aflaai_lebombo", "lang": "af",
     "text": "Laai môre in Komatipoort, aflaai in Maputo, 30 ton suiker, oor Lebombo",
     "expect": {"pickup_location": "Komatipoort", "delivery_location": "Maputo", "pickup_date": "2026-10-09",
                "border_post": "Lebombo / Ressano Garcia", "international": True, "weight": 30000, "cargo_description": "sugar"}},
    {"id": "en_pallet_count_valid_for", "lang": "en",
     "text": "From Isando to City Deep, 6 pallets, 3 ton, tautliner, valid for 7 days",
     "expect": {"pickup_location": "Isando", "delivery_location": "City Deep", "weight": 3000,
                "cargo_description": "pallets", "vehicle_hint": "tautliner", "valid_until": "2026-10-15"}},
    {"id": "af_daar_wees_teen_woensdag", "lang": "af",
     "text": "Joburg na Harare, 34 ton, 'n superlink, moet daar wees teen Woensdag",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Harare", "international": True,
                "weight": 34000, "vehicle_hint": "interlink", "delivery_date": "2026-10-14"},
     "absent": ["pickup_date"]},
    {"id": "stt_misheard_places_empty_return", "lang": "en",
     "text": "twenty eight ton steel coils from Pietermaritsburg to Kaapsted, empty return",
     "expect": {"weight": 28000, "cargo_description": "steel coils", "pickup_location": "Pietermaritzburg",
                "delivery_location": "Cape Town", "return_load_booked": False, "trip_type": "ONE_WAY"}},
    {"id": "af_toe_postposition_comma_decimal", "lang": "af",
     "text": "Ek wil 12,5 ton vrugte Kaapstad toe vat van Upington af, Dinsdag",
     "expect": {"weight": 12500, "cargo_description": "fruit", "pickup_location": "Upington",
                "delivery_location": "Cape Town", "pickup_date": "2026-10-13"}},
    {"id": "mixed_tomorrow_af_superlink_backload", "lang": "mixed",
     "text": "Môre a superlink van Richards Bay na Joburg, 34 ton chrome, ons het 'n backload",
     "expect": {"pickup_date": "2026-10-09", "vehicle_hint": "interlink", "pickup_location": "Richards Bay",
                "delivery_location": "Johannesburg", "weight": 34000, "cargo_description": "chrome",
                "return_load_booked": True, "trip_type": "ONE_WAY"}},
]

# Handwritten model responses (EXTRACTION_SCHEMA shape) for the merge tests.
# They deliberately include realistic model mistakes: Afrikaans number words
# mis-converted, a swapped route, an invented/insane value — the merge layer
# must keep the deterministic value where the rules are sure, and validation
# must drop anything out of range.
def llm_payload(**kw):
    base = {
        "pickup_location": "", "delivery_location": "", "stops": [], "weight_kg": 0, "vehicle_type": "",
        "customer_name": "", "cargo_description": "", "pickup_date": "", "delivery_date": "",
        "valid_until": "", "trip_type": "", "return_load_booked": "", "international": "", "border_post": "",
        "driver_nights": 0, "fuel_price_override": 0, "not_understood": [], "reply": "",
        "field_confidence": {},
    }
    base.update(kw)
    return base


LLM_CASES = {
    # LLM mis-converts "agt-en-twintig" to 20 t — the rules (0.95) win, confidence drops.
    "af_basic_numbers": llm_payload(
        pickup_location="Johannesburg", delivery_location="Durban", weight_kg=20000,
        cargo_description="steel coils", pickup_date="2026-10-09",
        reply="Reg so: staalrolle van Johannesburg na Durban, môre."),
    # LLM agrees with everything — confidence goes up.
    "en_basic": llm_payload(
        pickup_location="Johannesburg", delivery_location="Durban", weight_kg=28000,
        cargo_description="steel coils", pickup_date="2026-10-09",
        reply="Got it: 28 t steel coils, Johannesburg to Durban, tomorrow."),
    # LLM returns an insane weight and a malformed date — validation must drop both.
    "greeting_only": llm_payload(weight_kg=9_000_000, pickup_date="next week", trip_type="SOMETIMES",
                                 reply="Hi! Describe the load and I'll quote it."),
}


# Held-out phrases: written after the parser was tuned on CASES and never
# tuned against, so their score is the honest generalisation number.
HELDOUT = [
    {"id": "h1", "lang": "en", "text": "Got 30 tons of wheat to move from Bethlehem to Durban next Wednesday",
     "expect": {"weight": 30000, "cargo_description": "wheat", "pickup_location": "Bethlehem",
                "delivery_location": "Durban", "pickup_date": "2026-10-14"}},
    {"id": "h2", "lang": "af", "text": "Hoeveel vir vyftien ton kunsmis van Sasolburg na Kimberley?",
     "expect": {"weight": 15000, "cargo_description": "fertiliser", "pickup_location": "Sasolburg",
                "delivery_location": "Kimberley"}},
    {"id": "h3", "lang": "af", "text": "Koelwa van Kaapstad na Johannesburg, 18 ton vleis, Saterdag oplaai",
     "expect": {"vehicle_hint": "reefer", "pickup_location": "Cape Town", "delivery_location": "Johannesburg",
                "weight": 18000, "cargo_description": "meat", "pickup_date": "2026-10-10"}},
    {"id": "h4", "lang": "en", "text": "flatbed for 25t steel beams Vanderbijlpark to Port Elizabeth, one way",
     "expect": {"vehicle_hint": "flatbed", "weight": 25000, "cargo_description": "steel beams",
                "pickup_location": "Vanderbijlpark", "delivery_location": "Gqeberha", "trip_type": "ONE_WAY"}},
    {"id": "h5", "lang": "mixed", "text": "Joburg na Polokwane en back, loaded both ways, 20 ton cement",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Polokwane", "trip_type": "ROUND_TRIP",
                "weight": 20000, "cargo_description": "cement"}},
    {"id": "h6", "lang": "af", "text": "Ons gaan leeg terug kom van Upington af, 10 ton druiwe na Kaapstad",
     "expect": {"return_load_booked": False, "pickup_location": "Upington", "delivery_location": "Cape Town",
                "weight": 10000, "cargo_description": "grapes"}},
    {"id": "h7", "lang": "en", "text": "Harare from Joburg via Beitbridge, 34t fertiliser, superlink, 4 nights",
     "expect": {"pickup_location": "Johannesburg", "delivery_location": "Harare", "border_post": "Beitbridge",
                "international": True, "weight": 34000, "cargo_description": "fertiliser",
                "vehicle_hint": "interlink", "driver_nights": 4}},
    {"id": "h8", "lang": "af", "text": "drie en dertig ton steenkool, Ermelo na Richardsbaai, more oggend",
     "expect": {"weight": 33000, "cargo_description": "coal", "pickup_location": "Ermelo",
                "delivery_location": "Richards Bay", "pickup_date": "2026-10-09"}},
    {"id": "h9", "lang": "en", "text": "8000kg furniture Pretoria to George, deliver by the 20th",
     "expect": {"weight": 8000, "cargo_description": "furniture", "pickup_location": "Pretoria",
                "delivery_location": "George", "delivery_date": "2026-10-20"}},
    {"id": "h10", "lang": "en", "text": "Tanker, diesel from Durban to Lubumbashi, 35000 litres",
     "expect": {"vehicle_hint": "tanker", "pickup_location": "Durban", "delivery_location": "Lubumbashi",
                "international": True},
     "absent": ["weight", "fuel_price_override"]},
    {"id": "h11", "lang": "af", "text": "Tautliner asseblief, Bloem na Durban, 22 ton meel, Donderdag",
     "expect": {"vehicle_hint": "tautliner", "pickup_location": "Bloemfontein", "delivery_location": "Durban",
                "weight": 22000, "cargo_description": "flour", "pickup_date": "2026-10-15"}},
    {"id": "h12", "lang": "en", "text": "Need a side tipper 32 ton gravel Brits to Rustenburg today",
     "expect": {"vehicle_hint": "tipper", "weight": 32000, "cargo_description": "gravel",
                "pickup_location": "Brits", "delivery_location": "Rustenburg", "pickup_date": "2026-10-08"}},
    {"id": "h13", "lang": "mixed", "text": "Die client is Bokomo, 15 ton flour Paarl to Bellville",
     "customers": CUSTOMERS,
     "expect": {"customer_id": 13, "weight": 15000, "cargo_description": "flour", "pickup_location": "Paarl",
                "delivery_location": "Bellville"}},
    {"id": "h14", "lang": "en", "text": "Cape Town to Walvis Bay 28 tons wine return load sorted",
     "expect": {"pickup_location": "Cape Town", "delivery_location": "Walvis Bay", "international": True,
                "weight": 28000, "cargo_description": "wine", "return_load_booked": True}},
    {"id": "h15", "lang": "af", "text": "nege ton hoender bevrore, Rustenburg na Mahikeng, Vrydag aflewer",
     "expect": {"weight": 9000, "pickup_location": "Rustenburg", "delivery_location": "Mahikeng",
                "delivery_date": "2026-10-09"}},
    {"id": "h16", "lang": "en", "text": "pick up in nelspruit tomorrow drop in maputo 12 tons citrus",
     "expect": {"pickup_location": "Mbombela", "delivery_location": "Maputo", "pickup_date": "2026-10-09",
                "weight": 12000, "cargo_description": "citrus", "international": True}},
    {"id": "h17", "lang": "en", "text": "Twenty-four tonnes maize meal, Klerksdorp to Gaborone, cross-border",
     "expect": {"weight": 24000, "cargo_description": "maize meal", "pickup_location": "Klerksdorp",
                "delivery_location": "Gaborone", "international": True}},
    {"id": "h18", "lang": "af", "text": "Van Gqeberha na Oos Londen met 'n stop in Makhanda, 6 ton pakkies",
     "expect": {"pickup_location": "Gqeberha", "delivery_location": "East London", "stops": ["Makhanda"],
                "weight": 6000, "cargo_description": "parcels"}},
    {"id": "h19", "lang": "en", "text": "how much for a load to Durban",
     "expect": {"delivery_location": "Durban"}, "absent": ["pickup_location", "weight"]},
    {"id": "h20", "lang": "en", "text": "34 ton chrome Steelpoort to Maputo port via Lebombo",
     "expect": {"weight": 34000, "cargo_description": "chrome", "delivery_location": "Maputo",
                "border_post": "Lebombo / Ressano Garcia", "international": True}},
]


# English cargo words are kept as said (coordinator, 8 Oct: "chrome" stays
# "chrome", "gravel" stays "gravel"); four expectations above follow that.

# Round 2 inputs (toll/border branch): abnormal loads, trip_date, more border posts.
CASES += [
    {"id": "af_abnormale_vrag_lowbed", "lang": "af",
     "text": "Abnormale vrag op 'n lowbed, 45 ton transformator van Secunda na Lephalale, Maandag",
     "expect": {"abnormal_load": True, "vehicle_hint": "lowbed", "weight": 45000, "pickup_location": "Secunda",
                "delivery_location": "Lephalale", "pickup_date": "2026-10-12", "trip_date": "2026-10-12"}},
    {"id": "en_lowbed_implies_abnormal", "lang": "en",
     "text": "lowbed, 30 ton excavator from Rustenburg to Polokwane tomorrow",
     "expect": {"abnormal_load": True, "vehicle_hint": "lowbed", "weight": 30000, "trip_date": "2026-10-09"}},
    {"id": "en_oshoek", "lang": "en", "text": "Durban to Mbabane via Oshoek, 20 tons sugar",
     "expect": {"border_post": "Oshoek / Ngwenya", "international": True, "delivery_location": "Mbabane",
                "weight": 20000, "cargo_description": "sugar"}},
    {"id": "af_skilpadshek", "lang": "af", "text": "Joburg na Gaborone oor Skilpadshek, 28 ton sement",
     "expect": {"border_post": "Skilpadshek / Pioneer Gate", "international": True, "weight": 28000,
                "cargo_description": "cement"}},
    {"id": "en_groblersbrug", "lang": "en", "text": "Polokwane to Francistown through Groblersbrug, 30t maize",
     "expect": {"border_post": "Groblersbrug / Martin's Drift", "international": True, "weight": 30000}},
    {"id": "en_ariamsvlei", "lang": "en", "text": "Upington to Windhoek via Ariamsvlei, 25 tons grapes",
     "expect": {"border_post": "Nakop / Ariamsvlei", "international": True, "weight": 25000}},
    {"id": "af_kosi_bay", "lang": "af", "text": "van Richardsbaai na Maputo oor Kosi Bay, 10 ton vis",
     "expect": {"border_post": "Kosi Bay / Ponta do Ouro", "international": True, "pickup_location": "Richards Bay",
                "delivery_location": "Maputo", "weight": 10000, "cargo_description": "fish"}},
    {"id": "en_mamuno", "lang": "en", "text": "Gaborone to Windhoek via Mamuno, 30 ton copper",
     "expect": {"border_post": "Trans-Kalahari: Mamuno / Buitepos", "international": True,
                "pickup_location": "Gaborone", "delivery_location": "Windhoek", "weight": 30000}},
    {"id": "en_not_abnormal", "lang": "en", "text": "34 ton steel Joburg to Durban, not an abnormal load",
     "expect": {"abnormal_load": False, "weight": 34000}},
]


# ── Independent verifier's phrases (8 Oct 2026, written without seeing this
# parser; scratchpad/voice-verify/phrases.py), held out: never tuned against
# one by one. Place values may be a list of acceptable names; "_hint" is the
# vehicle_hint, "_absent" fields must not be filled, "_note" expects a
# not_understood entry. Evaluated with that company's customers and its full
# list of vehicle types.
VERIFIER_CUSTOMERS = [
    {"id": i, "name": n} for i, n in enumerate([
        "Shoprite Holdings Ltd", "Tiger Brands Ltd", "Pioneer Foods (Pty) Ltd", "Massmart Holdings Ltd",
        "Bidvest Group Ltd", "SA Steel Mills (Pty) Ltd", "Pick n Pay Stores Ltd", "Woolworths Holdings Ltd",
        "Sasol Ltd", "Distell Group Ltd", "Coca-Cola Beverages SA", "Clover Industries Ltd", "AVI Limited",
        "RCL Foods Ltd", "Astral Foods Ltd", "Imperial Logistics Ltd", "Super Group Ltd", "Famous Brands Ltd",
        "Nampak Ltd", "Consol Glass (Pty) Ltd"], start=1)
]
VERIFIER_FLEET = [
    {"name": n, "capacity_t": c} for n, c in [
        ("Light Delivery Vehicle (LDV)", 1.5), ("Medium Truck (4–8 tonnes)", 6), ("Heavy Truck (8–16 tonnes)", 14),
        ("Interlink (34 tonnes)", 34), ("Semi-Truck / Horse & Trailer (30 tonnes)", 30), ("Flatbed Truck", 20),
        ("Refrigerated Truck (Reefer)", 17), ("Tanker", 25), ("Box Truck", 5), ("Rigid Truck", 8),
        ("Tautliner", 22), ("Semi-Trailer Truck", 28)]
]
_VERIFIER_P = [
 ("af", "32 ton mielies van Bothaville na Durban Vrydag, leeg terug",
  dict(weight=32000, cargo_description=["maize","mielies"], pickup_location="Bothaville", delivery_location="Durban",
       pickup_date="2026-10-09", return_load_booked=False, trip_type="ONE_WAY")),
 ("en", "Need a quote for 18 tonnes of cement from PE to Mthatha next Tuesday",
  dict(weight=18000, cargo_description="cement", pickup_location=["Gqeberha","Port Elizabeth"], delivery_location="Mthatha",
       pickup_date=["2026-10-13","2026-10-20"])),
 ("af", "sement, 34 ton, Lichtenburg na Polokwane môre, superlink",
  dict(weight=34000, cargo_description="cement", pickup_location="Lichtenburg", delivery_location="Polokwane",
       pickup_date="2026-10-09", _hint="interlink")),
 ("af", "Kaapstad na Oos-Londen, 12 ton vrugte in 'n koelwa, oormôre",
  dict(pickup_location="Cape Town", delivery_location="East London", weight=12000, cargo_description="fruit",
       pickup_date="2026-10-10", _hint="reefer")),
 ("en", "steal coils 28 tons Joburg to Durbs tomorrow",
  dict(cargo_description="steel coils", weight=28000, pickup_location="Johannesburg", delivery_location="Durban",
       pickup_date="2026-10-09")),
 ("en", "Johannesberg to Pietermaritzberg 22 ton of paper rolls",
  dict(pickup_location="Johannesburg", delivery_location="Pietermaritzburg", weight=22000, cargo_description="paper rolls")),
 ("en", "eThekwini to Tshwane 30 ton containers round trip",
  dict(pickup_location="Durban", delivery_location="Pretoria", weight=30000, cargo_description="containers", trip_type="ROUND_TRIP")),
 ("en", "Mangaung to Msunduzi, 15 ton fertiliser",
  dict(pickup_location="Bloemfontein", delivery_location=["Pietermaritzburg","Msunduzi"], weight=15000, cargo_description=["fertiliser","fertilizer"])),
 ("en", "Rustenburg to Gaborone via Kopfontein, 25 ton chrome ore",
  dict(pickup_location="Rustenburg", delivery_location="Gaborone", border_post="Kopfontein / Tlokweng", international=True,
       weight=25000, cargo_description="chrome ore", _absent=["stops"])),
 ("en", "Musina to Harare via Beitbridge 30 ton maize, return load booked",
  dict(pickup_location="Musina", delivery_location="Harare", border_post="Beitbridge", international=True, weight=30000,
       cargo_description="maize", return_load_booked=True, trip_type="ONE_WAY")),
 ("en", "Nelspruit to Maputo through Lebombo 20 ton sugar",
  dict(pickup_location="Mbombela", delivery_location="Maputo", border_post="Lebombo / Ressano Garcia", international=True,
       weight=20000, cargo_description="sugar")),
 ("en", "Abnormal load: 45 ton transformer from Germiston to Lephalale on a lowbed, permit needed",
  dict(weight=45000, cargo_description="transformer", pickup_location="Germiston", delivery_location="Lephalale",
       abnormal_load=True, _hint="lowbed")),
 ("af", "abnormale vrag, 'n 60 ton graafmasjien van Witbank na Kathu",
  dict(abnormal_load=True, weight=60000, cargo_description=["excavator","graafmasjien"], pickup_location=["eMalahleni","Witbank","Emalahleni"],
       delivery_location="Kathu")),
 ("en", "8500 kg pallets Cape Town to George on 15 October",
  dict(weight=8500, cargo_description="pallets", pickup_location="Cape Town", delivery_location="George", pickup_date="2026-10-15")),
 ("en", "Bloem to Kimberley 12,5 ton wool",
  dict(weight=12500, cargo_description="wool", pickup_location="Bloemfontein", delivery_location="Kimberley")),
 ("en", "Upington to Cape Town with a stop in Springbok, 16 ton grapes, 2 nights out",
  dict(pickup_location="Upington", delivery_location="Cape Town", stops=["Springbok"], weight=16000, cargo_description="grapes", driver_nights=2)),
 ("af", "Joburg na Kaapstad oor Beaufort-Wes en Worcester, 20 ton meubels",
  dict(pickup_location="Johannesburg", delivery_location="Cape Town", stops=["Beaufort West","Worcester"], weight=20000, cargo_description="furniture")),
 ("en", "Diesel is R24.10 a litre, 28 ton coal Middelburg to Richards Bay",
  dict(fuel_price_override=24.10, weight=28000, cargo_description="coal", pickup_location="Middelburg", delivery_location="Richards Bay")),
 ("af", "diesel teen R23,85 per liter, Richardsbaai na Newcastle, 30 ton steenkool",
  dict(fuel_price_override=23.85, pickup_location="Richards Bay", delivery_location="Newcastle", weight=30000, cargo_description="coal")),
 ("en", "Joburg to Durban 28 steel",
  dict(pickup_location="Johannesburg", delivery_location="Durban", cargo_description="steel", _absent=["weight"], _note=True)),
 ("en", "Durban to Joburg 900 ton sand",
  dict(pickup_location="Durban", delivery_location="Johannesburg", cargo_description="sand", _absent=["weight"], _note=True)),
 ("en", "PE to Cape Town 20 ton timber, driver will sleep 3 nights",
  dict(pickup_location=["Gqeberha","Port Elizabeth"], delivery_location="Cape Town", weight=20000, cargo_description="timber", driver_nights=3)),
 ("af", "Pretoria na Pietersburg, 10 ton, heen en terug",
  dict(pickup_location="Pretoria", delivery_location="Polokwane", weight=10000, trip_type="ROUND_TRIP", _absent=["cargo_description"])),
 ("en", "for Astral, 24 ton chicken feed Standerton to Durban Monday",
  dict(customer_name="Astral Foods Ltd", weight=24000, cargo_description="chicken feed", pickup_location="Standerton",
       delivery_location="Durban", pickup_date="2026-10-12")),
 ("af", "kliënt is Clover, 18 ton melk van Bethlehem na Johannesburg Maandag",
  dict(customer_name="Clover Industries Ltd", weight=18000, cargo_description="milk", pickup_location="Bethlehem",
       delivery_location="Johannesburg", pickup_date="2026-10-12")),
 ("en", "Client is Shoprite, 22 ton groceries Centurion to Polokwane",
  dict(weight=22000, cargo_description="groceries", pickup_location="Centurion", delivery_location="Polokwane", _absent=["customer_id"])),
 ("en", "uh so like um twenty eight tons of copper cathodes from Lubumbashi to Durban via Kasumbalesa and Beitbridge",
  dict(weight=28000, cargo_description="copper cathodes", pickup_location="Lubumbashi", delivery_location="Durban", international=True)),
 ("en", "Windhoek to Walvis Bay 26 ton salt",
  dict(pickup_location="Windhoek", delivery_location="Walvis Bay", weight=26000, cargo_description="salt")),
 ("en", "Upington to Windhoek via Nakop, 20t cement, deliver by 14 Oct",
  dict(pickup_location="Upington", delivery_location="Windhoek", border_post="Nakop / Ariamsvlei", international=True, weight=20000,
       cargo_description="cement", delivery_date="2026-10-14")),
 ("en", "Maseru to Bloemfontein via Maseru Bridge 14 ton wool",
  dict(pickup_location="Maseru", delivery_location="Bloemfontein", border_post="Maseru Bridge", international=True, weight=14000, cargo_description="wool")),
 ("en", "Ermelo to Mbabane via Oshoek, 30 ton timber, empty back",
  dict(pickup_location="Ermelo", delivery_location="Mbabane", border_post="Oshoek / Ngwenya", international=True, weight=30000,
       cargo_description="timber", return_load_booked=False, trip_type="ONE_WAY")),
 ("af", "Kan jy my 'n prys gee vir 26 ton koring van Swellendam na Kaapstad volgende week Woensdag",
  dict(weight=26000, cargo_description="wheat", pickup_location="Swellendam", delivery_location="Cape Town", pickup_date="2026-10-14")),
 ("mixed", "Ons het 'n load of 20 tons tiles from Brits to Mahikeng tomorrow, flatbed asseblief",
  dict(weight=20000, cargo_description="tiles", pickup_location="Brits", delivery_location=["Mahikeng","Mafikeng"], pickup_date="2026-10-09",
       vehicle_type="Flatbed Truck")),
 ("en", "Gqeberha to Komani 6 ton motor parts, rigid",
  dict(pickup_location="Gqeberha", delivery_location=["Komani","Queenstown"], weight=6000, cargo_description="motor parts", vehicle_type="Rigid Truck")),
 ("en", "Emalahleni to Mbombela 30 000 kg coal",
  dict(pickup_location=["eMalahleni","Emalahleni","Witbank"], delivery_location="Mbombela", weight=30000, cargo_description="coal")),
 ("en", "Polokwane to Tzaneen 5 ton avocados today",
  dict(pickup_location="Polokwane", delivery_location="Tzaneen", weight=5000, cargo_description="avocados", pickup_date="2026-10-08")),
 ("en", "Joburg to Cape Town 30 ton bricks, pickup 2 October",
  dict(pickup_location="Johannesburg", delivery_location="Cape Town", weight=30000, cargo_description="bricks", _absent=["pickup_date"], _note=True)),
 ("en", "Durban to Durban 10 ton rice",
  dict(weight=10000, cargo_description="rice", _note=True)),
 ("en", "ten ton of something from somewhere",
  dict(weight=10000, _absent=["pickup_location","delivery_location"])),
 ("en", "Hello, how are you",
  dict(_absent=["pickup_location","delivery_location","weight","cargo_description"])),
 ("af", "Vryheid na Ulundi, ses ton hout",
  dict(pickup_location="Vryheid", delivery_location="Ulundi", weight=6000, cargo_description="timber")),
 ("en", "KwaMashu to uMhlanga, 3 ton bricks, LDV",
  dict(pickup_location="KwaMashu", delivery_location=["uMhlanga","Umhlanga"], weight=3000, cargo_description="bricks", _hint="ldv")),
 ("en", "Sasolburg to Secunda 34 000 litres diesel, tanker",
  dict(pickup_location="Sasolburg", delivery_location="Secunda", cargo_description="diesel", _absent=["weight"], _note=True, _hint="tanker")),
 ("en", "Joburg to Durban 28 ton steel coils, the truck is a 34 ton superlink",
  dict(pickup_location="Johannesburg", delivery_location="Durban", weight=28000, cargo_description="steel coils", _hint="interlink")),
 ("en", "From Kimberley to De Aar 18 tons scrap metal, pickup Friday deliver Saturday",
  dict(pickup_location="Kimberley", delivery_location="De Aar", weight=18000, cargo_description="scrap metal",
       pickup_date="2026-10-09", delivery_date="2026-10-10")),
 ("en", "Middelburg to Maputo 30 ton ferrochrome, diesel price R250",
  dict(pickup_location="Middelburg", delivery_location="Maputo", weight=30000, cargo_description="ferrochrome", international=True,
       _absent=["fuel_price_override"], _note=True)),
 ("en", "Thohoyandou to Giyani 7 ton maize meal, driver out 40 nights",
  dict(pickup_location="Thohoyandou", delivery_location="Giyani", weight=7000, cargo_description="maize meal", _absent=["driver_nights"], _note=True)),
 ("en", "Cape Town to Joburg 30 tons of cement and 25 tons of lime",
  dict(pickup_location="Cape Town", delivery_location="Johannesburg", _absent=["weight"], _note=True)),
 ("en", "abnormal load 120 ton transformer Majuba to Ankerlig",
  dict(abnormal_load=True, cargo_description="transformer", pickup_location="Majuba", delivery_location="Ankerlig")),
 ("af", "agt-en-twintig ton staalrolle van Jozi na eThekwini môre, retoervrag bespreek",
  dict(weight=28000, cargo_description="steel coils", pickup_location="Johannesburg", delivery_location="Durban", pickup_date="2026-10-09",
       return_load_booked=True, trip_type="ONE_WAY")),
 ("en", "Beitbridge to Lusaka 30 ton fertiliser via Chirundu",
  dict(pickup_location="Beitbridge", delivery_location="Lusaka", weight=30000, cargo_description="fertiliser", international=True)),
]


def _verifier_case(i, lang, text, exp, round1=True):
    exp = dict(exp)
    case = {"id": f"verifier_{i:02d}", "lang": lang, "text": text, "customers": VERIFIER_CUSTOMERS,
            "fleet": VERIFIER_FLEET, "absent": exp.pop("_absent", []), "not_understood": exp.pop("_note", False)}
    if "_hint" in exp:
        exp["vehicle_hint"] = exp.pop("_hint")
    if round1 and i == 26:
        # "Client is Shoprite": the verifier expected no match, but Shoprite
        # Holdings Ltd IS one of this company's customers (id 1) — matching it
        # is the intended behaviour, so the expectation is corrected here.
        case["absent"] = []
        exp["customer_id"] = 1
    if "customer_name" in exp:
        exp["customer_id"] = next(c["id"] for c in VERIFIER_CUSTOMERS if c["name"] == exp["customer_name"])
    case["expect"] = exp
    return case


VERIFIER = [_verifier_case(i, *p) for i, p in enumerate(_VERIFIER_P, 1)]
HELDOUT += VERIFIER


# ── Verifier round 2 (43 new phrases, 8 Oct 2026), held out the same way.
# "_weight_ok" lists acceptable weights (or None for "don't fill").
LDV = ["Light Delivery Vehicle (LDV)"]
_VERIFIER2_P = [
 ("af", "twee-en-twintig ton suiker van Malelane na Durban oormôre",
  dict(weight=22000, cargo_description="sugar", pickup_location="Malelane", delivery_location="Durban", pickup_date="2026-10-10")),
 ("af", "Ek soek 'n prys: 15 000 kg kunsmis, Potchefstroom na Klerksdorp, Dinsdag",
  dict(weight=15000, cargo_description=["fertiliser", "fertilizer"], pickup_location="Potchefstroom", delivery_location="Klerksdorp", pickup_date="2026-10-13")),
 ("af", "Tshwane na eMalahleni, dertig ton steenkool, die 15de",
  dict(pickup_location="Pretoria", delivery_location=["eMalahleni", "Emalahleni", "Witbank"], weight=30000, cargo_description="coal", pickup_date="2026-10-15")),
 ("en", "Load 26 tonnes of sunflower seed in Bethal, drop off at Randfontein on Saturday",
  dict(pickup_location="Bethal", delivery_location="Randfontein", weight=26000, cargo_description=["sunflower seed", "sunflower seeds"], delivery_date="2026-10-10")),
 ("en", "Ladysmith to Harrismith 8 ton of cooldrinks, collect Monday 12 October, deliver Tuesday",
  dict(pickup_location="Ladysmith", delivery_location="Harrismith", weight=8000, cargo_description=["cooldrinks", "cool drinks", "soft drinks"],
       pickup_date="2026-10-12", delivery_date="2026-10-13")),
 ("stt", "Gqeberha naar Kariega 4 ton motor onderdele",
  dict(pickup_location="Gqeberha", delivery_location=["Kariega", "Uitenhage"], weight=4000)),
 ("en", "Polokwane to Musina via Louis Trichardt 28 ton cement",
  dict(pickup_location="Polokwane", delivery_location="Musina", stops=[["Louis Trichardt"], ["Makhado"]], weight=28000, cargo_description="cement")),
 ("en", "eThekwini to KwaDukuza, 12 ton sugar cane",
  dict(pickup_location="Durban", delivery_location="KwaDukuza", weight=12000, cargo_description="sugar cane")),
 ("en", "Mahikeng to Lobatse via Ramatlabama, 20 ton mealie meal",
  dict(pickup_location=["Mahikeng", "Mafikeng"], delivery_location="Lobatse", border_post="Ramatlabama", international=True, weight=20000,
       cargo_description=["mealie meal", "maize meal"])),
 ("stt", "Johannesburg to Bulawayo, 30 ton steel beams, via Beit Bridge, back empty",
  dict(pickup_location="Johannesburg", delivery_location="Bulawayo", border_post="Beitbridge", international=True, weight=30000,
       cargo_description="steel beams", return_load_booked=False, trip_type="ONE_WAY")),
 ("en", "Durban to Manzini through Golela, 25 ton containers",
  dict(pickup_location="Durban", delivery_location="Manzini", border_post="Golela / Lavumisa", international=True, weight=25000, cargo_description="containers")),
 ("en", "Komatipoort to Maputo 34 ton chrome",
  dict(pickup_location="Komatipoort", delivery_location="Maputo", international=True, weight=34000, cargo_description="chrome")),
 ("en", "Bloemfontein to Maseru, 10 ton flour, Ficksburg bridge",
  dict(pickup_location="Bloemfontein", delivery_location="Maseru", border_post="Ficksburg Bridge / Maputsoe", international=True, weight=10000, cargo_description="flour")),
 ("en", "Springbok to Windhoek via Vioolsdrif, 18 ton grapes, 3 nights",
  dict(pickup_location="Springbok", delivery_location="Windhoek", border_post="Vioolsdrif / Noordoewer", international=True, weight=18000,
       cargo_description="grapes", driver_nights=3)),
 ("en", "Cape Town to Lusaka via Kazungula 30 ton wine",
  dict(pickup_location="Cape Town", delivery_location="Lusaka", international=True, weight=30000, cargo_description="wine", _absent=["border_post"])),
 ("en", "Abnormal: 52 ton crusher on a lowbed from Kimberley to Postmasburg",
  dict(abnormal_load=True, weight=52000, cargo_description="crusher", pickup_location="Kimberley", delivery_location="Postmasburg", _hint="lowbed")),
 ("af", "oorgrootte vrag, 'n transformator van 40 ton van Pretoria na Lephalale",
  dict(abnormal_load=True, weight=40000, cargo_description=["transformer", "transformator"], pickup_location="Pretoria", delivery_location="Lephalale")),
 ("en", "Joburg to PE 14,5t tyres, diesel R22.95",
  dict(pickup_location="Johannesburg", delivery_location=["Gqeberha", "Port Elizabeth"], weight=14500, cargo_description=["tyres", "tires"], fuel_price_override=22.95)),
 ("af", "Brandstof is R25,40 die liter. Worcester na Kaapstad, 9 ton appels",
  dict(fuel_price_override=25.40, pickup_location="Worcester", delivery_location="Cape Town", weight=9000, cargo_description="apples")),
 ("en", "Durban to Joburg 34 pallets",
  dict(pickup_location="Durban", delivery_location="Johannesburg", _absent=["weight"])),
 ("en", "Joburg to Cape Town, about 2 tons, bakkie",
  dict(pickup_location="Johannesburg", delivery_location="Cape Town", weight=2000, vehicle_type=LDV)),
 ("en", "Cape Town to Joburg 30 ton fridge goods, reefer, round trip loaded both ways",
  dict(pickup_location="Cape Town", delivery_location="Johannesburg", weight=30000, trip_type="ROUND_TRIP",
       vehicle_type="Refrigerated Truck (Reefer)")),
 ("en", "Mthatha to East London 6 ton building sand, client Bidvest",
  dict(pickup_location="Mthatha", delivery_location="East London", weight=6000, cargo_description="building sand", customer_name="Bidvest Group Ltd")),
 ("en", "Woolworths, 16 ton chilled food, Midrand to Bloemfontein, tomorrow morning",
  dict(customer_name="Woolworths Holdings Ltd", weight=16000, cargo_description="chilled food", pickup_location="Midrand",
       delivery_location="Bloemfontein", pickup_date="2026-10-09")),
 ("en", "Pick up 20 ton glass at Springs, deliver to Pietermaritzburg on 20 October",
  dict(pickup_location="Springs", delivery_location="Pietermaritzburg", weight=20000, cargo_description="glass", delivery_date="2026-10-20",
       _absent=["pickup_date"])),
 ("en", "Rustenburg to Brits 12 ton chrome, pickup 1 October",
  dict(pickup_location="Rustenburg", delivery_location="Brits", weight=12000, _absent=["pickup_date"], _note=True)),
 ("en", "Durban to Upington 30 ton salt pickup 5 Jan",
  dict(pickup_location="Durban", delivery_location="Upington", weight=30000, cargo_description="salt", pickup_date="2027-01-05")),
 ("stt", "uh Johannesburg to uh Kroonstad, nineteen tons uh of um mealies",
  dict(pickup_location="Johannesburg", delivery_location="Kroonstad", weight=19000, cargo_description=["maize", "mealies"])),
 ("stt", "Cape Town to Saldanha 28 tons iron or",
  dict(pickup_location="Cape Town", delivery_location=["Saldanha", "Saldanha Bay"], weight=28000)),
 ("en", "Pretoria to Mokopane, 30 ton platinum concentrate, flat deck",
  dict(pickup_location="Pretoria", delivery_location="Mokopane", weight=30000, cargo_description="platinum concentrate", vehicle_type="Flatbed Truck")),
 ("en", "Uitenhage to Joburg 22 ton car parts, superlink",
  dict(pickup_location=["Kariega", "Uitenhage"], delivery_location="Johannesburg", weight=22000, cargo_description="car parts",
       vehicle_type="Interlink (34 tonnes)")),
 ("af", "Nelspruit na Hazyview, 5 ton piesangs, Vrydag oplaai, Saterdag aflewer",
  dict(pickup_location="Mbombela", delivery_location="Hazyview", weight=5000, cargo_description="bananas", pickup_date="2026-10-09", delivery_date="2026-10-10")),
 ("af", "Kimberley na Upington, 20 ton, volgende Maandag",
  dict(pickup_location="Kimberley", delivery_location="Upington", weight=20000, pickup_date=["2026-10-12", "2026-10-19"])),
 ("en", "Sasolburg to Durban 25 ton plastic pellets, the client is Sasol",
  dict(pickup_location="Sasolburg", delivery_location="Durban", weight=25000, cargo_description="plastic pellets", customer_name="Sasol Ltd")),
 ("zu", "Ulundi to Nongoma 3 ton maize meal",
  dict(pickup_location="Ulundi", delivery_location="Nongoma", weight=3000, cargo_description="maize meal")),
 ("st", "Phuthaditjhaba to Bethlehem 7 ton timber",
  dict(pickup_location="Phuthaditjhaba", delivery_location="Bethlehem", weight=7000, cargo_description="timber")),
 ("en", "Mbombela to Bushbuckridge 10 ton citrus",
  dict(pickup_location="Mbombela", delivery_location="Bushbuckridge", weight=10000, cargo_description="citrus")),
 ("st", "Thaba Nchu to Botshabelo 4 ton bricks",
  dict(pickup_location="Thaba Nchu", delivery_location="Botshabelo", weight=4000, cargo_description="bricks")),
 ("en", "Joburg to Durban 28 000 steel coils",
  dict(pickup_location="Johannesburg", delivery_location="Durban", cargo_description="steel coils", _weight_ok=[None, 28000])),
 ("en", "Rustenburg to Durban 30 ton chrome, 31 ton max",
  dict(pickup_location="Rustenburg", delivery_location="Durban", _absent=["weight"], _note=True)),
 ("af", "Kaapstad na Johannesburg, 25 ton wyn, aflewer teen 16 Oktober",
  dict(pickup_location="Cape Town", delivery_location="Johannesburg", weight=25000, cargo_description="wine", delivery_date="2026-10-16",
       _absent=["pickup_date"])),
 ("af", "Harrismith na Durban, 30 ton mielies, leeg terug, 1 nag",
  dict(pickup_location="Harrismith", delivery_location="Durban", weight=30000, cargo_description="maize", return_load_booked=False,
       trip_type="ONE_WAY", driver_nights=1)),
 ("mixed", "Ja, ons moet 'n superlink load doen, 34 ton koring from Bethlehem to Durban next Friday, retoervrag is booked",
  dict(weight=34000, cargo_description="wheat", pickup_location="Bethlehem", delivery_location="Durban", pickup_date=["2026-10-09", "2026-10-16"],
       return_load_booked=True, trip_type="ONE_WAY", vehicle_type="Interlink (34 tonnes)")),
]


def _verifier2_case(i, lang, text, exp):
    exp = dict(exp)
    ok_weights = exp.pop("_weight_ok", None)
    case = _verifier_case(i, lang, text, exp, round1=False)
    case["id"] = f"verifier2_{i:02d}"
    if ok_weights is not None:
        case["expect"]["weight"] = list(ok_weights)  # None in the list = "not filled" is fine too
    return case


VERIFIER2 = [_verifier2_case(i, *p) for i, p in enumerate(_VERIFIER2_P, 1)]
HELDOUT += VERIFIER2
